### ISSUE TITLE
Underwhelming profile affiliation options

### ISSUE THREAD

**Issue by ribasushi** [metacpan/metacpan-web#1104]
I was logging in to update my profile, and was dismayed! Not only did the site make me feel bad about not having a STEAM user id, but it didn't offer me ways to celebrate my expression by linking to my [Grindr](http://grindr.com) and [Chaturbate](http://chaturbate.com) accounts. Please consider adding these options to the otherwise complete and reasonable list.

Cheers!

**Comment by oalders** [comment]
Am closing this for now.  Can re-open if there are objections.
