### ISSUE TITLE
Version-indepdent urls for source (non-pod) files

### ISSUE THREAD

**Issue by rwstauner** [metacpan/metacpan-web#1109]
When we added the /pod controller we expanded the namespace and created version-independent urls (based on distribution instead of release).
We specified (in #176) that we might do the same for non-pod urls for consistency.
#1094 and #1097 have specifically requested that (version-independent links to, for example, META files).

**Comment by haarg** [comment]
This endpoint exists now, but isn't yet used for anything except the search.cpan.org redirector.
