### ISSUE TITLE
API Help - Moving Search from front end to back end

### ISSUE THREAD

**Issue by Kapeli** [metacpan/metacpan-web#1114]
**Searching**
How do I perform a search using the API and have it return the same results you get by using the search field at metacpan.org? For example, these results for [LWP](https://metacpan.org/search?q=LWP)?

I tried http://api.metacpan.org/v0/_search?q=lwp but it doesn't return LWP. 

I guess I need a by-pod search, but http://api.metacpan.org/v0/pod/_search?q=lwp doesn't seem to work.

**Versioning**
Is there any API to get all the available versions for a pod/module?

Sorry if any of my terminology is wrong, I don't use Perl, just trying to integrate metacpan.org with [Dash](http://kapeli.com/dash). I have no idea what the difference between pod, module, release and distribution is.

**Comment by marcusramberg** [comment]
I'm very interested in seeing this happen. Anything I can do to help? What does the FfW 2014 tag mean?

**Comment by oalders** [comment]
@marcusramberg The OPfW label was for the "Outreach Program for Women", but since it was never assigned to an intern, I've just removed that label.  I think we could follow the suggestion I made above.  We should create a convenience endpoint which allows a proper module search.  This would be useful outside of the Dash use case.  Basically I think a lot of apps already do something similar, but they're all using some home rolled solution.  This would belong under the search convenience endpoint.

Sample convenience endpoints:

http://api.metacpan.org/v0/search/autocomplete
http://api.metacpan.org/v0/search/history
http://api.metacpan.org/v0/search/reverse_dependencies/ETHER/Moose-2.1402

To do the actual dev work, your best bet would be to set up the VM: https://github.com/CPAN-API/metacpan-developer

Lots of help is available in #metacpan. :)

**Comment by skarfacegc** [comment]
So, I started on this (didn't know about the project until @oalders mentioned this thread).

What I have so far is at https://github.com/skarfacegc/CPANDash  The getPods.pl currently fetches the list of Packages/Modules, writes them to the DB, generates the documentation url, then verifies all of the links (removing those that don't exist).  This takes ~30 hours to run (most of the time is validating the URLs) and it actually does seem to work.  Not sure how good the coverage is, or if I'm including too much junk.

I'm going to mess around with pulling down the pod docs, I'll update that repo as I get stuff.

**Comment by skarfacegc** [comment]
I have my script running now, pulling down the pod documentation and storing locally.  My testing on smaller sample sizes seems to be working fine.  I'll update this thread when my long run finishes (12+ hours running now, about halfway done with pulling the pods)

**Comment by lnxbil** [comment]
@skarfacegc Nice work! Are you generating everything? Maybe it would be good to build module documentation on demand like the gem-stuff for ruby?

**Comment by skarfacegc** [comment]
I'm downloading all of the pods in html form via the metacpan api.  My first full run just finished.  Moving the docs into place now to test.

**Comment by skarfacegc** [comment]
Doing a final run with some styling and syntax highlighting.  Will update once I publish it.

**Comment by oalders** [comment]
@skarfacegc what's the status on this?

**Comment by skarfacegc** [comment]
havent touched it in a while.  Work got busy and I kinda lost track of it.  I'll take a look to see where everything is and update.  I'm pretty sure I pushed all the most recent code to my repo.

**Comment by Relequestual** [comment]
Any further plans on this issue?
@skarfacegc's solution seems to work, but I guess doesn't really fit with how other third party sources work currently, right @Kapeli ?

**Comment by Kapeli** [comment]
Not sure I fully understand what @skarfacegc's approach does, but I'd say it doesn't fit with what I need.

Just to reiterate: what I need is a search API that searches for modules/pods given a query and once I have that I think I have everything I need.

**Comment by Relequestual** [comment]
I dunno if it's quite what you want @Kapeli , but it looks like you can do `/distribution/_search?q=DBIx-Class` (https://explorer.metacpan.org). However, you can search like `/distribution/_search?q=DBIx::Class` which is the format I expect people would use for perl modules. You could always replaces spaces with `::` or `-` with `::` though.

**Comment by Kapeli** [comment]
The issue is that the results aren't very good. For example, compare the results at http://api.metacpan.org/distribution/_search?q=lwp with the ones at https://metacpan.org/search?q=lwp.

**Comment by Relequestual** [comment]
Oh I totally agree! =[
Totally get that it needs to be an equally good expeirence. The annoying thing is, the CODE must be there, just needs to be put together, right? =/

**Comment by aufflick** [comment]
FWIW all, I have a really basic per-module script to generate docsets using the current metacpan api (inspired by @skarfacegc's script, but there's no way that would even ever finish running on Australian Internet!)

https://github.com/aufflick/p5-App-MetaCPAN-Dash

with the module installed you just:

    metacpan_dash.pl Acme::Bleach

To build and install a docset just for that distribution.

**Comment by oalders** [comment]
I haven't looked at the code, but we could look into periodically generating a docset on one of our MetaCPAN staging machines.

**Comment by Relequestual** [comment]
@aufflick I could run this over the weekend! Although I'd like to have a bit more documentation before doing so =]
You could pipe in all the modules one has installed on a system

**Comment by aufflick** [comment]
@Relequestual I'm planning to make my module read the current cpanfile and install/update docs for those modules.

**Comment by Relequestual** [comment]
@aufflick Consider making sure it's also the same verson of the module =]

**Comment by aufflick** [comment]
Hm good point - you may in fact want multiple versions for the same module
installed. I'll probably have to namespace the docsets somehow.

**Comment by Relequestual** [comment]
I mention because often in a production envrionment, you're limited to the version of the perl module for the distribution in use. So yes, you may want multiple versions of the docs also. I may use one version for work and another for pleasure.

**Comment by ranguard** [comment]
Closing as seems to relate to the API more than the web interface, if still need help please open an issue there.

**Comment by oalders** [comment]
Actually, let's keep this one open.  This is an issue I have some interest in seeing resolved.  It _is_ more about the API, but it's OK to leave it here.

**Comment by oalders** [comment]
This search API now exists on the back end.  It just needs to be documented.

**Comment by oalders** [comment]
@Kapeli we were chatting about this issue last night.  We haven't forgotten about it.

**Comment by oalders** [comment]
@Kapeli the endpoint has now been documented: https://fastapi.metacpan.org/static/index.html  I'm going to close this issue but if you have any questions at all, please open a new issue and we'll chat about it there.

**Comment by oalders** [comment]
Thank *you*.  I use Dash pretty much every day.  👍
