### ISSUE TITLE
Modules are being found, and indexed in search, in a distribution's local/ directory

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-web#1239]
https://metacpan.org/release/HTTP-Thin-UserAgent (version 0.008) is displaying documentation for, and also indexing as the first result in search, many modules that are not rightfully "provided" in the documentation.

(Does metacpan respect the meta 'provides' field, when present?  that would help in general, although not in this case since that field wasn't included in META.*.)

**Comment by rwstauner** [comment]
https://github.com/CPAN-API/cpan-api/commit/4f034ea52e22e2c7ab062d3c778848c4ab58c6f9
