### ISSUE TITLE
Documentation links to perlfunc don't work the same they they do on search.cpan.org

### ISSUE THREAD

**Issue by trinitum** [metacpan/metacpan-web#1241]
It seems `X<...>` formatting code is ignored by metacpan's pod parser. Links like `L<perlfunc/flock>` are working on search.cpan.org, but not on metacpan. If you look into perlfunc, the flock section looks like this:

```
=item flock FILEHANDLE,OPERATION
X<flock> X<lock> X<locking>
```

And thanks to `X<flock>` you can just specify link as `L<perlfunc/flock>` and it will work. On metacpan though, this code is ignored and there's no `#flock` anchor on perlfunc page. As I understand the only way to link to flock description is something like `L<perlfunc/"flock FILEHANDLE,OPERATION">`, which is not nice at all even if it works (I'm not sure if it is).

**Comment by haarg** [comment]
As far as I can tell, search.cpan.org has a special case for perlfunc to add the expected anchors.  There doesn't seem to be any generalized way this could be done, so we have to decide if we want to add a similar special case.  I can work on the code if others agree.

**Comment by oalders** [comment]
Special casing this sounds fine to me.

**Comment by haarg** [comment]
metacpan/metacpan-api#608 addresses this

**Comment by haarg** [comment]
This has been implemented.
