### ISSUE TITLE
Changed picture on Gravatar, but not updated on metacpan

### ISSUE THREAD

**Issue by mschilli** [metacpan/metacpan-web#1262]
Hi, I updated the picture associated with my CPAN email address on Gravatar last week

```
http://www.gravatar.com/avatar/df2a8f488042c13a4fe2a6b312dcdaa0.png
```

but the new image hasn't made it to metacpan (or seach.cpan.org for that matter) yet. The FAQ says that images are cached and to "give it a day or two", but it's been exactly a week (7/26), so I wonder if the cache is working correctly, would be great if you could check. Thanks!

**Comment by initself** [comment]
[Adding a Gravatar to PAUSE Account](http://blogs.perl.org/users/initself/2019/02/adding-gravatar-to-pause-account.html)
