### ISSUE TITLE
"Changes since last release" compares versions poorly

### ISSUE THREAD

**Issue by tsibley** [metacpan/metacpan-web#1289]
https://github.com/CPAN-API/metacpan-web/blob/master/lib/MetaCPAN/Web/Model/API/Changes.pm#L45 should be numifying both versions with `MetaCPAN::Util::numify_version()` and then comparing them with `==`.

In the case of https://metacpan.org/release/App-RecordStream, for example, the release version is `v4.0.6` (from the META.yml) but the version in the CPAN::Changes::Release object is `4.0.6`.  This causes no "changes since last release" to be shown.

**Comment by haarg** [comment]
This is working now.
