### ISSUE TITLE
Logging in with GitHub does not seem to work (at least if you haven't a MetaCPAN account yet)

### ISSUE THREAD

**Issue by xtaran** [metacpan/metacpan-web#1331]
If I click on the _Sign In_ → _GitHub_ link, I'm redirected to https://api.metacpan.org/user (after at least one redirect, no query string in the final location) and it just shows me `{}` and I'm not logged in afterwards, e.g. if I reload the MetaCPAN FAQ, it still shows me the _Sign In_ menu on the top right.

I have no MetaCPAN account yet, but I am logged in into GitHub. It seems to work fine if I use my Twitter account instead (being logged in there, too), but I don't want to use my Twitter account for MetaCPAN.

**Comment by ranguard** [comment]
We think this is solved - please comment if not
