### ISSUE TITLE
Can't view favorites under my profile

### ISSUE THREAD

**Issue by Farow** [metacpan/metacpan-web#1337]
I have no pause account. However, the modules that I have ++'d appear blue but do no show up on https://metacpan.org/account/favorite/list

**Comment by Flimm** [comment]
+1

**Comment by neilbowers** [comment]
When you hit the ++ button, does the count of ++'s change, even if just temporarily?

**Comment by Flimm** [comment]
Yes, it does, permanently and across browsers. I don't appear in the PAUSE users list, though, even though I am one.

**Comment by p-alik** [comment]
I've a pause account but in my case only ++button changes on click.
The favorite list is still empty.

**Comment by kadavr** [comment]
I have the same problem=( pause account: HAMMER

**Comment by ranguard** [comment]
pause accounts are not needed for this feature.

We think this is solved - please comment if not

**Comment by kadavr** [comment]
Приветствую. Этот email утонул в спаме.
Если Вам нужен личный контакт со мной, то пожалуйста пишите на evgeniy (dog) just4i.ru.

Greetings. This email address was drowned in spam.
If you need a personal contact with me, please write to evgeniy (dog) just4i.ru.

email: evgeniy (dog) just4i.ru
tel    : +79252587282

**Comment by p-alik** [comment]
just tested, it works fine to me. Thanks
