### ISSUE TITLE
Support alternative author contact points than just IRC

### ISSUE THREAD

**Issue by haarg** [metacpan/metacpan-web#1380]
Based on the discussion about the IRC sidebar link (#1235, #1360), it would be good to be able to promote alternative contact points for a module's author or community.  This might be a mailing list, an email address, a github repo, or just an arbitrary web link.  Some of these already have support in the meta spec, or commonly used conventions for that.  And authors may want to promote multiple of these or just one.

I can think of a couple ways to present this.  One is with either a modal dialog or a hover popup (like we use for GitHub repo links).  This allows showing multiple links, and using more detail such as showing a raw irc:// link.  Another option is to try to limit the contact point to a single contact point, but allowing the author to chose that using metadata somehow.

**Comment by ranguard** [comment]
@haarg are you likely to work on this, or should we close for now?

**Comment by haarg** [comment]
I've added support for a resource `x_chat`, which covers this well enough. Other options could be added if someone had a concrete proposal.
