### ISSUE TITLE
not fetching issue count from RT when "NoAuth" URL used

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-web#1392]
example: https://metacpan.org/release/CGI-Simple

The issue link in metadata is "http://rt.cpan.org/NoAuth/Bugs.html?Dist=CGI-Simple", and the associated issue count is not being fetched - presumably because this isn't recognized as an RT link, so the RT interface isn't being used?

**Comment by ranguard** [comment]
@karenetheridge is this still a problem?

**Comment by karenetheridge** [comment]
This seems to be fixed now (I checked some other distributions that were still using NoAuth URLs) -- thanks!
