### ISSUE TITLE
exclude inc/ directories from search indexing

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-web#1411]
https://metacpan.org/search?q=Module%3A%3AInstall contains a huge number of results for bundled inc/ directories, which are generally not relevant, and should be excluded from search indexing.

**Comment by rwstauner** [comment]
https://github.com/CPAN-API/cpan-api/commit/4f034ea52e22e2c7ab062d3c778848c4ab58c6f9

**Comment by rwstauner** [comment]
i fixed this and reindexed a bunch of dists that looked to be problematic.
The search results look much better now.

**Comment by karenetheridge** [comment]
@rwstauner fantastic; many thanks!
