### ISSUE TITLE
The reverse dependencies page lists Mo twice for IO-All

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-web#1424]
If you look at the reverse dependencies page for IO-All:

> https://metacpan.org/requires/distribution/IO-All

You'll see that Mo 0.38 and Mo 0.39 are both listed.

My first thought is that maybe INGY might be ballot-stuffing to support his grant application, but more likely (a) it's a bug in MetaCPAN, or (b) he's changed the dist name in Mo.

I checked META.yml for both releases, and they're the same, so chanelling SHOLMES, I suspect it's a MetaCPAN issue.

Neil

**Comment by simbabque** [comment]
It's now Mo 0.40 and it's only listed once.

**Comment by oalders** [comment]
@simbabque thanks for updating this ticket!
