### ISSUE TITLE
Please provide a way to keep me logged in!

### ISSUE THREAD

**Issue by timbunce** [metacpan/metacpan-web#1489]
This is my number one irritation with metacpan.
I end up not interacting with the advanced features because I'm never logged in.
I'm never logged in because metacpan keeps timing out my session.
And when it times out my session it forgets who I am. In 2015.

An option to "keep me logged in on this computer" would be fine.

Or, _always keep people logged in_ and only check authentication when they try to do something 'significant' and the authentication hasn't been checked 'recently'. This is how many sites, including amazon, work.

It would make a big different to have the personalization features always available.

**Comment by oalders** [comment]
I wonder what's going on here.  I'm logged in for months at a time.  @timbunce how quickly are your sessions timing out?  browser? OS?

**Comment by rwstauner** [comment]
Also, which provider(s) do you use to login?

**Comment by timbunce** [comment]
@oalders, I've not paid attention to the time. I logged in around the time I created the issue, and I'm still logged in now. So it's lasted ~8 hours so far. I'll check again tomorrow,
@rwstauner, github.

**Comment by oalders** [comment]
@timbunce browser + OS?

**Comment by timbunce** [comment]
Safari on OS X 10.9.5.

**Comment by timbunce** [comment]
I'm still logged in now, 2 days later. So the behaviour seems better than when I last logged in. (I'd love to be able to let you when that was but I've forgotten. I gave up logging in regularly many months ago.)

**Comment by timbunce** [comment]
I'm still logged in so I'm going to assume that something was fixed a while ago after I'd given up logging in so often. So I'll close this case now. I should have rechecked before opening it. I'm sorry for the noise.

**Comment by timbunce** [comment]
I noticed today that I'm no longer logged in. How long should I expect to stay logged in and would e.g. a browser restart cause a logout?

**Comment by oalders** [comment]
Your session should survive a restart.  We only prune sessions which have not been updated after X months, so if you're being kicked after a few days something is very wrong.

**Comment by timbunce** [comment]
I rebooted my machine today and that didn't log me out. So it seems to be on your end.

**Comment by rwstauner** [comment]
When you get logged out of metacpan, are you also logged out of github?

**Comment by timbunce** [comment]
Nope. I can't remember the last time I saw the github login page. (I just tried logging out of github to check what it looked like.)

**Comment by timbunce** [comment]
In case it helps: the 'Authorized applications' section of my github settings page says MetaCPAN was "Last used on Mar 22, 2015" (whatever 'used' may mean).

**Comment by rwstauner** [comment]
Hmm... mine says "last used" January, and i'm still logged in to both.
Do you have your pause account linked?  what about any other accounts?
When logged in to metacpan, If i click Account (top right) and Identities,
I see github and pause linked.

**Comment by timbunce** [comment]
github, pause, and twitter are linked.

**Comment by oalders** [comment]
@timbunce what's the current status on your staying logged in?

**Comment by ranguard** [comment]
Closing - think now fixed
