### ISSUE TITLE
Incorrect result count in author page

### ISSUE THREAD

**Issue by book** [metacpan/metacpan-web#1507]
When opening my author page https://metacpan.org/author/BOOK the text below the search box at the top shows "_47_ results (0.015 seconds)", when there are actually only **46** distributions on my page.

It's however correct for other authors I've tried:
- https://metacpan.org/author/ELBEHO (1)
- https://metacpan.org/author/VPIT (30)
- https://metacpan.org/author/SAPER (41)

Could the fact that I have one _deleted_ distribution (WWW-Gazetteer-HeavensAbove, not showing on metacpan) explain this?

**Comment by kentfredric** [comment]
Also, it doesn't make sense at all to me why this number needs to be in such an important location for this kind of result. You're not even doing a search query, its a static link. IT might be useful as a footnote, but cluttering the page =>?

https://github.com/CPAN-API/metacpan-web/issues/1550#issuecomment-119088084

**Comment by book** [comment]
I find it interesting to know how many distributions an author has released, but I agree it's not crucial information.

**Comment by oalders** [comment]
This looks like it's now fixed.
