### ISSUE TITLE
Display of ratings varies based on search size

### ISSUE THREAD

**Issue by rwstauner** [metacpan/metacpan-web#1508]
Seems fairly reproducible.

![metacpan-size-ratings](https://cloud.githubusercontent.com/assets/142719/7255084/eeaed9be-e7fb-11e4-9a51-b768e17e1cde.png)

Note that it doesn't merely disappear,
_which_ dists get ratings seem to vary based on the search size,
so there's probably a miscalculation about which page of results to get ratings for.

**Comment by haarg** [comment]
We've removed ratings, so this is no longer relevant.
