### ISSUE TITLE
Large amount of whitespace at the top

### ISSUE THREAD

**Issue by rwstauner** [metacpan/metacpan-web#1550]
There's a rather large amount of whitespace at the top of the page.

I hadn't noticed this until I was looking at #1548.
The whitespace seems to be present without that addition, but the extra row of input fields makes the area look even larger.

![screenshot - 06202015 - 08 34 35 am](https://cloud.githubusercontent.com/assets/142719/8267929/4c8caf66-1727-11e5-869c-49907ca48de1.png)

Is it just my eyes, or does anyone else agree that that's too much space?

**Comment by kentfredric** [comment]
There is also new contamination in this whitespace listing the numbers of results. These are static pages as far as I'm concerned, not "Searches", so how many "results" it gave is not really interesting, especially this high up the page.

![sn152](https://cloud.githubusercontent.com/assets/44790/8540070/5527188e-24d6-11e5-86bb-4eb248d5cb88.png)
![sn151](https://cloud.githubusercontent.com/assets/44790/8540069/5525d488-24d6-11e5-896f-7a734550be33.png)
![sn150](https://cloud.githubusercontent.com/assets/44790/8540071/55277e32-24d6-11e5-937a-00465374a17a.png)

**Comment by oalders** [comment]
Yep, let's get rid of the result stats on these pages.

**Comment by ranguard** [comment]
Seems ok to me now - closing for now - do comment if still and issue

**Comment by kentfredric** [comment]
This is still an issue. We've just gotten used to the sub-par nature.

**Comment by ranguard** [comment]
Thanks - reopened
