### ISSUE TITLE
Old releases entirely missing from version dropdown

### ISSUE THREAD

**Issue by kentfredric** [metacpan/metacpan-web#1565]
0.12 is nowhere to be found on the primary list, but it exists.

![sn172](https://cloud.githubusercontent.com/assets/44790/8888492/a6b982d2-3303-11e5-820c-24213c3af47c.png)
![sn173](https://cloud.githubusercontent.com/assets/44790/8888491/a66c1024-3303-11e5-88b7-733692f5c523.png)
![sn174](https://cloud.githubusercontent.com/assets/44790/8888490/a64020ea-3303-11e5-8879-df68e73bffa8.png)

**Comment by haarg** [comment]
Fixed on v1.
