### ISSUE TITLE
reduce conflicts between HTML ids in content vs chrome

### ISSUE THREAD

**Issue by haarg** [metacpan/metacpan-web#1590]
MetaCPAN has HTML ids that it uses in many places for javascript interactions and styling.  These ids can sometimes conflict with the generated ids in pod content.  We should try to reduce the conflict between these as much as possible.  Possibly by prefixing all of our own ids, or at least making them more unique.

As an example of this, 67782416093099323d27f92996af7deb4812ccdf added a field with id="size", meaning that you can no longer link to a section named "size" in any pod pages.

**Comment by gordon-fish** [comment]
I would like to take this one on. Feel free to put me as "assignee" (assuming I'm understanding how that works correctly.)

**Comment by haarg** [comment]
Fixed by #2530
