### ISSUE TITLE
files not sorted in "Browse" view of a dist?

### ISSUE THREAD

**Issue by wchristian** [metacpan/metacpan-web#1602]
I'm seeing this:

https://metacpan.org/source/JJNAPIORK/Catalyst-Runtime-5.90101/lib/Catalyst

![screenshot 2015-10-13 18 12 59](https://cloud.githubusercontent.com/assets/175467/10460778/36c88e34-71d6-11e5-8465-656f2a23370b.png)

**Comment by haarg** [comment]
There are two things going on here.  First is the the Javascript was not loading.  This is a caching issue that has been covered elsewhere.  I've resolved this for the moment by purging the Fastly cache.

Second is that the raw HTML served is not sorted.

**Comment by gordon-fish** [comment]
I can confirm that it is properly sorting in recent versions of Firefox, Chrome, IE, Edge, and Safari, so unless there is a further problem that I'm not seeing, this should perhaps be closed.

**Comment by oalders** [comment]
Thanks @gordon-fish!
