### ISSUE TITLE
favourites number updates incorrectly

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#1616]
I'm sure there's already an open issue for this, but I cant' find it.  I just added https://metacpan.org/pod/CPAN::Repository to my list of favourites.  The `++` turned blue, but the number in the right margin did not. It remains at 1.  However, https://metacpan.org/release/CPAN-Repository/plussers shows two users.  I have co-maint on this distribution -- wondering if that's part of the problem.

**Comment by agrinevich** [comment]
Found the same problem. 
Pressed - numbers turned blue. Then checking Account/Favorites and there's nothing. Then checking previous page again and there's old ++ value. Add to favorite doesn't work.

**Comment by smith153** [comment]
Similar issue with me. Anything I ++ does not go into my favorites and the numbers for 'non-PAUSE users' gets incremented, even though I am logged with with my cpan pause account (esaym).

**Comment by ranguard** [comment]
This all seems to be caching related, I'll take it on

**Comment by ranguard** [comment]
Think now sorted - if not please comment and we'll re-open
