### ISSUE TITLE
Pages of some dists have http content

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#1623]
I've just today noticed that there are some pages (well, one anyway) on https://metacpan.org/ generating warnings in the browser about unencrypted items (Firefox 42.0). The page for [File::Which](https://metacpan.org/pod/File::Which) is one such, although I haven't managed to spot which entity on that page is causing the problem.

I found an old issue (#361) which might be related to this but was closed apparently without total resolution. Sorry I can't be of more help but wanted to make sure that this issue didn't go unrecorded.

**Comment by oalders** [comment]
Is this the problem? `<div class="breadcrumbs" itemscope itemtype="http://schema.org/SoftwareApplication">`

**Comment by haarg** [comment]
This is going to be mostly due to gravatars in the plussers list.

We have functions that will rewrite the URLs to use https where possible.  But users can specify arbitrary URLs for their avatar, which often aren't available via https.  I've just some improvements to the code that rewrites the URLs which will handle the particular case that is showing up on File::Which, but it isn't a full solution.

To fix this properly we'd need to cache the non-gravatar avatars locally.

**Comment by openstrike** [comment]
@oalders Apparently not. That was my initial thought too, but it's present in other pages (eg. [Test::Simple](https://metacpan.org/pod/Test::Simple) where the browser doesn't issue the same warning.

**Comment by oalders** [comment]
I'd also be fine with either forcing everyone to use Gravatars or just not displaying gravatars which aren't available via https.  Allowing people to use something other than Gravatar has been the source of subtle bugs for quite a while now.

**Comment by openstrike** [comment]
ICBW but even if you allow avatars from other, arbitrary https URLs doesn't that just move the problem to https URLs with bad certs (because of unkown issuer / bad expiry / SHA-1 / weak cipher / whatever)? Either mandating Gravatars or local caching sound like winners, though.

**Comment by moltar** [comment]
This one has it: https://metacpan.org/pod/Plack::App::Directory

It's the user pic of one of ++ed users: http://www.kjetil.kjernsmo.net/images/kjetil-square-2015.jpg

**Comment by haarg** [comment]
This should be fixed now.
