### ISSUE TITLE
highlight modules or dists with ADOPTME or HANDOFF or NEEDHELP

### ISSUE THREAD

**Issue by rjbs** [metacpan/metacpan-web#1643]
It is intolerably hard to declare that you don't want to deal with a CPAN module anymore.  No matter what, it just sits there under your name, inviting bug reports, no matter how many times you say "No, I'm done."  (It's even worse if you're only co-maint, but that's another matter.)

One accepted but basically unsupported solution is to [use special permissions users](http://neilb.org/2013/08/07/adoptme.html) to indicate the idea that you want to transfer permissions away, or just get more hands at work.  Unfortunately, _nobody benefits from this_, because _nobody can tell_ they've been assigned unless they go look in 06perms, which is far, far more than anyone should be expected to do.

It would be useful if the MetaCPAN web site would throw up a big notice like:
- ADOPTME: This distribution is up for adoption!  Contact the modules list if you want to take over.
- HANDOFF: This distribution's maintainer is looking for someone to take over!  Contact them…

**Comment by neilb** [comment]
:+1:

**Comment by oalders** [comment]
This can be done once https://github.com/CPAN-API/cpan-api/pull/338 is merged.  I'll have another look at why that never made it into master.

**Comment by neilb** [comment]
I've written up [my thoughts](http://neilb.org/2016/02/13/it-takes-a-community.html) about this.

**Comment by rjbs** [comment]
@neilb Your blog post actually doesn't address HANDOFF or ADOPTME at all, from what I can see.

**Comment by neilb** [comment]
@rjbs: bugger, I thought about those at one point, then forgot to factor them in. ta!

**Comment by karenetheridge** [comment]
See also https://github.com/CPAN-API/metacpan-web/issues/952 and the wishlist section of the wiki.

**Comment by neilb** [comment]
@rjbs I've updated my blog post, to talk about HANDOFF, ADOPTME, NEEDHELP, and deprecated as well.

**Comment by dolmen** [comment]
Just for information: there is a place where permissions are a bit more visible that in 06perms: on rt.cpan.org, above the bug list of the distribution. That's where I usually lookup perms.
Here are a few interesting links:
https://rt.cpan.org//Dist/ByMaintainer.html?Name=ADOPTME
https://rt.cpan.org/Dist/ByMaintainer.html?Name=HANDOFF
https://rt.cpan.org/Dist/ByMaintainer.html?Name=NEEDHELP

**Comment by dolmen** [comment]
@neilb And speaking about rt.cpan.org, 06perms gives special power on RT tickets:
- only maintainers (or co-maint) can edit [maintainer's notes](http://blogs.perl.org/users/dolmen/2014/04/maintainers-notes-on-rtcpanorg.html).
- only maintainers and requestors can change the state of a ticket

**Comment by neilb** [comment]
@dolmen -- thanks, I wasn't aware of those!

I'll update my blog post.

**Comment by xdg** [comment]
My commentary: http://www.nntp.perl.org/group/perl.cpan.workers/2016/02/msg1400.html

**Comment by ThisUsedToBeAnEmail** [comment]
I guess this is me volunteering.

I had a play with this today and have a working end to end for NEEDHELP displaying at /release/* (was the first flag I came across inside of the demo data).

<img width="1015" alt="Screenshot 2019-11-07 at 21 18 56" src="https://user-images.githubusercontent.com/16151791/68392324-85d7d400-01a4-11ea-8431-560c42ff67ed.png">

The idea with the button is it will be a mailto link that will provide the maintainers email, a default subject and body.

I would like clarification on whether you think is acceptable, whether the position of my notification is correct and also what the exact title, text and email should be for each state. 

On the perl side I have made some modifications to the ReleaseInfo Model so it also retrieves permissions. Currently this is using releases main_module to make a single api request. I see inside the Permission model that you can pass a distribution but that will iterate all modules within it. I'm assuming it exists for a reason but would like clarification that permissions can be set at module level within a distribution and not just at dist level. ((1 vs $#modules) requests).

Regards Robert.

**Comment by oalders** [comment]
> I guess this is me volunteering.

👍 

> permissions can be set at module level within a distribution and not just at dist level

Right.  Essentially all permissions are at module level, since PAUSE doesn't have a concept of a dist.

I wonder if we'd want a button in the side bar as well, which could be displayed for the individual modules.  Not everyone will make it over to the release page.  In theory, someone could mark some, but not all, modules in a dist as `ADOPTME` etc.  Not sure if that's the case in practice, but we should keep it in mind.

**Comment by ThisUsedToBeAnEmail** [comment]
> In theory, someone could mark some, but not all, modules in a dist as `ADOPTME` etc. Not sure if that's the case in practice, but we should keep it in mind

If this is the case perhaps it may not make sense to display a notification at the release page. You may end up with a distribution that has all three states which may look a bit convoluted.

**Comment by oalders** [comment]
> If this is the case perhaps it may not make sense to display a notification at the release page. You may end up with a distribution that has all three states which could look a bit convoluted.

Right, there could be some cases where this would be really confusing.  If we were to display it on the release page we'd first have to check that every module in the dist has the appropriate `ADOPTME` etc.  The other possibility would be to mark each individual module on the release page which is flagged in `06perms` for needing help.

**Comment by haarg** [comment]
I think it would be fair to have that banner on the release page if any of the modules were marked as ADOPTME/HANDOFF.  But also just basing it on the main module should be fine.

But having something on the module pages is probably more important, since those pages are often the only ones people look at.

**Comment by neilb** [comment]
I agree with @haarg: if the main module for a dist has ADOPTME or NEEDHELP, then assume it applies to the dist, and then when looking at a specific module's page, it could say "this distribution's maintainer is looking for help".

If the dist has been [marked as deprecated](http://neilb.org/2015/01/17/deprecated-metadata.html), then the message displayed should probably reflect that as well.

**Comment by haarg** [comment]
See #1435 for discussion around deprecated modules.

**Comment by ThisUsedToBeAnEmail** [comment]
Okay so will continue to use main_module to display the notification on the /release page. I am not keen on displaying multiple notifications for each ADOPTME, HANDOFF and NEEDHELP. So will look into whether it is more logical to display the first or last found in the list of permissions.

As for module level should we also display a notification banner and a side button or just the button?

On deprecated this is already retrievable from release{deprecated}, this seems to be set at 'distribution' level. If my understanding is correct "you" (the people who decided to implement this stuff) have got it backwards because it seems much more logical to be able to deprecate a module within a distribution than to ask someone to adopt it.

**Comment by haarg** [comment]
If the entire distribution is deprecated, that is indicated with a `x_deprecated` field at the top of the distribution metadata.  If an individual module is deprecated, that is indicated by a `x_deprecated` field in the module data inside `provides`.

**Comment by ThisUsedToBeAnEmail** [comment]
So a misunderstanding all of this is new and I should probably do more research/reading over assumptions but thanks for the clearing that up.
