### ISSUE TITLE
Show River position on a distribution's home page

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-web#1679]
Once we have the river position data in MetaCPAN's API (see [this issue](https://github.com/CPAN-API/cpan-api/issues/460)), it would be great if the home page for a distribution showed its river position.

Just showing the total number of downstream dependencies isn't helpful enough on its own, and giving the river position as an index probably won't be easily grokkable by most users. I've ended up using logarithmic bins for chunking the river:
- **0**: no CPAN distributions depend on this
- **1**: between 1 and 9
- **2**: 10 - 99
- **3**: 100 - 999
- **4**: 1000 - 9999
- **5**: 10k+

This is the _bucket_ number in the JSON format proposed in [issue 460](https://github.com/CPAN-API/cpan-api/issues/460). This figure could then be used for a graphic, perhaps displayed next to the number of favourites. We could show this in the style of an LED power meter:

> ![river-meter](https://cloud.githubusercontent.com/assets/478461/14761234/2e31b9f8-0952-11e6-8b41-90016efd0670.png)

The tooltip could then say something like "System-Command has 4 direct dependents and 92 downstream dependents in total".

To date I've generally shown the river going the other way, but I think it will be more immediately grokkable this way round (for LTR users, and I don't suggest we support both LTR and RTL!).

**Comment by dolmen** [comment]
We need just 5 symbol (not 6) for your scale.

Here are some ideas with Unicode symbols:
```
$ perl -C -E 'say "\N{U+2652} " x ($_), "\N{U+268A} " x (5-$_), "\n" for 0..5'
⚊ ⚊ ⚊ ⚊ ⚊ 

♒ ⚊ ⚊ ⚊ ⚊ 

♒ ♒ ⚊ ⚊ ⚊ 

♒ ♒ ♒ ⚊ ⚊ 

♒ ♒ ♒ ♒ ⚊ 

♒ ♒ ♒ ♒ ♒ 

$ perl -C -E 'say "\N{U+2630} " x ($_), "\N{U+268A} " x (5-$_), "\n" for 0..5'

⚊ ⚊ ⚊ ⚊ ⚊ 

☰ ⚊ ⚊ ⚊ ⚊ 

☰ ☰ ⚊ ⚊ ⚊ 

☰ ☰ ☰ ⚊ ⚊ 

☰ ☰ ☰ ☰ ⚊ 

☰ ☰ ☰ ☰ ☰ 
```
Note: GitHub replaces \N{U+2652} with an emoticon: ♒

**Comment by neilb** [comment]
@dolmen, yeah, we could show it with five empty squares for the "no CPAN dependents", but for some reason that doesn't feel right. But given it's a meter, maybe it is.

I talked this through with Barbara (garu's wife), and she's going to have a think about ideas for this as well.

**Comment by babsveloso** [comment]
Hey all,
I've been playing with the UI of this component today and have some mockups to share.
Please take a look and send me your feedback:
https://drive.google.com/open?id=0B1FYkYs1yULQb2Rxc1MzdlZqSGs

And let me know if you need any other help :)
B.

**Comment by kentfredric** [comment]
Incidentally, I've been musing over something this month which might be of related interest, but simpler to implement.

1. Simply work out for a given week, what the "Growth" in new dependencies is, and what the "Decline" of certain dependencies are, to give a sort of "dependen-sea-change" metric for a given week/month.

This means you can not only represent where a thing is in the river, but wether its rising in the river, or sinking ( which adds more data to people deciding if they want to use a thing )

The logic I'd imagine is simple:
   
   1. Find all unique dists in `<Period>`
   2. Find `<most recent>` version of each dist in `<Period>` -> `A`
   3. Find "newest version" of each dist outside `<Period>` -> `B`
   4. Delta  `A.merged_prereqs` .. `B.merged_prereqs`
   5. ^ Accumulate adds | removals
   6. Bulk Statistic Found

If somebody gets to this before I get bored enough to staple something together, ++ :)

**Comment by dolmen** [comment]
I really like @babsveloso's proposal.

@kentfredric You should fill this as a separate ticket and add examples.

**Comment by ureesoriano** [comment]
+1 to @babsveloso 's proposal

**Comment by tsibley** [comment]
I'll take on implementing @babsveloso's proposal.

**Comment by tsibley** [comment]
Implemented as PR #2006.

**Comment by oalders** [comment]
I'm closing this as it's now implemented.  \o/  Thanks @babsveloso and everyone else for your work on this!

**Comment by tsibley** [comment]
There was some discussion of this looking too much like a rating, and I have to agree.  Two alternate ideas that are small departures but maybe break that "it's a rating" feeling?

![image](https://user-images.githubusercontent.com/79913/36762671-9eeeeb16-1bd9-11e8-8a75-52b9e8b84dcc.png)
![image](https://user-images.githubusercontent.com/79913/36762677-a9cd5540-1bd9-11e8-851a-21cf03ed8f01.png)

Other approaches might be to make the gauge vertical, more like a thermometer or actual river gauge, but that has less space to work with.

**Comment by karenetheridge** [comment]
My initial inclination is to leave the graphic alone, but change the
alt/mouseover text to "what's this?" or "CPAN river position" and have it
link to a page that explains the concept of the CPAN river (borrowing
heavily from Neil B's blog posts).

**Comment by tsibley** [comment]
@karenetheridge Have you seen the current title text?

**Comment by haarg** [comment]
Even though I know what the river gauge represents, I can't stop my brain from initially reading it as a rating.  If we can find an different visual representation I think that would be much better.

@tsibley The example you posted looks a bit too similar to a signal strength gauge, which is a little distracting.  I wonder if aligning the bars with the top would alleviate that.

**Comment by babsveloso** [comment]
hey guys!

I did some new options based on your feedback. My fav is #2 because IMO the single bar with gradient brings more affordance to the concept of the river – and it being smaller also helps to declutter the UI.

But if these indicators are still confusing, I can try something different. If you can browse [Dribbble](https://dribbble.com/search?q=indicators) for inspiration and show me some options you like, it'd be great.

![River indicator](https://user-images.githubusercontent.com/5322680/36793312-da703d46-1c7b-11e8-845f-9e08c480db62.png)

**Comment by mickeyn** [comment]
I vote for Option 2 as well.

@babsveloso++

**Comment by oalders** [comment]
> Hey all,
I've been playing with the UI of this component today and have some mockups to share.
Please take a look and send me your feedback:
https://drive.google.com/open?id=0B1FYkYs1yULQb2Rxc1MzdlZqSGs

@babsveloso I hope all is well! I notice that your file is now a 404. Is there any chance you still have this available somewhere?

**Comment by babsveloso** [comment]
Hi Olaf,

Here's the new link:
https://drive.google.com/drive/folders/1vlB-hiP5fLtJPLKuDYXl61kJRJVgChw7?usp=sharing

Let me know if you need anything else ;)

**Comment by oalders** [comment]
Hi @babsveloso,

Thanks again for this. I'm also digging around trying to find the design mockups you had put together to improve the UI. I can't seem to be able to find a ticket for it, but I swear it was there and I think we may be able to tackle some redesign soonish, so I wanted another look at what you had come up with.
