### ISSUE TITLE
Remove hardcoded references to https://metacpan.org

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#1681]
```
bash-3.2$ git grep metacpan.org lib
lib/MetaCPAN/Sitemap.pm:        nodes            => ['api.metacpan.org'],
lib/MetaCPAN/Sitemap.pm:            = 'https://metacpan.org/' . $self->cpan_directory . q{/};
lib/MetaCPAN/Web/Controller/Feed.pm:        $e{link}   = "https://metacpan.org/news#$a_name";
lib/MetaCPAN/Web/Controller/Feed.pm:            'https://metacpan.org', 'release',
lib/MetaCPAN/Web/Controller/Feed.pm:    $feed->link('https://metacpan.org/');
lib/MetaCPAN/Web/Controller/Feed.pm:            'https://metacpan.org', 'release',
lib/MetaCPAN/Web/Controller/Feed.pm:            'https://metacpan.org', 'release', $fav->{distribution} );
```

**Comment by ranguard** [comment]
12:40 < ilmari> also, the Release Info link goes to https://v1.metacpan.org/release/HAARG/MooX-TypeTiny-0.001003/, which redirects to https://metacpan.org/release/HAARG/MooX-TypeTiny-0.001003

**Comment by ranguard** [comment]
See https://github.com/CPAN-API/metacpan-web/pull/1705 for the trailing slash redirect fix

**Comment by tsibley** [comment]
This looks mostly cleaned up on master, with a few exceptions:

* Sitemaps are generated with https://metacpan.org
* robots.txt points at sitemaps with https://metacpan.org
* The opensearch.xml refers to https://metacpan.org
* `root/wrapper.html` spits out a `<link rel="canonical">` pointing to https://metacpan.org

**Comment by haarg** [comment]
Pod content is currently being generated with links to https://metacpan.org/.  #1791 should fix that.

**Comment by tsibley** [comment]
I think you mean metacpan/metacpan-api#542.

**Comment by ranguard** [comment]
@tsibley We are ok with those being hard coded - when we go live they will be correct, it was only for the testing.
