### ISSUE TITLE
Data-Random-Tree is absent from metacpan.org

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#1694]
Hi all,

http://search.cpan.org/dist/Data-Random-Tree/ cannot be found on metacpan.org, but it's on CPAN:

* https://metacpan.org/search?q=data%20random%20tree

It used to be there, but disappeared. It also isn't listed on https://metacpan.org/author/PERLANCAR .

Please look into correcting it.

**Comment by p-alik** [comment]
[Gearman](http://search.cpan.org/~palik/Gearman/) package disappeared from metacpan also.-;(

**Comment by mickeyn** [comment]
both are now available on v1.
closing, please open (separate please) an issue if happens again.

**Comment by shlomif** [comment]
Thanks for fixing Data-Random-Tree , @mickeyn ! However Gearman appears to be broken now - see https://github.com/metacpan/metacpan-web/issues/1760 .

**Comment by mickeyn** [comment]
it works on v1: https://v1.metacpan.org/release/Gearman
