### ISSUE TITLE
lib/MetaCPAN/Web/Model/API/Favorite.pm expects an ARRAY ref

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#1699]
[error] Caught exception in MetaCPAN::Web::Controller::Release->view "Can't use string ("gHkUiZ4fS4SrS1UNcn0b6g") as an ARRAY ref while "strict refs" in use at /home/metacpan/metacpan-web/lib/MetaCPAN/Web/Model/API/Favorite.pm line 135."

**Comment by oalders** [comment]
Not sure if this is a current or former problem.  No timestamps in the logs.

**Comment by mickeyn** [comment]
is this still an issue? I guess if we can't recreate it we should close it for now
