### ISSUE TITLE
v1 login fails, browser displays raw JSON 

### ISSUE THREAD

**Issue by kentfredric** [metacpan/metacpan-web#1710]
1. https://v1.metacpan.org/
2. See not signed in
3. Click drop down
4. Click "github"
5. Watch browser spin for a bit
6. Page lands at https://api.metacpan.org/user 
7. Page does show my personal details confirming auth happened somewhere
8. Manually go to v1.metacpan.org
9. Still not signed in.

**Comment by oalders** [comment]
I believe we'll need to set up a Github app just for v1, since I don't think it allows you to have more than one callback url.

**Comment by mickeyn** [comment]
@oalders this is still happening to me on different browsers even after cookie cleanup

**Comment by tsibley** [comment]
I can't reproduce this in a private browsing window.  There's been a lot of change to v1 since this was reported, so I'm closing it.  Please do re-open if you can reproduce it.
