### ISSUE TITLE
Distribution browser does not show FR.pod

### ISSUE THREAD

**Issue by dolmen** [metacpan/metacpan-web#1741]
This page shows no files in the directory:
https://metacpan.org/source/DOLMEN/Number-Phone-FR-0.0815091/lib/POD2/FR/Number/Phone
But FR.pod is there as shown in the raw browser:
https://api.metacpan.org/source/DOLMEN/Number-Phone-FR-0.0815091/lib/POD2/FR/Number/Phone

As a consequence (or not?), Number::Phone::FR is not shown in French (my web browser sends fr and fr-FR in Accept-Languages) as the previous release: https://metacpan.org/pod/release/DOLMEN/Number-Phone-FR-0.0814210/lib/Number/Phone/FR.pm

**Comment by ranguard** [comment]
This this is now fixed (after v1 release) - please comment if thats not the case and will re-open

**Comment by ranguard** [comment]
(note api has been replaced with fastapi)
