### ISSUE TITLE
v1: Links in POD L<Some::Module> Points Wrongly

### ISSUE THREAD

**Issue by ohoushyar** [metacpan/metacpan-web#1745]
POD Links `L<Some::Module>` Points to https://metacpan.org...

For example in https://v1.metacpan.org/pod/AnyEvent:
    `An FAQ document is available as L<AnyEvent::FAQ>` -> "https://metacpan.org/pod/distribution/AnyEvent/lib/AnyEvent/FAQ.pod"

**Comment by oalders** [comment]
I think this needs to be fixed in both metacpan-api as well as metacpan-web.  The API should be set up to receive a hostname parameter which it can use to generate the Pod.  metacpan-web, in turn, should provide the appropriate hostname when making the API calls for Pod generation.
