### ISSUE TITLE
Content-Type not properly set when viewing raw

### ISSUE THREAD

**Issue by perlancar** [metacpan/metacpan-web#1748]
I uploaded a test distribution that contains images. The raw link to one of the images:

https://api.metacpan.org/source/PERLANCAR/Acme-PERLANCAR-Test-Images-0.001/share/images/bakmi.jpg

This shows up as garbage in browser instead of the image. The `Content-Type` HTTP response header is set to `text/plain`, but the `X-Content-Type` is set to `image/jpeg`. I don't know whether this is intentional or is a bug.

**Comment by haarg** [comment]
This is metacpan/metacpan-api#272, which I don't feel has been fully resolved.

**Comment by haarg** [comment]
Fixed (on fastapi).
