### ISSUE TITLE
App::Env disappeared, App::Env::Login not listed; both erroneously marked as BACKPAN

### ISSUE THREAD

**Issue by djerius** [metacpan/metacpan-web#1749]
Howdy,

App::Env has disappeared from search and author (djerius)  listings on metacpan. It was there at most a couple of days ago.  Strangely, one can find the latest version (uploaded 2016-07-13) here

https://metacpan.org/release/DJERIUS/App-Env-0.33

but note that  is marked as being on BACKPAN, which it isn't.

App::Env::Login was uploaded yesterday (2016-07-13), and has suffered the same fate.  No appearance on search and author (djerius) listings, but marked as being on BACKPAN (the link in the drop down box is red) here:

https://metacpan.org/release/DJERIUS/App-Env-Login-0.01

Thanks!

Diab

**Comment by mickeyn** [comment]
both look ok on v1

**Comment by djerius** [comment]
Hi,

Any ideas on why this is happening? I've uploaded another distribution recently with no problems.  Should I try bumping the version and trying again?

**Comment by oalders** [comment]
@djerius sorry about that.  The issue was on our end.  Your releases should be fine now.  You may need to force a refresh to see it, though.

**Comment by djerius** [comment]
No Problem!  Your efforts are very much appreciated.
