### ISSUE TITLE
In v1, XML::LibXML is found when searching, but the linked page says it is not found

### ISSUE THREAD

**Issue by harleypig** [metacpan/metacpan-web#1758]
When searching for [XML::LibXML](https://v1.metacpan.org/search?q=XML%3A%3ALibXML&search_type=modules) it is the first module linked.

But when following the [link](https://v1.metacpan.org/pod/distribution/XML-LibXML/LibXML.pod) I get 'Not Found The resource you requested could not be found.'

I checked the [packages file](https://cpan.metacpan.org/modules/02packages.details.txt) and it is listed there.

**Comment by mickeyn** [comment]
fixed
