### ISSUE TITLE
Gearman dist is absent from metacpan.org

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#1760]
Hi all!

w.r.t to https://github.com/metacpan/metacpan-web/issues/1694 it seems that https://metacpan.org/release/Gearman returns a 404 while it is OK on http://search.cpan.org/dist/Gearman/ . Please look into fixing it.

Regards,

@shlomif

**Comment by p-alik** [comment]
@shlomif, thank you for opening the issue. @mickeyn referred in this [note on #1694](https://github.com/metacpan/metacpan-web/issues/1694#issuecomment-240098069) to v1 and Gearman is available there.
Best regards,
@p-alik

**Comment by oalders** [comment]
I've just re-indexed it on metacpan.org so it's on v0 as well as v1 now.  Thanks for reporting.  :)

**Comment by p-alik** [comment]
thanks for fixing @oalders

**Comment by shlomif** [comment]
@oalders : thanks for fixing it, and - you're welcome.
