### ISSUE TITLE
Issue rendering $x and $y variables within codeblocks in POD

### ISSUE THREAD

**Issue by stevieb9** [metacpan/metacpan-web#1763]
I believe there is a bug when specific variables (in my case `$x` and `$y`) are used by themselves in a POD code block (indented four spaces).

These specific variables do not render in browser (they do show up in the source with "view source").

The full details of the issue with a useful piece of feedback can be found on [PerlMonks](http://perlmonks.org/?node_id=1170464).

If you'd prefer I include all of the information here, please let me know. I'll reformat it and edit the issue.

**Comment by jberger** [comment]
Do you have an example?

**Comment by stevieb9** [comment]
The following POD, at [this location](https://metacpan.org/pod/RPi::WiringPi::LCD#send_cmd-command), does not render the `$x` and `$y` parameters in the code block for the `position()` function

    =head2 send_cmd($command)

    Sends any arbitrary command to the LCD. (I've never tested this!).

    Parameters:

        $command

    Mandatory: A command to submit to the LCD.

    =head2 position($x, $y)

    Moves the cursor to the specified position on the LCD display.

    Parameters:

        $x

    Mandatory: Column position. C<0> is the left-most edge.

        $y

    Mandatory: Row position. C<0> is the top row.

**Comment by haarg** [comment]
This is the same issue as #1228.  I'm pretty sure fixing it would require replacing the syntax highlighter, which is something I've wanted to do for a while.
