### ISSUE TITLE
author page loading can be too slow

### ISSUE THREAD

**Issue by mickeyn** [metacpan/metacpan-web#1764]
16:37:30 � mst� 15:11 < xenu> his author page on metacpan choked my browser for a while

We need to speed up the page loading.

suggestions -
1. separate author releases and author ratings to different views (so we don't query both for the same page)
2. add paging

**Comment by oalders** [comment]
How about adding pagination for both releases and ratings if they exceed a given threshold?  In the majority of cases we'll be able to fit everything onto one page without the browser choking.

**Comment by mickeyn** [comment]
yep, that sounds like the way to go

**Comment by haarg** [comment]
Dupe of #1661
