### ISSUE TITLE
HTML-Table page seems to be permanently borked

### ISSUE THREAD

**Issue by andk** [metacpan/metacpan-web#1766]
https://metacpan.org/release/HTML-Table gives me a "please come back later" page. I got the link to it from metacpan itself: https://metacpan.org/author/AJPEACOCK. I get the "please come back later page already for more than a day.

As far as I can see, HTML::Table is AJPEACOCK/HTML-Table-2.08a.tar.gz which contains version "2.08a" but is indexed by PAUSE as having "2.08". This may be completely irrelevant for the issue, I just want to mention it.

**Comment by oalders** [comment]
@andk thanks for reporting. Looks like it's broken on v1 as well.

**Comment by ranguard** [comment]
Now working on v1 - thanks @haarg
