### ISSUE TITLE
Data from CPAN Testers is out of date

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#1769]
It appears that the summary of pass/fail/na data from CPAN Testers stopped updating a little while ago. Older releases are showing lower figures than listed on CPAN Testers (eg. Acme::Bleach shows 444 passes on [MetaCPAN](https://metacpan.org/pod/Acme::Bleach) but 467 as of 2 days ago on [CPAN Testers](http://matrix.cpantesters.org/?dist=Acme-Bleach+1.150)). Newer releases show no test result data at all (eg. CGI 4.32 released on 19th of July has no stats on [MetaCPAN](https://metacpan.org/pod/distribution/CGI/lib/CGI.pod), but 996 passes on [CPAN Testers](http://matrix.cpantesters.org/?dist=CGI+4.32)).

The stats on search.cpan.org appear to be up to date so it does look like this is a problem at the MetaCPAN end rather than with CPAN Testers.

**Comment by haarg** [comment]
This is metacpan/metacpan-web#1630 again, which I've reopened.
