### ISSUE TITLE
/author

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-web#1775]
https://fastapi.metacpan.org/author/ is being requests on most pages in v1.metacpan.org

e.g. https://v1.metacpan.org/recent vs https://metacpan.org/recent

Seems to be from:

https://github.com/metacpan/metacpan-web/blame/master/root/static/js/contributors.js#L83

being included in all js

@haarg can you shed any light on this?

**Comment by haarg** [comment]
Fixed by ddfa0066b5f48e9c7ae0c4ece0c32c915ba6edaa
