### ISSUE TITLE
Selenium::Waiter consumes exceptions

### ISSUE THREAD

**Issue by ylavoie** [metacpan/metacpan-web#1783]
All exceptions within Selenium::Waiter are consumed instead of being returned.
This makes it really hard to extend functionality for one cannot react properly on failures.
This be configurable and defaulted to current behaviour.

**Comment by oalders** [comment]
Hi @ylavoie,

You'll need to raise this issue at https://github.com/gempesaw/Selenium-Remote-Driver/issues  We (unfortunately) can't help with `Selenium::Waiter`.
