### ISSUE TITLE
New page: Most favorited modules

### ISSUE THREAD

**Issue by chankeypathak** [metacpan/metacpan-web#1787]
Feature: Add a new page on top navigation bar, near to "Recent" which would show most favorited modules sorted by "favorite" count.

**Comment by mickeyn** [comment]
are you looking for this: https://metacpan.org/favorite/leaderboard ?

**Comment by chankeypathak** [comment]
Oops, it already exists.

**Comment by chankeypathak** [comment]
How about adding the leaderboard link to top nav bar?

**Comment by mickeyn** [comment]
if it was popular enough to justify it... I don't think it is

**Comment by oalders** [comment]
I'd be fine with adding it to the nav bar.  Seems like a useful thing to know about.

**Comment by chankeypathak** [comment]
I think the same. Otherwise "leaderboard" is not visible as it has not been linked to any other page, best option would be to put it on homepage or in navbar.
