### ISSUE TITLE
Raw source link now giving "wrong" content type

### ISSUE THREAD

**Issue by shadowcat-mst** [metacpan/metacpan-web#1807]
So, on e.g. https://metacpan.org/pod/release/PREACTION/CPAN-Testers-Schema-0.002/lib/CPAN/Testers/Schema/Result/Stats.pm the 'raw' part of 'source (raw)' now links to st.aticpan.org, which provides a content type based on the file, which while it might be useful in some situations mostly means that firefox wants to download the file rather than let me read it, which means that I can't use this link to browse source code anymore, which is one of the most common things I do with metacpan (it also, similarly, makes the 'browse (raw)' basically useless to me, since I can't click into a file).

Note that if you click just the 'source' link the 'raw code' link on that page goes to fastapi, which forces the content type to text/plain still, and therefore works fine for me.

I can live with 'click source, then click raw code' as a workaround for the moment (since my original workaround was going to be 'go back to s.c.o' which, ew) but it'd be really nice if we could make the main 'raw' link useful again.

**Comment by ranguard** [comment]
Anything with content type of `/x-script.perl/ || /text\/x-pod/` is now converted to `text/plain` on st.aticpan.org

**Comment by shadowcat-mst** [comment]
https://st.aticpan.org/source/MONS/Devel-Hexdump-0.02/

https://st.aticpan.org/source/MONS/Devel-Hexdump-0.02/Hexdump.xs
https://st.aticpan.org/source/MONS/Devel-Hexdump-0.02/ppport.h

Not sure whether "keep whitelisting file extensions" is going to be the right approach here?

**Comment by haarg** [comment]
At least all text/x-* types could be converted to text/plain.

**Comment by ranguard** [comment]
```
19:07 < ranguard> mst: content-type =~ /x-script/ || =~ 'text/x-' are now set to content-type text/plain on st.aticpan.org - please play
19:13 < mst> ranguard++
19:13 < mst> that now works perfectly
```
