### ISSUE TITLE
Carousel for showing sponsors

### ISSUE THREAD

**Issue by chankeypathak** [metacpan/metacpan-web#1829]
As per the pull request [1821](https://github.com/metacpan/metacpan-web/pull/1821), homepage now shows sponsors. 

I find it a bit ugly. In order to keep the homepage clean I suggest a carousel.

For example: https://jsfiddle.net/chankeypathak/6wkkf3hz/

Above example is not perfect, I might need logos of perfect size and some other data but the idea is to use a carousel and put it in footer. This way the site stays clean and sponsors are also happy.

I'm ready to work on it if you guys approve this.

**Comment by oalders** [comment]
The issue here is that the sponsors have essentially paid to be on the front page and I think the best way to handle this is to give everyone equal time with static links.

Having said this, most of the sponsors will be removed at the beginning of 2017, so this is mostly a temporary thing.
