### ISSUE TITLE
Broken link for Net::LDAP::Server::Test

### ISSUE THREAD

**Issue by mans0954** [metacpan/metacpan-web#1832]
Search MetaCPAN for Net::LDAP::Server::Test

https://metacpan.org/search?q=Net::LDAP::Server::Test

At the bottom of the first entry, there is a link named Net-LDAP-Server-Test-0.21, which points to

https://metacpan.org/release/Net-LDAP-Server-Test

However, following this link gives a 404.

The equivalent link for other modules, e.g. https://metacpan.org/release/Net-LDAP-Server for Net::LDAP::Server work.

Thanks.

**Comment by mans0954** [comment]
The module is listed in https://cpan.metacpan.org/modules/02packages.details.txt

**Comment by mans0954** [comment]
Also Net::LDAP::Server:Test is missing from the list at https://metacpan.org/author/KARMAN

**Comment by oalders** [comment]
This looks to be fixed now.
