### ISSUE TITLE
POD is rendered wrongly on https://metacpan.org/pod/Test::Code::TidyAll

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#1841]
On https://metacpan.org/pod/Test::Code::TidyAll , the POD contains `C<<mode => 'test'>>` which is getting rendered strangely (possibly due to the mishandling of double angle brackets).

**Comment by haarg** [comment]
This is a pod error.  When using multiple angle brackets in formatting codes, the content must be surrounded by whitespace.

**Comment by shlomif** [comment]
Thanks @haarg ! I'll send a pull-req to Code::TidyAll correcting it.
