### ISSUE TITLE
please revisit whether the line spacing of the TOC should be that big

### ISSUE THREAD

**Issue by wchristian** [metacpan/metacpan-web#1866]
Right now the line-spacing for the TOC is pretty big.
![image](https://cloud.githubusercontent.com/assets/175467/24831804/940b76e8-1ca1-11e7-9141-06d25e7185c7.png)

This seems like it would be helpful in separating items, but it does not do that:
![image](https://cloud.githubusercontent.com/assets/175467/24831803/843e5096-1ca1-11e7-83f0-329ab391f604.png)

The spacing should definitely be changed to not happen between lines, but between items.

Additionally it might be a decent idea to reduce it overall.

**Comment by haarg** [comment]
Fixed in 7f6319ef55356a38535c4c7aee0b4c7c63e140ea, reducing the space between wrapped lines.
