### ISSUE TITLE
no distribution page for Expect

### ISSUE THREAD

**Issue by chorny** [metacpan/metacpan-web#1888]
https://metacpan.org/release/Expect shows 404.
There is a link to https://metacpan.org/release/Expect from https://metacpan.org/search?q=expect
Expect is indexed:
```
Expect                             1.35  J/JA/JACOBY/Expect-1.35.tar.gz
```
JACOBY page also does not have Expect: https://metacpan.org/author/JACOBY

**Comment by faraco** [comment]
@chorny Hi, I found both https://metacpan.org/release/Expect and https://metacpan.org/author/JACOBY are the contrary of what you stated. The distribution page perfectly shows the distro files, and the author page shows it has 'Expect' in his **release** section.

**Comment by chorny** [comment]
Yes, everything works now.
