### ISSUE TITLE
Links on module names in code excerpts in grep results are broken

### ISSUE THREAD

**Issue by simbabque** [metacpan/metacpan-web#1919]
When searching on grep.metacpan.org the code excerpts in the results have module names (like `require Foo::Bar`) converted to metacpan links. Those links point to https://grep.metacpan.org/pod/Foo::Bar, which of course doesn't exist, so it leads to a 404 page. It should be https://metacpan.org/pod/Foo::Bar.

Here is an example:

Search: https://grep.metacpan.org/search?size=20&q=DBIC_TRACE_PROFILE&qd=&qft=
Broken link: https://grep.metacpan.org/pod/DBIx::Class::Storage::Debug::PrettyPrint
![screenshot](https://user-images.githubusercontent.com/1125067/27173578-776af5f2-51b9-11e7-9c2a-e6bc8a2c3db3.png)

This is because the link is relative. When I inspect the page, it shows:

    <a href="/pod/DBIx::Class::Storage::Debug::PrettyPrint">DBIx::Class::Storage::Debug::PrettyPrint</a>

Steps to reproduce:
---

- Go to https://grep.metacpan.org
- Search for `DBIC_TRACE_PROFILE`
- Scroll down to the result in `DBIx-Class`
- Click the link on `require DBIx::Class::Storage::Debug::PrettyPrint`

Suggested solution:
---

I see two possible solutions:
- Make the links in this view absolute.
- Make https://grep.metacpan.org/pod an alias of https://metacpan.org/pod.

**Comment by atoomic** [comment]
I can clearly see always using the absolute https://metacpan.org/ in the js highlighter,
you mainly want to go to the doc page, no reasons to jump to another search once you are browsing the content of a perl file.
