### ISSUE TITLE
Chrome thinkgs search results are in Vietnamese if I search "dbi ldap"

### ISSUE THREAD

**Issue by simbabque** [metacpan/metacpan-web#1928]
I was searching for the team "dbi ldap" (https://metacpan.org/search?q=dbi+ldap) in Chrome Version 59.0.3071.86 (Official Build) (64-bit). To my confusion there was a Google Translate icon displayed and it asked me if I wanted to auto-translate the page because it's in Vietnamese. My Ubuntu is set to US English and I'm in Germany.

![search dbi ldap](https://user-images.githubusercontent.com/1125067/27432974-d466d304-5752-11e7-9f06-61424ae109bd.png)

I tried to search for "dbi" (https://metacpan.org/search?q=dbi) only and "ldap" (https://metacpan.org/search?q=ldap) only. Both don't display this behavior.
 
![search dbi](https://user-images.githubusercontent.com/1125067/27433002-f5812b02-5752-11e7-90dd-ce1f6ae5997a.png)

![search ldap](https://user-images.githubusercontent.com/1125067/27433006-fd4e9248-5752-11e7-8f67-f6cb3f7139ac.png)

From a cursory glance it doesn't look like there is anything in the search results with Vietnamese text. There is no language meta data in the HTML or in the HTTP response headers.

**Comment by mickeyn** [comment]
FWIW, I don't see that behavior on my machine, using chrome Version 59.0.3071.104 (Official Build) (64-bit)

Maybe it does makes sense to have either:
```
<meta name="google" content="notranslate" />
```
or setting the `Content-Language`.

see [google's guide](https://support.google.com/webmasters/answer/79812?hl=en) or [this stackoverflow answer](https://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer)

**Comment by simbabque** [comment]
While the `notranslate` sounds good, I think that might also be bad for non-English speaking people that use their Chrome to translate documentation on CPAN. I'm thinking mostly Asian developers. So maybe setting the language is a better idea.

**Comment by oalders** [comment]
@simbabque do you have a proposal for which pages should get this header?  There is some translated pod, so that might not be correct for every page.

**Comment by simbabque** [comment]
Sorry I'm a bit late to the party. I've revisited this and can't reproduce it myself any more. Maybe it was a temporary glitch. I think it's definitely not high up in the priority list. Maybe we should just forget about it.

**Comment by oalders** [comment]
Thanks @simbabque. We can close it for now and re-open it later if we need to.
