### ISSUE TITLE
UTF-8 in Module name bug

### ISSUE THREAD

**Issue by simcop2387** [metacpan/metacpan-web#1953]
There's a double encoding/decoding bug happening it looks like

Doesn't work: https://metacpan.org/module/Acme::%E0%B2%A0_%E0%B2%A0 doesn't work
works: https://metacpan.org/module/Acme::%C3%A0%C2%B2%C2%A0_%C3%A0%C2%B2%C2%A0

the module is Acme::ಠ_ಠ

**Comment by haarg** [comment]
It's not exactly a double encoding bug, but a lack of re-encoding on output in the redirect used.
