### ISSUE TITLE
Recent CPAN uploads feed should remove empty content:encoded tags

### ISSUE THREAD

**Issue by y** [metacpan/metacpan-web#1954]
The feed at https://metacpan.org/feed/recent includes a ```content:encoded``` tag for every item. This confuses some feed readers which give this field a higher priority than the description tag. So when the feed is displayed, it doesn't display a description. Actually it probably is displaying it as a single space, since that's what's in the tag. The similar feed at http://search.cpan.org/uploads.rdf displays the description properly because it doesn't include this tag.

Reference: http://www.rssboard.org/rss-profile#namespace-elements-content-encoded

**Comment by grr** [comment]
This has been reported as a bug against XML::Feed here: https://rt.cpan.org/Public/Bug/Display.html?id=124346

**Comment by grr** [comment]
XML::Feed doesn't appear to be actively maintained, so it's unlikely that bug will be addressed in a timely manner. An alternative solution that can be implemented immediately would be to delete the entry's content field in build_entry() in MetaCPAN/Web/Controller/Feed.pm like `delete $e->{content}`. Another solution would be to switch the feed format from RSS to Atom.

**Comment by y** [comment]
Any chance the feed can be fixed before search.cpan.org is retired?

**Comment by haarg** [comment]
It's on my list.

**Comment by haarg** [comment]
This has been fixed.
