### ISSUE TITLE
The number of issues on this distribution is wrong.

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#1955]
(I have read the guidelines and do not believe this is a feature request.)

On this distribution:

https://metacpan.org/pod/Convert::Moji

two issues are listed as being open. However, these issues were closed several months ago:

https://github.com/benkasminbullock/Convert-Moji/issues?q=is%3Aissue+is%3Aclosed

![convert-moji-issues-number-issue](https://user-images.githubusercontent.com/102005/28807372-179fb65a-76b0-11e7-96b8-882d37dae9bc.png)

**Comment by mickeyn** [comment]
@benkasminbullock thanks for reporting.

I think I see why this is happening, will try to solve this later on today/morrow.

**Comment by mickeyn** [comment]
OK, this is now fixed by running the script manually.
I don't see any code changes that are required ATM, but please do report if you see this happening again.
thanks.
