### ISSUE TITLE
Link to pumpkin.pod is broken

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#1958]
Hi all,

in [these search results](https://metacpan.org/search?q=perl+Porting+pumpkin) the first hit is reported as a broken link - https://metacpan.org/pod/distribution/perl/Porting/pumpkin.pod . The web archive indicates that it existed: http://web.archive.org/web/*/https://metacpan.org/pod/distribution/perl/Porting/pumpkin.pod .

Please look into fixing it.

**Comment by mickeyn** [comment]
fixed

**Comment by shlomif** [comment]
On Wed, 09 Aug 2017 17:29:01 +0000 (UTC)
Mickey <notifications@github.com> wrote:

> fixed
> 

Thanks!
