### ISSUE TITLE
404 on "perl"

### ISSUE THREAD

**Issue by plicease** [metacpan/metacpan-web#1960]
This URL:

https://metacpan.org/release/perl

gives me a 404 error.  There is a link to this obscure distribution from this page:

https://metacpan.org/pod/strict

and the widget that lets me select old versions of Perl from that page doesn't seem to be working either.

**Comment by mickeyn** [comment]
This is now fixed.

The problem is not specific to "perl", it has to do with cache purging upon indexing.
we'll sort that out.

**Comment by jscook** [comment]
I noticed this with 'ack' today and I imagine it is related.
