### ISSUE TITLE
Distribution invisible for some reason

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#1963]
[I have read the text and do not believe this is a feature request.]

From "/recent", the link as follows:

https://metacpan.org/release/WWW-CheckGzip

is going to a "Not found" page.

Similar for the search page using the module title:

https://metacpan.org/pod/distribution/WWW-CheckGzip/lib/WWW/CheckGzip.pod

This link works:

https://metacpan.org/release/BKB/WWW-CheckGzip-0.03

It looks like the module is not indexed at all, because all of the dropdown links on the above page are grey. However, the first upload was about 48 hours ago.

**Comment by mickeyn** [comment]
fixed. had to do with a caching issue we are currently dealing with.
