### ISSUE TITLE
Incorrect user count for faved ("-1 non-PAUSE users")

### ISSUE THREAD

**Issue by OpossumPetya** [metacpan/metacpan-web#1964]
If you access [UUID::Random](https://metacpan.org/pod/UUID::Random) page, in the right panel, above author's image there's ++ count, and it says: 

    ++ed by:
    2 PAUSE users
    -1 non-PAUSE users

![image](https://user-images.githubusercontent.com/575197/29496404-aa714a78-85da-11e7-80b5-48428811a8dd.png)

This affects total faved count for the module:

![image](https://user-images.githubusercontent.com/575197/29496461-e7362806-85db-11e7-9ba4-6542599d4653.png)

**Comment by haarg** [comment]
I've fixed this particular case, but there is a general problem of disconnecting from PAUSE being incomplete.
