### ISSUE TITLE
Testers matrix to module

### ISSUE THREAD

**Issue by philiprbrenan** [metacpan/metacpan-web#1968]
On page: http://matrix.cpantesters.org/?dist=Math-Disarrange-List%2020170828

(a) Clicking on: by Slaven Rezić produces "problems loading page"

(b) Please consider making the title at the top of the page clickable to the corresponding  version of the module as this would allow me to send this page to people to demonstrate the module quality (first) and then the actual module content (second).

Thanks!

**Comment by oalders** [comment]
Thanks @philiprbrenan.  It looks like this issue should be opened on https://github.com/eserte/cpan-testers-matrix so that @eserte can look into it.  :)
