### ISSUE TITLE
Dependency discrepancy

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#1970]
I have noticed a discrepancy today for my recently uploaded dist [Net::EPP::Registry::Nominet 0.03_01](https://metacpan.org/pod/release/HOUSTON/Net-EPP-Registry-Nominet-0.03_01/lib/Net/EPP/Registry/Nominet.pm). In the right panel under "Dependencies" it correctly lists Carp and Net::EPP, but in the pop-up from the link "Dependency graph" no dependencies are shown.

This appears to be a regression since the [previous release](https://metacpan.org/pod/release/HOUSTON/Net-EPP-Registry-Nominet-0.03/lib/Net/EPP/Registry/Nominet.pm) of the dist does have the correct results shown in the "Dependency graph" pop-up.

Is this a bug or have I done something really daft with the meta data?

**Comment by haarg** [comment]
For now, we're removing the dependency graph.  It is provided by Stratopan, but that service seems to be unmaintained at this point.  The TLS cert has been expired for months.  See #2106.

As for the cause of the discrepancy, that's something on Stratopan's side.
