### ISSUE TITLE
Missing result count / distributions' counts in authors' pages

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#1975]
Seems like the result count is now completely missing on authors pages such as https://metacpan.org/author/BOOK which renders this issue report outdated - https://github.com/metacpan/metacpan-web/issues/1507 . I personally really liked the distributions count and think it should be restored and may likely work on that. What is the consensus for that? Also note the demise of perlresume - https://github.com/vti/perlresume.org/issues/15 .

**Comment by oalders** [comment]
I don't think this was intentional.  @mickeyn maybe a side effect of your changes?

**Comment by shlomif** [comment]
@oalders @mickeyn : please see this branch - https://github.com/shlomif/metacpan-web/tree/fix-issue-1975-missing-result-count .

**Comment by shlomif** [comment]
Can I get my change reviewed please? Should I file a pull-req?

**Comment by oalders** [comment]
@shlomif a pull request would be the best way to get this reviewed. :)

**Comment by shlomif** [comment]
@oalders : see https://github.com/metacpan/metacpan-web/pull/1982 - thanks.

**Comment by shlomif** [comment]
On Tue, 14 Nov 2017 14:13:42 +0000 (UTC)
Olaf Alders <notifications@github.com> wrote:

> @shlomif a pull request would be the best way to get this reviewed. :)
> 

Will do it, then. Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Chuck Norris is ninety out of Jay-Z's 99 problems.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by oalders** [comment]
Closed via #1982
