### ISSUE TITLE
No distributions depending on $module could be found

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-web#1979]
Currently clicking on "Reverse dependencies" produces an empty list, apparently everywhere. At least this should return something: https://metacpan.org/requires/distribution/Mojolicious?sort=[[2,1]]&size=100

**Comment by mickeyn** [comment]
@haarg I see the parameters (sort) to 'request' are stringified instead of being properly encoded.
any idea what may have caused this?
I will try to investigate further later on this week.

**Comment by haarg** [comment]
The sort parameter needs to support more than just a string.  It includes both the field, and the direction.  It doesn't seem like the back end will accept something like that.

**Comment by mickeyn** [comment]
OK, I can hack this into a POST request passing the sort parameter as JSON body.
Requires changes to both WEB (simple) and API (hackish).
For now this will work, until we figure out a better way to handle it on the API side.

**Comment by mickeyn** [comment]
@haarg , please look at:
https://github.com/metacpan/metacpan-web/pull/1981
https://github.com/metacpan/metacpan-api/pull/746

If you're OK with this solution - let's merge

**Comment by mickeyn** [comment]
@eserte this is now fixed. can you please confirm&close?

**Comment by eserte** [comment]
Looks good now.
