### ISSUE TITLE
When searching for a module, I see some blue ++ tags without number in them

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-web#2003]
like this:

![screenshot-2017-11-22 search for dbix class - metacpan org](https://user-images.githubusercontent.com/423822/33151951-e4001254-cfe2-11e7-8a21-df97a158813a.png)

**Comment by akarelas** [comment]
I believe the blue tags are the ones I have plus-plus-ed already. The only bug then is that the numbers are missing.

**Comment by akarelas** [comment]
In fact, I also see absolutely no numbers on any of the ++ tags in the search results. So I can't tell immediately which module is popular.

**Comment by perlpunk** [comment]
same for me

**Comment by ranguard** [comment]
@mickeyn I see this too... even for a non-logged in user... did something change with calling the API for that info? - or is that unrelated?

**Comment by haarg** [comment]
Fixed in metacpan/metacpan-api@c287ed4ab907dcd24af2997584f7a07bf5ecaace
