### ISSUE TITLE
Two versions of the same distribution in some authors' pages

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#2009]
This page - https://metacpan.org/author/SHLOMIF - contains two versions of "Digest-JHash" and "Math-GMP" but only the latest should be displayed. Keywords: duplicate, dups, duplicates, twice.

**Comment by mickeyn** [comment]
The 2 releases were left with `status='latest'`, I believe this to be a glitch.
In any case, this was corrected - please refresh your page.

**Comment by shlomif** [comment]
@mickeyn : looks good - thanks for the fix!
