### ISSUE TITLE
Allow sorting by "river stage" on the search results page

### ISSUE THREAD

**Issue by book** [metacpan/metacpan-web#2010]
At first I was thinking about the author page, which already allows different sorting order by clicking on the headers (except river stage, for now).

But it fact, it would also be useful to sort search results by the showing the most used modules first.

**Comment by haarg** [comment]
This has been implemented.

**Comment by cxw42** [comment]
Also related to #2054.  @haarg you mentioned that it has been implemented, but I can't find it through the Web interface.  Am I missing something obvious?  (I probably am!)  Thanks!
