### ISSUE TITLE
"latest" link exists for module which only exists on BackPAN

### ISSUE THREAD

**Issue by ikegami** [metacpan/metacpan-web#2013]
From [App-plenv-v1.4.0](https://metacpan.org/release/TOKUHIROM/App-plenv-v1.4.0), clicking on "Latest version" under PERMALINKS results in a 404.

**Comment by mickeyn** [comment]
This distribution has no CPAN releases (only Backpan), 'latest' can only work with releases appearing in 02packages.details, which is not the case here.

@haarg maybe conditionally not show the 'latest' link in such case?

**Comment by ikegami** [comment]
ah! I didn't realize that.

**Comment by mickeyn** [comment]
This seems no longer relevant (no latest link in the mentioned page). Feel free to reopen if needed.
