### ISSUE TITLE
Graphics::Raylib module: The resource you requested could not be found

### ISSUE THREAD

**Issue by a3f** [metacpan/metacpan-web#2014]
v0.009 of Graphics::Raylib has a release page: https://metacpan.org/release/Graphics-Raylib
but no page for the [main module](https://metacpan.org/source/ATHREEF/Graphics-Raylib-0.009/lib/Graphics/Raylib.pm): https://metacpan.org/pod/Graphics::Raylib

> **Not Found**
>
> The resource you requested could not be found.

It used to show up normally. It's contained in the [02packags.details.txt](https://cpan.metacpan.org/modules/02packages.details.txt) and [works on cpan.org](http://search.cpan.org/~athreef/Graphics-Raylib-0.009/lib/Graphics/Raylib.pm): 
```
Graphics::Raylib                  0.009  A/AT/ATHREEF/Graphics-Raylib-0.009.tar.gz
```

**Comment by mickeyn** [comment]
I see it's there now
