### ISSUE TITLE
cpan river dependent counts unreliable?

### ISSUE THREAD

**Issue by wchristian** [metacpan/metacpan-web#2018]
https://metacpan.org/pod/Devel::GlobalPhase seems to have no dependents according to metacpan.
![image](https://user-images.githubusercontent.com/175467/35339510-17407d24-0121-11e8-8e17-41b083587e55.png)

https://metacpan.org/release/Test-Spec however clearly depends on it.
![image](https://user-images.githubusercontent.com/175467/35339555-2e4f4914-0121-11e8-9ff1-0ca19d0e2211.png)

**Comment by neilb** [comment]
It's neilb that's unreliable. The river counts have been updated, so you can see them for the dist you gave.

The MetaCPAN team are working on removing the neilb dependency.

**Comment by oalders** [comment]
I'm going to close this as we're working to bring the Bowersware into the MetaCPAN family.
