### ISSUE TITLE
Buttons in neighbour map have incorrect height

### ISSUE THREAD

**Issue by pioevogel** [metacpan/metacpan-web#2020]
Hi,

the buttons in the neighbourmap have an incorrect height at startup (see https://imgur.com/a/uEZx3). Once a node on the map is doubleclicked they are normal.

I see this behaviour on Mozilla Firefox 58.0 on Kubuntu linux.

**Comment by haarg** [comment]
I believe you are trying to report a bug on [App-Netdisco](https://metacpan.org/release/App-Netdisco).  MetaCPAN is a documentation viewer for all of CPAN.  The proper issue tracker for App-Netdisco is at https://github.com/netdisco/netdisco/issues.

**Comment by pioevogel** [comment]
Sorry, you're right. My bad.
