### ISSUE TITLE
grepping a dist appears to always search the most recent version

### ISSUE THREAD

**Issue by DrHyde** [metacpan/metacpan-web#2022]
Go to the page for an old version of a dist, eg https://metacpan.org/release/CPANEL/cPanel-PublicAPI-2.2. Grep for something, and you end up at eg https://grep.metacpan.org/search?qd=cPanel-PublicAPI&source=metacpan&q=2.2.1.

It appears to have searched the most recent version (which is 2.2.1) as you can see by the hits it finds in the Changes file. Also the "view release on meatcpan" links go to the index page for the most recent version.

**Comment by oalders** [comment]
Sorry, I had missed this.  I think this belongs in https://github.com/metacpan/metacpan-grep-front-end . Ping @atoomic
