### ISSUE TITLE
line-height too narrow

### ISSUE THREAD

**Issue by daxim** [metacpan/metacpan-web#2025]
![](https://user-images.githubusercontent.com/104814/36670788-a34877da-1af9-11e8-84e8-0e7fcd012566.png)

The line-height is so uncomfortably narrow that overhanging padding from monospace text is cutting past descenders and base line of the line above.

**Comment by haarg** [comment]
What operating system and browser are you using?

Can you check the fonts being used for normal and monospace font?  The dev tools in Firefox or Chrome should be able to tell you.

**Comment by daxim** [comment]
Firefox 58.0.2 on Linux

DejaVu Sans and DejaVu Sans Mono

**Comment by daxim** [comment]
> the monospace text should usually have a light grey background

Don't worry about that, that's an image compression artifact.

> Are you overriding the site's CSS in some way?

Yes, I raised the minimum font size in the settings to a level that's comfortable to read for me. Please let me know whether you can reproduce the problem with that.

> computed font-size and line-height

* for `<p>`, font-size = line-height = 14.3px
* for `<code>`, font-size = line-height = 12.8667px

I experimented with the styles in the inspector a bit and found the culprit

    /* a0297a25030379cbbb1fd7b670f9591ac13f455f.css:8796 */
    .content {
        line-height: 20px;
    }

If I change that to 28px or 2em then it looks like in your screenshot.
