### ISSUE TITLE
Can't disconnect any identities

### ISSUE THREAD

**Issue by smith153** [metacpan/metacpan-web#2027]
I apparently have two accounts and am trying to follow the FAQ to merge them. I have one with a single github profile and another with a google and pause profile. Logging into any of them and clicking the 'disconnect' button causes the page to refresh but the identity remains connected. Tried using different browsers, logging out, clearing cookies, etc but to no avail.

**Comment by smith153** [comment]
I managed to get my '/account/identities' to show my google and pause accounts as disconnected by using firefox dev console to craft a delete request to https://fastapi.metacpan.org/v1/user/identity/{pause,google}. Still testing, hopefully haven't really messed something up..

**Comment by smith153** [comment]
I seem to have merged all my profiles into one account. But ++'ing a module still shows its stats as ++'ed by a non-pause user and my pause user favorites list remains blank:  https://metacpan.org/author/ESAYM and my profile favorites /account/favorite/list still doesn't update.

**Comment by smith153** [comment]
Hmm, actually ++'ing seems to work as I'm now listed on a dist's page: https://metacpan.org/release/Time-Piece/plussers but my favorites list in my profile and author page is still not updating.

**Comment by smith153** [comment]
Looks like everything is working now. Guess it just takes time for the favorites to show up. This can be closed unless someone wants to investigate why I had to craft a delete request to https://fastapi.metacpan.org/v1/user/identity/ in order to disconnect profiles...

**Comment by oalders** [comment]
I'm inclined to leave this open as an example of how someone who is really motivated can get this resolved.  :) We really do need to fix this on our end, though.

Thanks for walking us through your process @smith153.

**Comment by balajirama** [comment]
@oalders This is actually very difficult to handle for new users. Can you please help resolve it? I am unable to resolve it by following @smith153 process. 😞

**Comment by smith153** [comment]
I can't remember exactly how I did it, but it was some thing along the lines of: I logged in with the main account that I wanted to keep, then opened the dev console on firefox and went to the 'network' tab. From there I disconnected the other account and watched the request that was made through the dev console. Can't remember what exactly the request was, but I examined it by clicking on the request in the console, then click the 'headers' tab followed by clicking 'Edit and Resend'. I then changed the url to 'https://fastapi.metacpan.org/v1/user/identity/google' and the method to 'DELETE'. Then I hit the send button. Not sure about what I did after that... But that might have been it.

**Comment by oalders** [comment]
@balajirama it looks like there's a problem with our outgoing mail.  We're going to try switching to Fastmail from Mailgun for this.  Hopefully that will solve the problem.  I'm off sick today but I'll try to get this going once I feel better.

**Comment by balajirama** [comment]
@oalders are you feeling better? Did you get a chance to look at this? I continue to get CPAN test reports, but MetaCPAN cannot send me an email to confirm my PAUSE id and connect to it.

As a result, I'm unable to change anything at all about my profile. Please help with this.

**Comment by oalders** [comment]
@balajirama I'll take a look at this today.

**Comment by oalders** [comment]
The mail configuration is mostly set up now, but I probably won't be able to test it until Tuesday.

**Comment by balajirama** [comment]
@oalders did you get a chance to test the mail configuration and release it? I am still seeing the same issue I described above.

**Comment by oalders** [comment]
@balajirama we're getting close.  I'm hoping this branch solves it: https://github.com/metacpan/metacpan-api/pull/893

**Comment by oalders** [comment]
@balajirama could you try it out now?

**Comment by oalders** [comment]
I can confirm that disconnecting identities is still not working.  Not sure if connecting is working as I can't currently disconnect to test reconnecting. :(

**Comment by oalders** [comment]
I'm wondering if the issue with `DELETE` is here: https://github.com/metacpan/metacpan-web/blob/master/lib/MetaCPAN/Web/Model/API/User.pm#L12-L18

Since no return values are being checked, this may just not be working at all.

**Comment by oalders** [comment]
https://github.com/metacpan/metacpan-web/blob/master/t/controller/account.t#L206-L208 :(

**Comment by balajirama** [comment]
It is still not working... 😞

**Comment by balajirama** [comment]
@oalders any news?

**Comment by oalders** [comment]
I may not get back to this until the Perl Toolchain Summit, so late next week probably.

**Comment by sbakker** [comment]
I'm suffering from the same problem. This all started when trying to "++" some modules and them not showing up on my profile. Tried the route to disconnect identities, but so far, neither GitHub nor PAUSE identities can be disconnected.

**Comment by oalders** [comment]
meta::hack is happening from Dec 5-8.  I will be spending time on fixing this issue then.  It's a priority.
