### ISSUE TITLE
Uncaught TypeError: child_process_1.spawnSync is not a function

### ISSUE THREAD

**Issue by aknaamani** [metacpan/metacpan-web#2028]
I installed Geo::StreetAddress::Canada with Yarn into a Rails 5 application, and am getting this error when trying to parse an address:

```
var geoStreetAddress = require('geo-streetaddress-canada')
geoStreetAddress.parseAddress('PH1-933 W Hastings Street')

Uncaught TypeError: child_process_1.spawnSync is not a function
```

Any suggestions on how to implement this in a Rails app? Thanks!

**Comment by oalders** [comment]
Sorry, this repo is for issues with the front end of the MetaCPAN module search.  We can't really help with debugging third party applications.  You may need to do a little more digging to find the right place to open this issue.  Good luck on your search.  I'm sorry we couldn't help.

**Comment by aknaamani** [comment]
Cool. Appreciate the response!
