### ISSUE TITLE
Where did DBD-ODBC Go?

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-web#2029]
Did something happen to DBD-ODBC? The [release URL](https://metacpan.org/release/DBD-ODBC)  is a 404 now, but [search.cpan.org still has it](http://search.cpan.org/dist/DBD-ODBC/).

**Comment by mickeyn** [comment]
it's not 404 now, could have been a temporary issue.

**Comment by haarg** [comment]
DBD::ODBC was deindexed on PAUSE due to the deletion of 1.57.  It looks like it got properly reindexed on PAUSE now.
