### ISSUE TITLE
CPAN Testers link broken

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2030]
On each page where dependencies are listed is a link to deps.cpantesters.org with text "CPAN Testers List". Unfortunately this link uses https but deps.cpantesters.org does not respond to this. eg. compare [this https link](https://deps.cpantesters.org/?module=CGI) with [this http link](http://deps.cpantesters.org/?module=CGI) to see the response.

Now, that's arguably a flaw with deps.cpantesters.org but until that responds to https should this link not just refer to the non-https equivalent (just like the link to matrix.cpantesters.org in the left-hand nav)?

**Comment by haarg** [comment]
Should be fixed.
