### ISSUE TITLE
CAPTCHA: "V1 SHUTDOWN ON 2018-03-31" warning 

### ISSUE THREAD

**Issue by chrstphrchvz** [metacpan/metacpan-web#2031]
The CAPTCHA displayed on the [Verify Account page](https://metacpan.org/account/turing) is not a Turing test but rather a warning, "V1 SHUTDOWN ON 2018-03-31" (which is also text the user is expected to type), and a link for directing site owners to.

Screenshot:
![captchav1](https://user-images.githubusercontent.com/7941193/37944658-19a981fe-3142-11e8-9149-8870c9a75f2b.PNG)

That link for site owners (https://g.co/recaptcha/upgrade) warns:
> **Any calls to the v1 API will not work after March 31, 2018.**

~~So as of reporting this, there's probably only a few days left until users won't be able to verify their accounts.~~ **Edit:** as of 2018-04-07, on other sites still using the v1 CAPTCHA that I've tried, typing the warning string is still accepted.

**Comment by haarg** [comment]
Fixed.
