### ISSUE TITLE
Hardening web interface to keep working somewhat when the origin server goes down

### ISSUE THREAD

**Issue by 2shortplanks** [metacpan/metacpan-web#2034]
When the origin server goes down Fastly should keep serving cached content for a period of time.

This is [documented extensively](https://docs.fastly.com/guides/performance-tuning/serving-stale-content) on Fastly's website.

I think you need a header like `Surrogate-Control: stale-if-error=86400` (but I haven't tried this so I'm not sure)

**Comment by haarg** [comment]
All of the cacheable resources generally already get cached at Fastly for 1 year.  Adding `stale-if-error` wouldn't really add any value on top of that.

**Comment by 2shortplanks** [comment]
I'm not sure that's true.  For example, while the origin was down I tried accessing both https://metacpan.org/news and https://metacpan.org/pod/Params::ValidationCompiler and both were timing out.  I think these are (by looking at the Cache-Control headers) being cached for an hour.

I'm assuming that these are not considered "cacheable resources".

What I'm suggesting in this ticket is that it's okay to serve the stale (expired) version of these pages if the origin is down.

**Comment by haarg** [comment]
The `Cache-Control` headers control how long browsers should cache for.  The `Surrogate-Control` headers aren't passed through to browsers.  The current `Surrogate-Control` headers for `/pod/Params::ValidationCompiler` are `max-age=31556952, stale-if-error=2592000`.  So we are already using this header.
