### ISSUE TITLE
Automatic links from code samples don't make sense

### ISSUE THREAD

**Issue by willsheppard** [metacpan/metacpan-web#2035]
In the code sample below (that can be found [here](https://metacpan.org/pod/Moose::Manual::Roles#Required-Methods-Provided-by-Attributes)), all the package/module/class/role names have been turned into links by metacpan, but the links to example class names "Breakable" and "Car" are broken because those classes don't exist on cpan.

I would assert that **_code samples_** should not be modified in this way to add potentially broken links. POD already has facility for adding links (outside of code samples), which are already rendered by metacpan seperately.

```
package Breakable;

use Moose::Role;

requires 'stress';

########

package Car;

use Moose;

has 'stress' => (
    is  => 'ro',
    isa => 'Int',
);

with 'Breakable';
```

**Comment by haarg** [comment]
There are numerous other examples where the extra links are to real modules.  The extra links don't really hurt anything, so I'm inclined to just leave them be.

**Comment by willsheppard** [comment]
If you ignore the users experience of clicking on a link, and seeing an error message "The resource you requested could not be found", and not necessarily understanding why... Then yes! In that case you are absolutely right, they don't hurt anything.

**Comment by willsheppard** [comment]
Also "leaving them be" is misleading. If you let the POD be, there are no links within example code. Someone has specifically written logic to *add extra links* to the POD when rendered in a web page. Sometimes this may be useful, but in the case of code samples, there is definitely a high risk of broken links, and therefore a poor user experience.

**Comment by oalders** [comment]
I get how this is problematic, but I feel like on the whole this is a useful feature to keep in place.

**Comment by oalders** [comment]
I'm going to close this for now. If someone is will to come up with a solution that fixes the broken links without removing the feature, I'm happy to revisit it.
