### ISSUE TITLE
Can't associate with PAUSE

### ISSUE THREAD

**Issue by vinsworldcom** [metacpan/metacpan-web#2048]
I've used Google then changed to GitHub as OAuth to access MetaCPAN.  When I click Disconnect for the Google account it does nothing and still shows the Disconnect button.  I've revoked access from the myaccount.google.com side.

I can still log in with GitHub OAuth, but I can't associate my PAUSE account VINSWORLD.  I never get the email.  I've looked in SPAM and nothing there.  My CPAN account (vinsworld@cpan.org) is set to forward to my "secret" email from CPAN (not the public one) and I do get CPAN emails from RT, when uploading, etc..

**Comment by icklekitten** [comment]
Same.

**Comment by oalders** [comment]
This is a particularly annoying one that nobody has been able to figure out yet.  Is this helpful at all? https://metacpan.org/about/faq#whycantilinkmypauseaccount

**Comment by icklekitten** [comment]
I tried a different browser who has never logged into metacpan or pause or github but it not send email when I try to link accounts.

**Comment by vinsworldcom** [comment]
It seems MetaCPAN is using your public PAUSE email address rather than you "actual" USER_ID@cpan.org address, which you can configure within PAUSE to forward to your public *or private* address.  I have it configured to forward to private and use a throwaway as my public email.  This does not work.  MetaCPAN will always send to the public address.

So, I changed my PAUSE public address to an actual real address I receive mail on and tried again from a brand new browser.  I got the email but when clicking on the link, I get a pages with just:

{}

That's open and close curly brackets - that's it.  And it doesn't associate.  I've been through the FAQ and tried everything, mind you I can't disconnect accounts on MetaCPAN - pressing the button does nothing - they button still shows red disconnect - so I do go the external sites and revoke the permissions, but that does nothing.

I'm thinking I don't really need to log into MetaCPAN - I never logged into search.cpan.org and this is all way too much trouble.

**Comment by oalders** [comment]
> I'm thinking I don't really need to log into MetaCPAN - I never logged into search.cpan.org and this is all way too much trouble.

You really don't need to log in.  If you don't want to click the `++` or update your author profile then you can bypass the login and still get most of what the site has to offer.

Having said that, the issue you raise about us not sending to the configured email address should be easy to fix.  The issue with the empty JSON has been hard to consistently reproduce, which is why it hasn't yet been fixed.

**Comment by vinsworldcom** [comment]
No worries then.  I've forcing myself to use MetaCPAN instead of search.cpan.org since I saw the announcement.  The interface is growing on me and all search.cpan.org functionality is there without my logging in (as you said).  You can close the issue from my perspective - I know a few others have weighed in though.  I'll continue to use without login but may try it down the road to see if the issues are resolved.  In the meantime, thanks for supporting the Perl community and taking over for search.cpan.org.

**Comment by icklekitten** [comment]
I have my kitten@cpan.org address set as the public one. My private one is set to my real address. And CPAN is set to forward mail to my private address.

**Comment by oalders** [comment]
@icklekitten are you able to test this out?

> So, I changed my PAUSE public address to an actual real address I receive mail on and tried again from a brand new browser.

**Comment by icklekitten** [comment]
Changed public address to my real address, same address as mu private address, set kitten@cpan.org to redirect to public address too. Started new profile in firefox so shouldn't have any cookies. Signed into github. Went to metacpan. Signed in using github. Went to profile to connect to pause account. Typed in my pause user name.

Went to check email. There's one from pause saying my data was updated. Nothing from metacpan.

**Comment by icklekitten** [comment]
If we can't figure out how to connect my github account to my pause account on metacpan, is there anybody with the right access to metacpan server who can do mannually for me?

**Comment by guimard** [comment]
Hello,
I've the same problem: even removing all cookies, I can't associate my PAUSE account.

**Comment by guimard** [comment]
Solved for me using another connexion backend (Twitter instead of Github). It seems that changing email on Github has created the problem

**Comment by icklekitten** [comment]
Oh wow. Works with signing in using Google not Github!

**Comment by icklekitten** [comment]
Well, I got the email and clicked the link but still not able to edit profile. :(

**Comment by haarg** [comment]
It appears the service we use to send emails is hard blocked on cpan.org, which prevents linking PAUSE accounts.  I'm still looking for an appropriate solution for this.

**Comment by brtastic** [comment]
Hello, any news? This still isn't working, so is there any other way to link accounts right now?

**Comment by bokutin** [comment]
It is the same problem. I did not receive the mail.

**Comment by omohayui** [comment]
I got the same problem 😢

**Comment by omohayui** [comment]
Today, I received the email and could connect my PAUSE account.
Has already been This solved?

**Comment by oalders** [comment]
@omohayui we deployed some code last week to use FastMail for mail delivery.  If it works for you now, it sounds like it has at least partially been solved.  Could the others in this thread try it now as well?

**Comment by trapd00r** [comment]
Interesting. I click "login with github", looks like nothing happens, but all of a sudden I am logged in as my cpan author for the first time since 2011. :)

**Comment by bokutin** [comment]
Solved! The email came to me and PAUSE was linked. :)
