### ISSUE TITLE
White space lines

### ISSUE THREAD

**Issue by davidhedlund** [metacpan/metacpan-web#2049]
These lines are automatically inserted at the end of Etherpad documents when I edit them:
> ########
> ################
> 
> ########
> ##########################################################

It's actually white spaces but I use square brackets to make them visible for demonstration. Also, this set of lines may be inserted multiple times when I edit Etherpad docuemtents, and this set of lines can be inserted from multiple users that edit the document.

**Comment by oalders** [comment]
I think this is not the right repo for this issue?
