### ISSUE TITLE
Please provide the ability to limit/filter searches and collapse search results

### ISSUE THREAD

**Issue by djerius** [metacpan/metacpan-web#2050]
Hi,

search.cpan.org provides the ability to limit a search to distribution or module names.  This is something I will sorely miss, as metacpan provides a firehose with, as far as I can tell, no means of filtering.  It would be very helpful to provide some mechanism to limit results.

Something else that would be very helpful is to return one result per module or distribution.  Currently multiple matches produces multiple results greatly increasing the amount of content one must scan, which makes it much harder to find things.

Thanks,
Diab

**Comment by djerius** [comment]
I've tried to come up with a live example, but I don't seem to be able to, so perhaps this isn't an issue.

I recollect that a search might return multiple entries for a given module or distribution, sometimes showing up across multiple result pages.  IF this actually does occur, I'd like the results for a module/distribution to be collapsed into a single entry.

**Comment by haarg** [comment]
Closing this as not reproducible.  If you find a real example of an issue related to this, feel free to reopen.
