### ISSUE TITLE
I upload 1.02 version, but 1.01 "lastest"

### ISSUE THREAD

**Issue by Azq2** [metacpan/metacpan-web#2051]
Why? 

"latest 1.01": https://metacpan.org/release/HTML5-DOM
"oldest: 1.02": https://metacpan.org/release/ZHUMARIN/HTML5-DOM-1.02

I think, 1.02 biggest then 1.01...
It's a temporary issue (may be waiting moderation or indexing) or need re-upload new version?

**Comment by oalders** [comment]
Just give it time.  Uploads are indexed immediately, but they aren't marked as "latest" until a cron runs.  :)

**Comment by Azq2** [comment]
Ok, thanks
