### ISSUE TITLE
"Changes" menu item in sidebar does not show file uploaded by co-maintainer

### ISSUE THREAD

**Issue by jnsbyr** [metacpan/metacpan-web#2059]
When browsing versions of a module uploaded by a co-maintainer, clicking on the "Changes" menu shows the youngest file version uploaded by the primary maintainer and not the file version belonging to the shown module version of the co-maintainer.

Example:
- Search for "Device::Firmata": https://metacpan.org/pod/Device::Firmata or https://metacpan.org/release/Device-Firmata (Device-Firmata-0.64) 
- "Changes" menu item points to: https://metacpan.org/changes/distribution/Device-Firmata (Device::Firmata 0.60)

To resolve this issue the "Changes" menu must be changed to point to the directory and module version of the co-maintainer for co-maintainer uploads.

**Comment by jnsbyr** [comment]
As a workaround forcing a browser refresh can resolve this issue. So this might be a cache issue and not a path issue at its core.

**Comment by haarg** [comment]
Fixed in c791ecadcab34a45a727b7433894d5f7b0a8f960

**Comment by jnsbyr** [comment]
@haarg, thanks for the quick fix!
