### ISSUE TITLE
MetaCPAN search does not find devel-only distributions

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-web#2062]
search.cpan.org is (soon: was) capable of finding distributions which have only non-stable releases. For example, http://search.cpan.org/search?query=Crypt::secp256k1&mode=all would find http://search.cpan.org/~chohag/Crypt-secp256k1-0.0_02/lib/Crypt/secp256k1.pm
The equivalent MetaCPAN search does find this distribution.

**Comment by ranguard** [comment]
There are several tickets open already relating to this: https://github.com/metacpan/metacpan-web/issues?q=is%3Aopen+is%3Aissue+label%3Agroup%3Adev_trial_release currently no one has a clear solution I believe but I know it's been discussed many many times
