### ISSUE TITLE
Mail::Sendmail incorrect page shown

### ISSUE THREAD

**Issue by szabgab** [metacpan/metacpan-web#2063]
https://metacpan.org/pod/Mail::Sendmail shows it as part of https://metacpan.org/release/Test-Smoke while I think it would be better to show the one in https://metacpan.org/release/Mail-Sendmail

Is it a MetaCPAN issue or one that the authors @neilb or @abeltje need to address?

**Comment by oalders** [comment]
Thanks for this @szabgab. I think the best place to follow this issue is at https://github.com/metacpan/metacpan-api/issues/811
