### ISSUE TITLE
What will happen to the build and installation guide for Perl 5 after search.cpan.org shuts down?

### ISSUE THREAD

**Issue by hakonhagland** [metacpan/metacpan-web#2071]
I have noticed  that search.cpan.org will soon shut down. What will happen to the build and installation guide for Perl 5 ( http://search.cpan.org/~shay/perl-5.26.2/INSTALL )  at that time?

Currently it is linking to a raw POD text file: https://metacpan.org/source/SHAY/perl-5.26.2/INSTALL at metacpan.org.

But I think this is much more difficult to read than the HTML formatted code at search.cpan.org.
Is there any hope of getting back the nice HTML formatting at metacpan.org?

**Comment by haarg** [comment]
Where is it linking to the raw pod file?

**Comment by hakonhagland** [comment]
@haarg If you click on the MetaCPAN.org link in the pink box at the top of the page, you will be redirected to the raw pod file. Here is a screenshot:

![selection_001](https://user-images.githubusercontent.com/6708379/40955299-824bb3fc-6889-11e8-861f-cbe9b515b7d6.png)

**Comment by haarg** [comment]
Fixed.
