### ISSUE TITLE
My module ANDK/CPAN-Testers-ParseReport-0.4.4.tar.bz2 missing on metacpan

### ISSUE THREAD

**Issue by andk** [metacpan/metacpan-web#2074]
It has been brought to my attention in https://rt.cpan.org/Ticket/Display.html?id=125518

I find the correct line in 02packages.details.txt:

CPAN::Testers::ParseReport       v0.4.4  A/AN/ANDK/CPAN-Testers-ParseReport-0.4.4.tar.bz2

It is there since May 09, 2018. The fact that search.cpan.org also has an issue with it indicates that there is some common source for this disappearance but I have no idea what this could be.

**Comment by oalders** [comment]
One weird thing is that the `permissions` aren't being found by the front end, even though I can see the module in `06perms.txt`.  See https://metacpan.org/permission/distribution/CPAN-Testers-ParseReport

**Comment by oalders** [comment]
But, this endpoint works https://metacpan.org/permission/module/CPAN::Testers::ParseReport

**Comment by mickeyn** [comment]
I figured out the problem, will submit a patch.
once merged, we can reindex the release and it will work.

**Comment by mickeyn** [comment]
This is now fixed (I reindexed the release and now it's marked as 'latest').
