### ISSUE TITLE
xml in displayed code

### ISSUE THREAD

**Issue by philiprbrenan** [metacpan/metacpan-web#2075]
Please scroll down one page from:

https://metacpan.org/pod/Data::Edit::Xml#divideDocumentIntoSections($$)

and observe that the xml included in my example is affecting the layout of the html?

**Comment by haarg** [comment]
The Pod for that section is not all indented, so it is interpreted as ending the verbatim section and starting a normal paragraph.  You should indent parts like ```
H1

</section>
",
```
MetaCPAN isn't doing anything wrong here.
