### ISSUE TITLE
Could not connect Facebook profile

### ISSUE THREAD

**Issue by jmaslak** [metacpan/metacpan-web#2076]
After logging in with Facebook and realizing that wasn't my metacpan account that was linked to my PAUSE account, I logged out of metacpan and logged in with my Google ID.  Then I tried linking that to my Facebook account so that the next time I logged in with Facebook, I'd get access to the right account.

I got this error when I clicked the green "Connect" button to connect the profile:

    {
       "error": {
          "message": "Error validating application. Application has been deleted.",
          "type": "OAuthException",
          "code": 101,
          "fbtrace_id": "HE+J/h0VT0j"
       }
    }

I don't know if this is user error or application error, so the error likely could use some work for this particular exception.

**Comment by adamtaylor** [comment]
+1 I saw the same error this morning when trying to link my account to FB.

**Comment by oalders** [comment]
I *think* this actually means that the Facebook app has been deleted.  It would have been set up by one of the core devs who is no longer actively contributing.  I just checked and we don't have Facebook in our private credential log.  The question is, do we want to create a new app or do we want to remove Facebook from the list of supported OAuth methods?

**Comment by oalders** [comment]
If we get enough coverage via the other OAuth options, then my vote is to remove Facebook from the list.

**Comment by oalders** [comment]
Facebook has now been removed.
