### ISSUE TITLE
typo in doc : Widgets::TextMemo , description field

### ISSUE THREAD

**Issue by bzimage-it** [metacpan/metacpan-web#2078]
> DESCRIPTION Curses::Widgets::TextMemo provides simplified OO access to Curses-based single line text fields. Each object maintains its own state information.

shall be "multiple line" instead of "single line" .

**Comment by ranguard** [comment]
Hi ,

Please report this to the author: https://metacpan.org/author/CORLISS

We just host the contents of the  module, we can't change it
