### ISSUE TITLE
Distribution SGMLSpm missing on metacpan

### ISSUE THREAD

**Issue by lexeii** [metacpan/metacpan-web#2080]
search.cpan.org:
  * http://search.cpan.org/~raab/SGMLSpm-1.1/
  * https://www.cpan.org/authors/id/R/RA/RAAB/

metacpan.org:
  * https://metacpan.org/release/SGMLSpm (Not Found)
  * https://cpan.metacpan.org/authors/id/R/RA/RAAB/

**Comment by haarg** [comment]
This is an unauthorized release, so it doesn't appear under the bare release URL.  It is available under  https://metacpan.org/release/RAAB/SGMLSpm-1.1.

For including non-indexed releases in search results and elsewhere, see #1231 and #1777.

**Comment by lexeii** [comment]
[API link](https://fastapi.metacpan.org/v1/release/RAAB/SGMLSpm-1.1) works too, it's enough for me. Thank you.
