### ISSUE TITLE
API: repetitions in "provides"

### ISSUE THREAD

**Issue by lexeii** [metacpan/metacpan-web#2086]
In some distributions, there are repetitions in the "provides" in the JSON returned by the API service. Here are examples among the packages I saw:

  * [AppConfig](https://fastapi.metacpan.org/v1/release/AppConfig) provides AppConfig::State twice;
  * [BerkeleyDB](https://fastapi.metacpan.org/v1/release/BerkeleyDB) provides both BerkeleyDB::Btree and BerkeleyDB::Hash twice;
  * [Bit-Vector](https://fastapi.metacpan.org/v1/release/Bit-Vector) — Bit::Vector × 3;
  * [Business-ISMN](https://fastapi.metacpan.org/v1/release/Business-ISMN) — Business::ISMN × 2;
  * [Date-Calc](https://fastapi.metacpan.org/v1/release/Date-Calc) — Date::Calc × 2;
  * [GD](https://fastapi.metacpan.org/v1/release/GD) — GD::Polygon × 2;
  * [perl-ldap](https://fastapi.metacpan.org/v1/release/perl-ldap) — Net::LDAP::Filter × 2;
  * [Tk](https://fastapi.metacpan.org/v1/release/Tk) — Tk × 5;
  * [Unicode-LineBreak](https://fastapi.metacpan.org/v1/release/Unicode-LineBreak) — Unicode::LineBreak × 2;
  * [XML-SAX](https://fastapi.metacpan.org/v1/release/XML-SAX) — XML::SAX::PurePerl × 7 and XML::SAX::PurePerl::Reader × 3.

It seems that this is not a bug, but it would not hurt to make an improvement.

---
_I'm not a programmer, I only want to compile 3½ hundred of the Perl modules packages for my Linux distro, as well as keep them up to date. For this, I use the API extensively, and I want to make some kind of contribution to express my gratitude. Thank you!_

**Comment by oalders** [comment]
Thanks for this @lexeii! It's an interesting problem.  Let's pick on @neilb and `AppConfig`.

```sh
$ git grep 'package AppConfig::State;'
lib/AppConfig/Getopt.pm:130:package AppConfig::State;
lib/AppConfig/State.pm:39:package AppConfig::State;
```

The line that is causing the duplicate entry is at https://metacpan.org/source/NEILB/AppConfig-1.71/lib/AppConfig/Getopt.pm#L131

I think, what needs to happen here, is that the MetaCPAN API needs to return a unique list of package names, so that this is less confusing.  If we're not returning a list of file names with the package names then having duplicates in provides is probably more confusing than helpful.

**Comment by oalders** [comment]
These distributions will need to be re-indexed before we can close this.

**Comment by oalders** [comment]
@lexeii I've re-indexed all of these modules, so they should be fixed.  There may well be others that are out there that have already been indexed.  It will be fixed for new releases, but we can manually fix past releases on demand.  Thanks for your very detailed report.  👍
