### ISSUE TITLE
Move or remove the floating left menu.

### ISSUE THREAD

**Issue by netbroom** [metacpan/metacpan-web#2089]
It's VERY distracting. Just move it to the right and stop it from floating.  I removed it using Chrome's inspect element and readability is WAY better.

**Comment by oalders** [comment]
Which menu?

**Comment by grr** [comment]
I agree. I'm pretty sure he means this one, since it's on the left and it floats when you scroll:

<img width="1011" alt="screen shot 2018-06-27 at 09 12 58" src="https://user-images.githubusercontent.com/690894/41979792-84cc105a-79ea-11e8-8222-a8b209823398.png">

**Comment by oalders** [comment]
Thanks @grr.

Please see #2090 for some proposed UI changes.

**Comment by netbroom** [comment]
Awesome thanks guys! Those UI changes look great.

**Comment by haarg** [comment]
While we have a new design in mind, within the current design we are not going to remove the sidebar.
