### ISSUE TITLE
Locales.pm missing from meta-cpan

### ISSUE THREAD

**Issue by drmuey** [metacpan/metacpan-web#2092]
https://metacpan.org/release/Locales == Not Found

https://metacpan.org/author/DMUEY == Not listed

https://metacpan.org/search?q=Locales == Not found

https://metacpan.org/release/DMUEY/Locales-0.34 == exists

Per https://metacpan.org/about/missing_modules

- Is it in the index?
   - **Yes**. It wasn’t but I forced a reindex and it is now (as of about an hour ago)
- Is the distribution POD only with no package?
   - **No**
- Please check existing issues
   - couldn’t find any that re-indexing didn't resolve
   - the `no_index` + `provides` issue doesn’t appear applicable
   - the [suggestion that it because `provides` is missing](https://rt.cpan.org/Ticket/Display.html?id=125178&results=fde4af406f4edca4084b8b2c51232218) appears to be a red herring:
      - [`provides` is supposed to be optional](https://metacpan.org/pod/CPAN::Meta::Spec#provides)
      - others without it have all of their modules indexed
      - it was added back to the index by forcing a reindex from PAUSE

Help me metacpan you’re my only hope! 😂 But seriously, thanks for all the work y’all do for us

**Comment by haarg** [comment]
metacpan/metacpan-api#812

**Comment by haarg** [comment]
Looks like indexing timed out for this module.  I've manually indexed it for now.

Possibly related: metacpan/metacpan-api#709

**Comment by drmuey** [comment]
looks resolved, FWiW I created https://github.com/drmuey/p5-Locales/issues/9 for later
