### ISSUE TITLE
method is_connected returns true even though server connection is cut.

### ISSUE THREAD

**Issue by onelogindavidkayal** [metacpan/metacpan-web#2093]
recently, I have been working on a utility utilizing the module, where I query is_connected once a second to ensure that the connection is still present.

I have noticed that when I log into the server and manually cut the connection via the management UI, that the is_connected value still returns a true value.  It should be noted that the connection does not show up in the management UI once this action has been done.

**Comment by haarg** [comment]
This is the issue tracker for the website metacpan.org.  MetaCPAN is just a documentation viewer and search site, and has no direct connection to the particular module you are using.
