### ISSUE TITLE
Old URLs for development packages don't work anymore

### ISSUE THREAD

**Issue by Getty** [metacpan/metacpan-web#2096]
Through the change it is now not possible anymore to have:

search.cpan.org/~author/Dist-Ribution/

for accessing the development versions of a yet not existing module.

Specific example: search.cpan.org/~nerdvana/Spreadsheet-ExcelTableReader/

I am sadly not aware how that page looked like before, but now all of ~author just goes to the active releases.

**Comment by oalders** [comment]
<img width="1470" alt="screen shot 2018-07-03 at 13 14 59" src="https://user-images.githubusercontent.com/96205/42234636-2c906d2c-7ec3-11e8-8c16-8c073639e3d2.png">

**Comment by haarg** [comment]
The example you gave redirects to the development release.  Do you have a real example of a failure?

**Comment by Getty** [comment]
The development release is specific the point, previously you could reach a not yet released module over that way, i mean not that this is a crucial feature now, but if it would be possible to work again it would probably be nice.

**Comment by Getty** [comment]
Wait I just realize, it DOES do what I want, then we have another problem, gimme a sec.

**Comment by Getty** [comment]
Ok the problem is with Google, that bamboozled me into believing that the old URL doesn't work anymore:

![](https://i.imgur.com/SUGczUm.png)

As you see, the link of the old link is now https://metacpan.org/release/Spreadsheet according to google. I have now no idea where he got that from if the URL is actually directing to the development release proper <scratchhead>

**Comment by Getty** [comment]
AAAHHH ok, forget it, it was the MetaCPAN Helper!!! Ha ha! :D that bastard, ok, all good. People should just stop to use MetaCPAN helper now :D
