### ISSUE TITLE
only display "Did you arrive here via search.cpan.org? Find out why." message when user is redirected from SCO

### ISSUE THREAD

**Issue by grr** [metacpan/metacpan-web#2097]
The "Did you arrive here via search.cpan.org? Find out why." message should only displayed to users who are redirected from SCO. This is easy to detect from the request headers. Also, it should set a cookie so it is only displayed a single time. I am currently seeing it on every page view on every page.

**Comment by oalders** [comment]
It wouldn't be hard to change this behaviour, but I'm not sure it's worth the effort.  People who haven't been redirected might also be interested to find out the current state of affairs.  This message is not going to be shown permanently.

If someone wanted to make this a one-time banner that uses, say, `localStorage` to track whether the banner has already been dismissed, I'd accept a patch for that, but I do see some value in this being available to a wider audience.

**Comment by haarg** [comment]
The request headers don't contain anything we can use to detect this.

**Comment by haarg** [comment]
This banner has now been removed.
