### ISSUE TITLE
Make search results more readable

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#2098]
Received via email:

> I've just arrived at https://metacpan.org/search?q=Image-ExifTool
Good info, just what I was seeking, but please could you use black text rather than grey? Some of us whose sight isn't what it used to be have a struggle to read it.

I just compared our results with Google and it does look like our text is lighter.  We could switch from `#999999` to `#6a6a6a` to match what Google has.

**Comment by haarg** [comment]
Where are you getting `#6a6a6a` from?  I'm seeing `#545454` for the text of google search results.

**Comment by oalders** [comment]
I swear that's a copy/paste, but now I'm seeing #545454 as well.

<img width="921" alt="screen shot 2018-07-11 at 11 39 34 am" src="https://user-images.githubusercontent.com/96205/42583548-2b5c1216-84ff-11e8-9590-6c8e2502e46d.png">

**Comment by haarg** [comment]
Fixed in 5e21271f8005d05a42a6df495c0fb2907ad2205c
