### ISSUE TITLE
searching for ACH::Builder returns no results

### ISSUE THREAD

**Issue by wchristian** [metacpan/metacpan-web#2102]
The dist definitely exists: https://metacpan.org/release/SSEVERIN/ACH-Builder-0.23.1

But requests like this fail: https://metacpan.org/pod/ACH::Builder

And this: https://metacpan.org/search?q=ACH::Builder

**Comment by haarg** [comment]
It is not indexed by PAUSE, so it isn't marked as latest on MetaCPAN.

**Comment by wchristian** [comment]
I don't think making something that exists and has history invisible and unfindable because of a bug in the very last release makes sense. The only reason i found the first dist at all is because google had still indexed SCO's indexing of it.

**Comment by haarg** [comment]
This is the same as not showing dev releases in the search results.  There are a number of other issues reported about it.

**Comment by wchristian** [comment]
Duplicate of: #1777

**Comment by oalders** [comment]
It's probably time to move this particular problem up to the top of the priority list.
