### ISSUE TITLE
"Dependency graph" visualization is not working: SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by jorol** [metacpan/metacpan-web#2106]
Error:

```
widgets.stratopan.com verwendet ein ungültiges Sicherheitszertifikat.

Das Zertifikat ist am Samstag, 4. August 2018 01:59 abgelaufen. Die aktuelle Zeit ist Montag, 3. September 2018 13:05.

Fehlercode: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by haarg** [comment]
This is an issue with the stratopan.com that we can't fix ourselves.  @thaljef hopefully has more info.

**Comment by haarg** [comment]
We haven't gotten any response from @thaljef so we're removing this feature for now.  It may be re-added in the future if Stratopan gets fixed.

Removed in d3aba2920935649f109e0edec881bf3e7a409480.
