### ISSUE TITLE
st.aticpan.org: browser display is awkward

### ISSUE THREAD

**Issue by jkeenan** [metacpan/metacpan-web#2109]
Today I had occasion to click on the "Browser (raw)" link of several CPAN distributions.  I noticed several awkward aspects to the web pages I was taken to:

1. The column alignment to display directories and files is awkward (though the degree of awkwardness differs among browsers)>  Please see the attached screen shots.

![chrome st aticpan org](https://user-images.githubusercontent.com/96524/45519538-841ea600-b783-11e8-89c9-968a2fed3884.png)
![firefox st aticpan org](https://user-images.githubusercontent.com/96524/45520043-9699df00-b785-11e8-9e0b-61cd051bf822.png)

Note that:

(a) Too much space is allocated for entries in column "Name".
(b) There is insufficient gutter space between the entries in "Size" and "Type".
(c) The column header for "Type" is centered on the column; it should be flush left to match the rows for that column.
(d) Both the header and rows for "Last Modified" are flush right; they should be flush left (with sufficient gutter between "Type" and "Last Modified".
(e) The results should be checked in multiple browsers.  No matter how I adjust the point size in Firefox, the text in the "Last Modified" column breaks.

2. No matter how far I drill down in the directory tree, the main heading remains:

    ```Index of /```

Thank you very much.

**Comment by haarg** [comment]
This is a default nginx directory listing.

Patches welcome.

**Comment by mickeyn** [comment]
Closing as this is not actionable for us at this point.
As @haarg said, we welcome patches.
