### ISSUE TITLE
MetaCPAN cannot find POD for Ref::Util

### ISSUE THREAD

**Issue by SineSwiper** [metacpan/metacpan-web#2110]
https://metacpan.org/pod/Ref::Util
https://metacpan.org/source/ARC/Ref-Util-0.204/lib/Ref/Util.pm

It can't find the POD or the source code itself.  This is despite the directory listing saying that the file exists here:

https://metacpan.org/source/ARC/Ref-Util-0.204/lib/Ref

**Comment by openstrike** [comment]
Both links work fine for me today. Do you still see the problem, @SineSwiper ?

**Comment by haarg** [comment]
Closing, since this is working now.  Feel free to reopen if it reoccurs.
