### ISSUE TITLE
"How to contribute" even the author doesn't know

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#2111]
On the modules it has a link at the right saying "How to contribute". I click on this for my own module but find an empty page.

https://metacpan.org/contributing-to/BKB/Lingua-JA-Moji-0.52

However, even I, the author, don't know what I was supposed to put in the module to make the above not appear. Could someone write just a hint as to what the problem is?

**Comment by oalders** [comment]
@zakame FYI ^^

**Comment by zakame** [comment]
Hi @oalders @benkasminbullock, thanks for the ping!

I have in mind some update for that page to show a short how-to about adding the Contributing file to the dist, perhaps something like in http://neilb.org/2016/01/17/encouraging-contributions.html.  Would that work for you?

**Comment by oalders** [comment]
@zakame that would be a great start!

**Comment by oalders** [comment]
This is a big improvement.  @neilb any thoughts?

**Comment by neilb** [comment]
Great idea to have placeholder text here!

I like the idea of having the text for authors and getting users to encourage authors.

Given that most distributions don't (currently) have a contributing file, how about changing the tone slightly, to something along the lines of:

    This distribution doesn't include its own guidelines for contributors.

    If you want to contribute, there are some generic guidelines below, but it's always a good idea
    to get in touch with the author, so you don't waste any time working on something that
    the author is perhaps already working on, or has specific ideas on how to do it.

    [generic guidance]

**Comment by zakame** [comment]
Thanks @neilb!  I've adapted your note above:

![image](https://user-images.githubusercontent.com/110625/46255480-0e7b3f80-c4d0-11e8-947f-a5c67a82540e.png)
