### ISSUE TITLE
Perl 5.6.2 is missing from the dropdown list of versions

### ISSUE THREAD

**Issue by DrHyde** [metacpan/metacpan-web#2114]
For hysterical raisins I need to build perl 5.6.2. Urgh.

The dropdown list of versions in the top left at https://metacpan.org/release/perl is missing version 5.6.2, both in the main list and in the section at the bottom for perls that are only on the BackPAN, but 5.6.2 is missing from that list. It does however show up in https://cpan.metacpan.org/authors/id/R/RG/RGARCIA/.

**Comment by haarg** [comment]
The front end is only showing 250 entries in the drop downs.  Some dists (such as perl) have more releases than that.  We should either increase the limit, or provide some other way to get the full list for cases like this.

**Comment by DrHyde** [comment]
It now shows up, although as `v5.6.2` and not `5.006002` like I would have expected.

**Comment by haarg** [comment]
5.6.2 does not include a META file, so the version is taken directly from the file name of the tarball.  Newer versions do include a META file, using numeric version formats like 5.030001.  This is preferred over the version from the file name.  metacpan doesn't attempt to normalize to a consistent version format.

**Comment by DrHyde** [comment]
Fair enough. In that case I'll close the issue.

**Comment by Grinnz** [comment]
You can use version->parse($version) to consistently parse either of these formats, and call ->numeric or ->normal on the result.
