### ISSUE TITLE
In many modules, no number next to some blue ++ in the search results

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-web#2115]
Eg https://metacpan.org/search?q=parallel%3A%3Aforkmanager shows P::FM with a blue ++ but no number.

Blue is correct (I have fav'ed it). Number should show. (username: KARJALA)

**Comment by openstrike** [comment]
There's an oddity with that dist which may be related. When I view https://metacpan.org/pod/Parallel::ForkManager it is missing the initial line above the "Contents" box: the line which is usually Author / Dist River Favs / Module.

**Comment by haarg** [comment]
@openstrike I'm not seeing anything abnormal on that page.  Can you maybe show a screenshot of what you are seeing?

**Comment by openstrike** [comment]
The missing line has now magically reappeared. It was the line highlighted in green here which I swear was absent earlier today.

![metacpan](https://user-images.githubusercontent.com/4331674/46963695-3c4eaf80-d09e-11e8-8cd9-da4749e0c72e.png)
