### ISSUE TITLE
MaxMind older version "provides" is wonky

### ISSUE THREAD

**Issue by barefootcoder** [metacpan/metacpan-web#2117]
So, if one goes, say, to [this version](https://metacpan.org/release/DROLSKY/MaxMind-DB-Common-0.031003) of MaxMind-DB-Common, you can see most of the modules are listed as "unauthorized."  In this particular interface, that's fine.  But when I'm sending an API request like this:
```
{
    "query" : { "terms" : { "name" : [
        "MaxMind-DB-Common-0.031003"
    ] } },
    "fields" : [ "distribution","provides" ],
    "size"   : 1
}
```
the fact that I'm not seeing those modules under "provides" is really mucking me up.  That exact version is what I want, in order to recreate known-working-good versions of all my modules.  But, if my system can't tell that that version provides those modules, then the installation client (in this case, that's `cpm`, but I'm pretty sure it doesn't really matter) won't use my preferred version and instead goes out looking to CPAN.

I'm not entirely sure _why_ those modules are unauthorized, but I'm not sure I care.  I would happily accept any of the following solutions:
* Someone somehow makes those modules de-unauthorized, so then they show up in that API request.
* Someone figures out a way to make those modules show up in that API request even _though_ they remain unauthorized.
* Someone suggests an alternative to that API request that will return the unauthorized modules as well.

I'm not sure I'm really bright enough for any of those someones to be me, but I'm happy to go digging through code, if anyone can tell me which is the most desirable alternative and maybe point me in the right direction. :-)

Thx for any help you can provide!

**Comment by oalders** [comment]
The first issue is that this release was by DROLSKY, but that dist (now) only has release permissions for MAXMIND.  It was likely authorized at the time it was uploaded, but we've re-indexed since then and don't use historical data to fix permissions.  See https://metacpan.org/permission/distribution/MaxMind-DB-Common

**Comment by barefootcoder** [comment]
> The first issue is ...

Sure.  But you see my dilemma, right?  As the installer is walking the dependency tree, it sees it needs one of these modules.  My `cpanfile.snapshot` is telling it to use this particular version, but the snapshot file also doesn't say that this particular version provides the module it wants, so it just ignores that and goes on out to CPAN, thus ending up with the wrong version.  Not sure how I can resolve this problem other than just blatantly hardcoding an exception for MaxMind (and one other module I have a failure on, but I'm not sure if that's the same issue as this one yet).

**Comment by oalders** [comment]
You're not wrong and there is actually some historical data to be had, but the biggest problem is finding someone to do the work.  That's where we are perpetually in short supply.

**Comment by oalders** [comment]
Closing, as I don't see a bug here.  We can revisit this if someone wants to tackle historical data.

**Comment by mickeyn** [comment]
release is now reindexed with 'authorized' forced.

**Comment by barefootcoder** [comment]
> release is now reindexed with 'authorized' forced.

Thx.  I can confirm that this works for me; I can now get rid of half my hardcoded workarounds! :-D

> ... there is actually some historical data to be had, but the biggest problem is finding someone to do the work. That's where we are perpetually in short supply.

Could you just briefly outline what you think that work would involve?  That would give anyone considering such an endeavor an idea of what they would be in for. ;->

**Comment by mickeyn** [comment]
For problems of similar nature, I can reindex them. but I'll need the list and some confirmation (not having the historical data) that the release-author is/was authorized at the time of the release to ensure correct data.
