### ISSUE TITLE
Rendering of autodoc.pl in perl distribution is bad

### ISSUE THREAD

**Issue by jkeenan** [metacpan/metacpan-web#2118]
This was originally filed as a bug in the Perl 5 core distribution's issue queue at: https://rt.perl.org/Ticket/Display.html?id=133638.  At issue is this page on metacpan.org: https://metacpan.org/pod/distribution/perl/autodoc.pl

```
The rendering of perlapi on metacpan https://metacpan.org/pod/distribution/perl/autodoc.pl 
appears to be highly confused.

There is a lot of plain code appearing prior to the NAME section. No section appears 
describing the api calls themselves.

thanks
```

```autodoc.pl``` is the program used for automatic generation of certain POD files within the core distribution such as ```pod/perlapi.pod```.  As such it contains what might be described as a custom heredoc that contains POD-formatted text.  This quasi-POD apparently confuses POD renderers.

 ```autodoc.pl```, strictly speaking, has no public documentation.  So perhaps it should not be rendered on metacpan.org.  (It appears not to be rendered at perldoc.perl.org.)

Let's discuss.

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
Metacpan assumes any pod it finds in .pm or .pl is documentation for that file. You can avoid this misclassification with tricks like fatpacker uses: prefix all lines in the heredoc with extra spaces, and remove those spaces afterwards.

**Comment by haarg** [comment]
#1628 related

**Comment by xsawyerx** [comment]
You note that while we can prevent `autodoc.pl` from appearing the documentation list by indenting the POD inside it, still won't prevent the POD from being rendered and I'm confused by it. Is it because it will render the POD even if it's indented?

I think rendering the documentation during the release cycle is achievable, but why do you suggesting copying the `perldelta.pod` to its new location pre-release? What does that address?

I think we should resolve this on the perl side and not MetaCPAN side.

**Comment by Grinnz** [comment]
I think you misinterpreted; indenting the POD will both prevent it from being rendered as POD and showing up as a documentation file. It does not solve the problem of displaying the correct POD for 'perlapi'.

**Comment by Grinnz** [comment]
Copying the perldelta to its new location would mean that https://metacpan.org/pod/perl5280delta would be linkable while it's still the latest stable release of Perl - linking to https://metacpan.org/pod/perldelta is not very useful since it will change in the future.

**Comment by xsawyerx** [comment]
Oh, I see. So we need three different changes:

 * Create documentation for perlapi. We can do that, even if all it explains is what it does and says these are not the documentations you are looking for.
* Indent the POD and then remove it, so it doesn't get detected.

Isn't the whole point of perldelta to reflect the latest - and current - one?

**Comment by Grinnz** [comment]
> Create documentation for perlapi.

This would be best solved by generating perlapi.pod at release time if that's possible.

> Isn't the whole point of perldelta to reflect the latest - and current - one?

Yes, which is useful for 'perldoc perldelta' or looking for what's changed only in the latest release, but not for linking to a specific change in a release of Perl.

**Comment by mauke** [comment]
I think this bug can be closed.
