### ISSUE TITLE
pod2html tool returns "Bad Request"

### ISSUE THREAD

**Issue by tonycoz** [metacpan/metacpan-web#2128]
The pod2html too at https://metacpan.org/pod2html returns "Bad Request" for a variety of (perhaps all) valid POD.

Reproduce steps:

1. visit https://metacpan.org/pod2html
2. Paste valid POD (or select a file)
3. "Bad Request" below the form.

Simple POD I used to test this:

=head1 NAME

perldelta - what is new for perl v5.29.5

=cut

**Comment by oalders** [comment]
Thanks @tonycoz. We will look into this.

**Comment by oalders** [comment]
This has been fixed.  Thanks @tonycoz and @jberger!
