### ISSUE TITLE
spam on metacpan.org?

### ISSUE THREAD

**Issue by GermanS** [metacpan/metacpan-web#2130]
Hello,

If you visit https://metacpan.org/recent
you could see some new packages looks like spam

https://metacpan.org/release/ADAMS/Watch-Robin-Hood-online-full-movie-free-download-uhd
https://metacpan.org/release/ADAMS/Watch-Instant-Family-online-full-movie-free-download-uhd
https://metacpan.org/release/ADAMS/Watch-Venom-online-full-movie-free-download-uhd
...

I'm not sure it's the right place for spam report. I beg your pardon,

**Comment by haarg** [comment]
andk/pause#298

**Comment by oalders** [comment]
@haarg we now have a script to delete SPAM after PAUSE has dealt with it, so I think we can track this here.  Once PAUSE deals with it, we can delete it from the index.

**Comment by andk** [comment]
PAUSE has dealt with him.

**Comment by oalders** [comment]
metacpan@bm-mc-01:~/metacpan-api$ ../bin/metacpan-api-carton-exec bin/metacpan purge --author ADAMS
*** Warning ***: Author ADAMS + all their releases will be removed from the index !!!
Are you sure you want to do this (type "YES" to confirm) ? YES
alright then...
2018/11/27 19:50:51 I purge: Looking all up author ADAMS releases
2018/11/27 19:50:54 I purge: Looking for files of release Watch-Venom-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:54 I purge: Finished purging files for release Watch-Venom-online-full-movie-free-download-uhd
2018/11/27 19:50:54 I purge: Looking for files of release Watch-The-Grinch-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:54 I purge: Finished purging files for release Watch-The-Grinch-online-full-movie-free-download-uhd
2018/11/27 19:50:54 I purge: Looking for files of release Watch-Bohemian-Rhapsody-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:54 I purge: Finished purging files for release Watch-Bohemian-Rhapsody-online-full-movie-free-download-uhd
2018/11/27 19:50:54 I purge: Looking for files of release Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-hd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-hd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Creed-2-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Creed-2-online-full-movie-free-download-uhd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Instant-Family-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Instant-Family-online-full-movie-free-download-uhd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-uhd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Ralph-Breaks-the-Internet-online-full-movie-free-download-hd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Ralph-Breaks-the-Internet-online-full-movie-free-download-hd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Creed-2-online-full-movie-free-download-hd by author ADAMS
2018/11/27 19:50:55 I purge: Finished purging files for release Watch-Creed-2-online-full-movie-free-download-hd
2018/11/27 19:50:55 I purge: Looking for files of release Watch-Robin-Hood-online-full-movie-free-download-uhd by author ADAMS
2018/11/27 19:50:56 I purge: Finished purging files for release Watch-Robin-Hood-online-full-movie-free-download-uhd
2018/11/27 19:50:56 I purge: Moving archive Watch-Venom-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-The-Grinch-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Bohemian-Rhapsody-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-hd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Creed-2-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Instant-Family-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Fantastic-Beasts-The-Crimes-of-Grindelwald-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Ralph-Breaks-the-Internet-online-full-movie-free-download-hd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Creed-2-online-full-movie-free-download-hd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Moving archive Watch-Robin-Hood-online-full-movie-free-download-uhd.zip to /home/metacpan/QUARANTINE
2018/11/27 19:50:56 I purge: Finished purging releases for author ADAMS
2018/11/27 19:50:56 I purge: Looking for favorites author ADAMS
2018/11/27 19:50:56 I purge: Finished purging favorites for author ADAMS
2018/11/27 19:50:56 I purge: Looking all up ratings for author ADAMS
2018/11/27 19:50:56 I purge: Finished purging rating entries related to author ADAMS
2018/11/27 19:50:56 I purge: Purging author ADAMS
2018/11/27 19:50:56 I purge: Finished purging author ADAMS
2018/11/27 19:50:56 I purge: Looking all up author ADAMS contributions
2018/11/27 19:50:56 I purge: Finished purging contribution entries related to ADAMS

**Comment by oalders** [comment]
Thanks @GermanS, @andk and @haarg!  Also thanks to @mickeyn for creating the purge mechanism.  👍
