### ISSUE TITLE
release pages are empty

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-web#2133]
For example https://metacpan.org/release/Moose → Content-Length: 0.

**Comment by eserte** [comment]
Works now again.

**Comment by MartinMcGrath** [comment]
https://metacpan.org/pod/distribution/SOAP-Lite/lib/SOAP/SOM.pod

Returns zero bytes but

https://metacpan.org/source/PHRED/SOAP-Lite-1.27/lib/SOAP/SOM.pod

works. I think there is some underlying issue

**Comment by plambert** [comment]
metacpan.org/recent is very empty as well. Just a few outer tags with no content or visible text.

**Comment by oalders** [comment]
This is empty as well: https://metacpan.org/pod/HTTP::BrowserDetect

My IRC client is messed up right now, so haven't been in the channel today.

**Comment by oalders** [comment]
I purged the cache for these URLs.  I think some of these will be resolved now.

**Comment by ssoriche** [comment]
There were many errors in the API that started with the push of the web front end (because you don't have IRC to see). I restarted the API services again and the errors went away and pages started responding. I've been through the ones that were listed in this issue and they're all responding correctly again.

**Comment by oalders** [comment]
Thanks @ssoriche!  I hope to get back on IRC in the next day or so.

**Comment by eserte** [comment]
A simple workaround to get around the broken cache contents: just add `?something` to the URL --- this will cause a refetch of the resource.

**Comment by mrmuskrat** [comment]
https://metacpan.org/pod/URI::Escape is still empty

**Comment by ssoriche** [comment]
It was empty for me as well, as soon as appended `?` to the URL, it worked.

**Comment by SineSwiper** [comment]
Please just bounce the cache.  Far too many links are broken:

* https://metacpan.org/pod/Carp
* https://metacpan.org/pod/Class::Load
* https://metacpan.org/pod/Devel::OverloadInfo
* https://metacpan.org/pod/Eval::Closure
* https://metacpan.org/pod/Module::Runtime
* https://metacpan.org/pod/File::Spec
* https://metacpan.org/pod/Encode
* https://metacpan.org/pod/File::Basename
* https://metacpan.org/pod/Pod::Man
* https://metacpan.org/pod/Config
* https://metacpan.org/pod/Sub::Name
* https://metacpan.org/pod/Package::Stash
* https://metacpan.org/release/Specio
* https://metacpan.org/release/Plack-Middleware-Debug-RefCounts
* https://metacpan.org/release/DBIx-OnlineDDL
* https://metacpan.org/release/DBIx-BatchChunker
* https://metacpan.org/pod/Email::SendGrid::V3
* https://metacpan.org/pod/DBIx::Connector::Retry

That's just from 5-10 minutes of poking around.

**Comment by oalders** [comment]
I just purged everything from the front end and the api.  FWIW, anyone can purge individual pages: `curl -X PURGE https://www.example.com/image.jpg`

**Comment by MartinMcGrath** [comment]
Thanks for the prompt fix, I've checked a selection of the URLs reported here and can't reproduce the problem.

**Comment by matthewlenz** [comment]
Whatever this issue is it's still occuring.   I used @oalders ' suggestion to gain access to a few pages returning blank results as recent as an hour ago.

**Comment by oalders** [comment]
I think this has been resolved.
