### ISSUE TITLE
README.pod isn't treated as a README file

### ISSUE THREAD

**Issue by jgamble** [metacpan/metacpan-web#2134]
I found that in distribution [C-Blocks](https://metacpan.org/release/C-Blocks) that it has a README.pod file instead of a README, and the file isn't appearing in the display (I found it by browsing the source).

Now it was uploaded in 2016, so perhaps the code to recognize it has been updated since then, but I  haven't found a relevant section if so. I note there was an issue to deal with a CHANGES.pod file (#2043), does there need to be one for README.pod? And if so, where in the code should I be looking?

**Comment by haarg** [comment]
#1482

**Comment by jgamble** [comment]
So the general consensus is Don't Do That?

(I'm okay with that decision if so, but is it now official?)

**Comment by jgamble** [comment]
No further comments, we're approaching two months on this, and the issue does seem to be answered in #1482, so I'm closing this.
