### ISSUE TITLE
You're being rate-limited by Github

### ISSUE THREAD

**Issue by davidcantrelluk2** [metacpan/metacpan-web#2137]
Hover over the "clone repository" or "issues" link for a dist and the popup says "API rate limit exceeded for 79.173.173.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

No doubt you won't be able to replicate this reliably, but hey, at least it tells you what the problem is and how to fix it :-)

**Comment by haarg** [comment]
That isn't a rate limit on us, it's a rate limit on you.  The GitHub calls are done entirely client side.  To improve this we would need to have our own API to retrieve this info where we could use authenticated calls.

**Comment by davidcantrelluk2** [comment]
Ahh, OK. I'll close the ticket then.
