### ISSUE TITLE
Feature request: adding Changes to entry summary in RSS feed.

### ISSUE THREAD

**Issue by gugod** [metacpan/metacpan-web#2142]
Since the latest entry of Changlog of each distribution is parsed out, it might be a good idea to mix that into each entry -- inside which there's only "abstract" now, which is useful, but not giving away the information about what's new.

Since I still favor RSS/Atom feed in the year of 2019, I'd like to spend some time working on this.... will share my progress here.

Update: Here's my WIP:

- (Web) https://github.com/gugod/metacpan-web/tree/latest-changelog-in-feed
- (API) [PR 885](https://github.com/metacpan/metacpan-api/pull/885) Add a new API: /changes/by_releases

I got it almost the way I wanted it, but it is very inefficient (one API query for each feed item), and the change logs is not formatting nice in my RSS reader (tested with Vienna.app) yet.

**Comment by oalders** [comment]
@gugod sounds like a great idea!

**Comment by gugod** [comment]
@oalders thanks for the endorsement ❤️ 

I managed to get the output correct-ish with an inefficient implementation In this WIP branch https://github.com/gugod/metacpan-web/tree/latest-changelog-in-feed 

I will create PR once I figure out how not to add N API queries but just one.... :)

**Comment by mohawk2** [comment]
@gugod Is this now resolved, or are there further changes you'd like to see in the feed?

**Comment by gugod** [comment]
It is up and running for a while and I am happy with the result. 

I was worrying the efficiency of the implementation but maybe it is not too bad afterall.

**Comment by mohawk2** [comment]
PRs to improve efficiency will always be welcome (if evidence is included :-)!
