### ISSUE TITLE
https://metacpan.org/pod/Test::Exception shows an empty page

### ISSUE THREAD

**Issue by ehuelsmann** [metacpan/metacpan-web#2143]
Well, the topic says it all. I'm not sure what's up, because the module does have documentation (and it used to show).

**Comment by oalders** [comment]
I had to purge the Fastly cache.  Seems ok now.  Thanks for reporting @ehuelsmann.

**Comment by ehuelsmann** [comment]
Confirmed. Works for me now as well. @oalders thanks for the quick response!
