### ISSUE TITLE
Some pages corrupted

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-web#2144]
Some pages were not including file names (such as the `Other files` in https://metacpan.org/release/PERLANCAR/Calendar-Dates-ID-Holiday-0.003 ) and others we missing the dist name:

![search_for__data__pageset__-_metacpan_org](https://user-images.githubusercontent.com/60391/52902151-da958200-3204-11e9-847d-834ee440310a.png)

The bit being pointed to was not there previously.

This seems to have been on: bm-mc-02 and lw-mc-02

We found clearing the template toolkit cache `~metacpan/metacpan-web/var/tmp/templates` resolved the issue (remember to also clear Fastly - `purge_fastly.pl --service web --html` - script is in `https://github.com/metacpan/metacpan-conf-private/blob/master/bin/purge_fastly.pl`

**Comment by oalders** [comment]
Thanks @ranguard!
