### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by tobyink** [metacpan/metacpan-web#2147]
CPANCover claims Type-Tiny-1.005_002's coverage is 85.94% but coveralls.io shows 98.77%.

* http://cpancover.com/latest/Type-Tiny-1.005_002/index.html
* https://coveralls.io/builds/21334454

As well as them having different ways of calculating a total coverage, there's the issue that some code paths may only be covered when optional dependencies are installed. It would be nice if authors were able to specify a place where reliable coverage data can be found, and MetaCPAN would show that, instead of always showing CPANCover.

(Of course, it would need to ensure that it was showing the coverage data for the correct version, rather than the current master branch in the repo.)

**Comment by oalders** [comment]
@pjcj thoughts on this?  Does CPANCover install optional deps before running coverage?

**Comment by haarg** [comment]
This is something that has bothered me as well.  For Moo, I'm intending to have it include the extra dependencies and texts [when run under EXTENDED_TESTING](https://github.com/moose/Moo/blob/master/Makefile.PL#L89-L103).  I haven't released that yet to prove the concept.

**Comment by haarg** [comment]
For reference, EXTENTED_TESTING is set [by cpancover's runner script](https://github.com/pjcj/Devel--Cover/blob/master/utils/dc#L40).

**Comment by tobyink** [comment]
I do already have this in my Makefile.PL:

```perl
if ($ENV{EXTENDED_TESTING} and $meta->{version} =~ /_/) {
        $meta->{prereqs}{test}{requires}{'Moose'} = '2.0600';
}
```

I guess I could do this for other optional dependencies. This is only a partial solution though. For example, it doesn't help display coverage information for [Win32::Clipboard](https://metacpan.org/source/JDB/Win32-Clipboard-0.58/Makefile.PL).

**Comment by pjcj** [comment]
Perhaps EXTENDED_TESTING is the correct answer.  But I am also willing to install extra dependencies.

The code which installs modules is found at https://github.com/pjcj/Devel--Cover/blob/master/lib/Devel/Cover/Collection.pm#L153

How should I install the optional dependencies?

I can't remember whether coveralls is running Devel::Cover itself or using your uploaded data.  Either way, last time I looked it only handles statement coverage.  Does coveralls also run your code on Windows and other operating systems?  Cpancover only runs on one linux system, so the coverage information is limited to that.  I have a long-standing plan to allow people to upload coverage from other systems and merge it into a single result, but I have no time to work on that.

**Comment by haarg** [comment]
Coveralls is just an interface for coverage data uploaded from somewhere else, often a service like Travis CI or AppVeyor running Devel::Cover with Devel::Cover::Report::Coveralls.

**Comment by oalders** [comment]
Should this issue be moved to `Devel::Cover`?

**Comment by oalders** [comment]
Since this is not a MetaCPAN issue, it should be opened on the `Devel::Cover` repo.
