### ISSUE TITLE
Changes file isn't rendered on dist frontpage

### ISSUE THREAD

**Issue by trapd00r** [metacpan/metacpan-web#2151]
I see other dists having a really nice changes since last release box on its frontpage, but I can't seem to get one myself no matter what I do. I've checked various other dists where it's working but can't seem to figure out what I'm doing wrong?

https://metacpan.org/release/Term-ExtendedColor

**Comment by haarg** [comment]
That dist is version 0.500, but the Changes file does not include a section for that version.  It only has an entry for 0.499.
