### ISSUE TITLE
Inconsistent handling of spaces in POD links

### ISSUE THREAD

**Issue by Alex-Kent** [metacpan/metacpan-web#2159]
My POD documentation has spaces in the link targets, e.g.:

    =head2 Index( ... )

The links I'm putting in look like this:

    The C<L<Index(...)|/Index(_..._)>> method is really spiffy.

With both `perldoc` and `pod2html` the links are correct.  `perldoc` links to the `#Index(_..._)` anchor while `pod2html` does a bit of rewriting and links instead to the `#Index` anchor.  In both cases the links function properly.  On MetaCPAN, however, the links targets use dashes in place of spaces (e.g. `#Index(-...-)`) and thus the manually added (non-table-of-contents) links are broken.  Changing from `_` to `-` in the manual links breaks the links for `perldoc` and `pod2html`.  You can see an example of this with [Geo::Index](https://metacpan.org/pod/release/AKH/Geo-Index-v0.0.7/lib/Geo/Index.pm).

Is this a bug or am I doing something incorrectly?

**Comment by haarg** [comment]
Your `L<>` links should contain the same text as the headings, including spaces.  Different renderers have different ways of transforming the text into link targets, but if you use the same text in both places then it should always match.

**Comment by Alex-Kent** [comment]
Per your suggestion, using spaces in the link targets works for me for `perldoc` and `pod2html` (haven't tried MetaCPAN yet).  Oddly, that was the link style I originally tried to use.  For reasons now unreproducible it wasn't working correctly.  Thanks!

**Comment by haarg** [comment]
MetaCPAN has a [Pod Renderer Tool](https://metacpan.org/pod2html) you can use for testing if you want.

**Comment by Alex-Kent** [comment]
Good to know.  I'll be using that in future.
