### ISSUE TITLE
All search results either show "SOMETHING MISSING? FIND OUT WHY" page or a list of items that all return Not Found pages

### ISSUE THREAD

**Issue by Bub-la-bub** [metacpan/metacpan-web#2165]
Every module I search for on metacpan.org either returns a "SOMETHING MISSING? FIND OUT WHY" page or a normal-looking page of results.  However if I do actually get a page of results and click on any module listed I get a "Not Found" page.

Try the following:

These all give me the "something missing" page (searching for "dbi" or "cgi"):
https://metacpan.org/search?q=dbi
https://metacpan.org/search?q=cgi

This returns a list of results (searching for "valid"):
https://metacpan.org/search?q=valid

But every item listed in those results returns a not found page, for example the link to Getopt::Valid:
https://metacpan.org/pod/Getopt::Valid

**Comment by PopeFelix** [comment]
I'm having this issue too. Unable to bring up https://metacpan.org/pod/DBIx::Class::Schema or https://metacpan.org/pod/DBIx::Class::Manual::DocMap, for example

**Comment by PhilipSharman** [comment]
Confirming - this happens for me too.

**Comment by PopeFelix** [comment]
I think it's back now. I just tried Getopt::Valid and it worked

**Comment by Bub-la-bub** [comment]
Yay!  - Yep, I'm getting proper results and pages now too.  That was nice and quick.

**Comment by oalders** [comment]
Sorry about that.  Outage happened while all of us were out to dinner.  :(  We'll be checking the logs to try to figure out what went wrong.  Thanks for reporting.
