### ISSUE TITLE
I have problem to disconnect account

### ISSUE THREAD

**Issue by lucas1** [metacpan/metacpan-web#2172]
I'm trying disconnect from twitter and github but not work, see image:
![Captura de tela em 2019-05-05 22-42-08](https://user-images.githubusercontent.com/784699/57203524-40351700-6f87-11e9-9989-2caf573e4bd7.png)

it seems I have 3 accounts, "github and twitter", "google" and "pause". I click in disconnect, after refresh page I see connected again.

Thanks.

**Comment by oalders** [comment]
This is a known issue.  Not sure when we'll get a fix in for it, though.

**Comment by lucas1** [comment]
data of login from (twitter,github,google) this save in ElasticSearch?

**Comment by lucas1** [comment]
https://github.com/metacpan/metacpan-api/blob/master/lib/MetaCPAN/Model/User/Account.pm#L153

after it's removed from ref do not need to be set again?

**Comment by akarelas-pt** [comment]
This bug is making it hard to for me to use Metacpan from $work, since I want to log in to my account using $work's Google account and I can't disconnect the existing google account first. So +1 to have this solved.

**Comment by oalders** [comment]
Can you try this again?  It may have been fixed via #2248.

**Comment by ltmbr** [comment]
Solved thanks :)
