### ISSUE TITLE
No uploads for 23 hours

### ISSUE THREAD

**Issue by rwfranks** [metacpan/metacpan-web#2173]
Uploads, or the reporting thereof, stopped at about 18:15, 5th May.

**Comment by oalders** [comment]
Thanks @rwfranks.  This appears to be an issue on the Perl NOC side of things.  We're aware of it and things should get back to normal once we start getting the mirrored uploads again.

**Comment by perlpunk** [comment]
It can be a good idea to leave such issues open, so that other people who wonder about the same thing don't open another issue.

**Comment by rwfranks** [comment]
All seems to be well again
