### ISSUE TITLE
Dependency graphs replacement

### ISSUE THREAD

**Issue by Grinnz** [metacpan/metacpan-web#2174]
As the link to stratopan graphs has been removed (#2106) I developed https://cpandeps.grinnz.com as a replacement. If desired it could be linked to or embedded as the stratopan graphs were. I am not sure how it will behave in an iframe so I can make changes as needed if that approach is taken. The graph for each distribution can be reached as https://cpandeps.grinnz.com?dist=Dist-Name.

**Comment by oalders** [comment]
closed via #2178
