### ISSUE TITLE
Autolink "github ###" as a GH issue link in Changes

### ISSUE THREAD

**Issue by cxw42** [metacpan/metacpan-web#2175]
Thanks to #907, `GH-###` in a `Changes` file is recognized as an issue link.  I just noticed that @pjcj uses `github ###` in the [`Changes` file for `Devel::Cover`](https://metacpan.org/changes/distribution/Devel-Cover).  Would it be possible to also autolink that format?  It seems to be [here](https://github.com/metacpan/metacpan-web/blob/700748459b3ca2cec64a5c9834943343857dd33b/lib/MetaCPAN/Web/Controller/Release.pm#L269) in `master` as I write this.  Thanks for considering this request!

**Comment by oalders** [comment]
I think that's fine.  Is this an offer???

**Comment by pjcj** [comment]
I can also get with the programme and be a bit more standard.  At PTS I wondered why I was filling up my changes file with the word github, so I'm quite happy to change my changes rather than requiring a change to accommodate my foibles.

**Comment by oalders** [comment]
Also not a bad idea.  👍

**Comment by cxw42** [comment]
@oalders Happy to write the ten-character change :) and additional test, but I don't have bandwidth at the moment to set up a dev environment.  Know that if I send a PR it won't be tested yet ;) .

@pjcj `GH-` is definitely less to type!  I think it's still worth making the change (ha) for the sake of previous `Devel::Cover` releases, and I suspect you're not the only one who uses the full name.

**Comment by oalders** [comment]
@cxw42 setting up the dev env is just cloning the repo and running `cpanm install App::cpm && cpm install --cpanfile cpanfile` on the repo.  You don't need any of the fancy stuff to work on the front end.

**Comment by cxw42** [comment]
@oalders Thanks for the help getting set up!  The only other thing I needed to do was manually install `Carton::Snapshot` (for some reason `cpm` didn't automatically).

PR is now open as #2176.

**Comment by oalders** [comment]
@cxw42 thanks for doing that.  It looks like `Carton` is in Runtime/Recommends for `cpm`: https://metacpan.org/source/SKAJI/App-cpm-0.980/META.json#L44
