### ISSUE TITLE
Metacpan reports "No healthy backends"

### ISSUE THREAD

**Issue by ehuelsmann** [metacpan/metacpan-web#2183]
Hi,

Right now, on any uncached page (try using a search), I'm getting a "no healthy backends" error reported by Varnish.

Thanks for looking into this!

Regards,

Erik.

**Comment by ehuelsmann** [comment]
Ok. it seems to have returned to normal operation.

**Comment by oalders** [comment]
Thanks @ehuelsmann.   Looks like it coincided with this:

> [06:39:45]  <PanoptaOutage>	bm-mc-02 (5.153.225.20)  CPU: Usage percentage - Total greater than 90% for more than 5 minutes at 05:39:03 CDT

**Comment by haarg** [comment]
bm-mc-02 constantly gets CPU and IO spikes because it hosts grep.metacpan.org

**Comment by oalders** [comment]
Should we move that site to a different machine?
