### ISSUE TITLE
POD rendering: C<> interprets section like L<>

### ISSUE THREAD

**Issue by perlancar** [metacpan/metacpan-web#2184]
Example in https://metacpan.org/pod/distribution/App-ProveWithPrereqsOnly/bin/prove-with-prereqs-rs-only

    C<lib/>

is rendered as a hyperlink with text:

    "" in lib

where it should just be a verbatim:

    lib/

**Comment by haarg** [comment]
The pod has `L<lib/>`: https://metacpan.org/release/App-ProveWithPrereqsOnly/source/bin/prove-with-prereqs-rs-only#L43

**Comment by perlancar** [comment]
Sorry for the noise. I haven't released the typo fix, thinking it's already on MetaCPAN.
