### ISSUE TITLE
App-Sqitch: Not Found

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-web#2185]
https://metacpan.org/release/App-Sqitch leads to a 404 page. The page for the current release ( https://metacpan.org/release/DWHEELER/App-Sqitch-v1.0.0 ) is displayed OK, though, but clicking on the "Latest version" link (which leads to the formerly mentioned URL) is not.

**Comment by oalders** [comment]
Thanks @eserte.  It looks like it's there now.  May have been a cache issue.

**Comment by eserte** [comment]
So next time should I try a Shift-Reload, or is there another possibility to circumvent the cache?

**Comment by oalders** [comment]
You can also try `curl -XPURGE https://metacpan.org/release/App-Sqitch `
