### ISSUE TITLE
intltool XML parser missing

### ISSUE THREAD

**Issue by Azaretdodo** [metacpan/metacpan-web#2186]
Hello,

My error when I want to './configure' share mim info :

`checking for perl >= 5.8.1... 5.30.0
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool
`

Thank you in advance to help me repair this issue because I don't find this perl module too I fail to download this perl 5.8.1 too I fail to repair by download XML parser and intltool from debian page web,

Regards.

Dorian ROSSE.

**Comment by oalders** [comment]
This issue should be reported to the correct author.  Let us know if you need help tracking the author down.
