### ISSUE TITLE
Google+ discontinued

### ISSUE THREAD

**Issue by chrstphrchvz** [metacpan/metacpan-web#2187]
https://plus.google.com

Should links to Google+ accounts be removed/no longer able to be added?

**Comment by chrstphrchvz** [comment]
Note, I do not mean removing Google **identities** for login—just the links to Google+ **profiles**

**Comment by oalders** [comment]
Thanks @chrstphrchvz! We should do this.

**Comment by oalders** [comment]
Closed via #2212
