### ISSUE TITLE
Feature request: Support README.md files

### ISSUE THREAD

**Issue by djzort** [metacpan/metacpan-web#2191]
Frequently distributions are shipping README.md files as the only README.x style file.

It would be excellent for MetaCPAN to be able to consider a README.md to be the  "proper" README file and render it as html.

**Comment by oalders** [comment]
I think this makes sense.

**Comment by PatrickCronin** [comment]
I'd like to take a crack at this.

**Comment by oalders** [comment]
Closed via #2214  This should be deployed in an hour or so.
