### ISSUE TITLE
Link to 'latest' is broken for BBB/ttylog-0.85

### ISSUE THREAD

**Issue by mbeijen** [metacpan/metacpan-web#2194]
On this page:

https://metacpan.org/release/BBB/ttylog-0.85

The Permalink to 'Latest version' points to https://metacpan.org/release/ttylog which currently returns a 404.

**Comment by Grinnz** [comment]
I suspect the problems are in part because the distribution has never contained an indexed package.

**Comment by mickeyn** [comment]
The reason is that we don't have a 'latest' for this distribution as it's removed from CPAN (not in 02packages).
This kind of link works on latest per distribution name and there's no match for it.
