### ISSUE TITLE
PGObject::Util::DBAdmin not included in the index 9h after upload

### ISSUE THREAD

**Issue by ehuelsmann** [metacpan/metacpan-web#2197]
Hi, 

on https://github.com/miyagawa/cpanmetadb-perl/issues/8 @migayawa points out that the package is correctly indexed on the response returned over HTTP but not on the response returned over HTTPS (curl -s https://cpan.metacpan.org/modules/02packages.details.txt.gz).

Thanks for looking into this!

Regards,

Erik.

**Comment by Grinnz** [comment]
It may be mirror related, as https://cpanmeta.grinnz.com/packages?module=PGObject%3A%3AUtil%3A%3ADBAdmin&match_mode=exact is sourced from the same URL and was up to date at the time.

**Comment by mickeyn** [comment]
it shows now.
