### ISSUE TITLE
(pass / fail / na) links to https://www.cpantesters.org, but it only works with http://

### ISSUE THREAD

**Issue by choroba** [metacpan/metacpan-web#2202]
In lynx, I'm getting 

    SSL error:host(www.cpantesters.org)!=cert(CN<c.sni.fastly.net>:SAN<DNS=c.sni.fastly.net>)

when clicking on the failure reports from https://metacpan.org/pod/Module::Starter

**Comment by oalders** [comment]
Ping @preaction

**Comment by preaction** [comment]
What version of Lynx? Does it support SNI? Looks like the first released version with some measure of SNI support was `2.8.7pre.2` (2009-04-26). CPAN Testers uses a shared SSL cert donated by Fastly which requires SNI support.

**Comment by choroba** [comment]
`2.8.9dev.16`. But I'm getting `Your connection is not secure` even in Firefox:
> www.cpantesters.org uses an invalid security certificate.
> The certificate is only valid for c.sni.fastly.net
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by oalders** [comment]
Closing this here as it is (was?) an cpantesters/Fastly issue.

**Comment by preaction** [comment]
Sorry, yes, this is now fixed.

**Comment by oalders** [comment]
Thanks @preaction!
