### ISSUE TITLE
Tried to install Win32::Console but don't have dmake or PPM (but have ActivePerl)

### ISSUE THREAD

**Issue by DragonOsman** [metacpan/metacpan-web#2208]
For some reason I don't have PPM.  Is there a way to get it?  I want to install `dmake` so that I don't get an error like this when I try to install Win32::Console:
```
Running make for J/JD/JDB/Win32-Console-0.10.tar.gz
'dmake' is not recognized as an internal or external command,
operable program or batch file.
  JDB/Win32-Console-0.10.tar.gz
  dmake -- NOT OK
Failed during this command:
 JDB/Win32-Console-0.10.tar.gz                : make NO
```
Any help is appreciated.  Thanks in advance.

**Comment by oalders** [comment]
Hi @DragonOsman,

We can't actually help you with this, but you should be able to get help via https://rt.cpan.org/Public/Dist/Display.html?Name=Win32-Console
