### ISSUE TITLE
Use cpan to install PadWalker on windows but end up with undefined references

### ISSUE THREAD

**Issue by AAAAAj** [metacpan/metacpan-web#2209]
cpan PadWalker
Loading internal logger. Log::Log4perl recommende
Reading 'C:\Perl64\cpan\Metadata'                
  Database was generated on Tue, 17 Sep 2019 05:1
Running install for module 'PadWalker'           
CPAN: Digest::SHA loaded ok (v6.01)              
CPAN: Compress::Zlib loaded ok (v2.074)          
Checksum for C:\Perl64\cpan\sources\authors\id\R\RO\ROBIN\PadWalker-2.3.tar.gz ok 
CPAN: Archive::Tar loaded ok (v2.30)             
PadWalker-2.3/                                   
PadWalker-2.3/Changes                            
PadWalker-2.3/MANIFEST                           
PadWalker-2.3/t/                                 
PadWalker-2.3/README                             
PadWalker-2.3/META.yml                           
PadWalker-2.3/PadWalker.xs                       
PadWalker-2.3/Makefile.PL                        
PadWalker-2.3/PadWalker.pm                       
PadWalker-2.3/META.json                          
PadWalker-2.3/t/var_name.t                       
PadWalker-2.3/t/our.t                            
PadWalker-2.3/t/baz.pl                           
PadWalker-2.3/t/recurse.t                        
PadWalker-2.3/t/test.t                           
PadWalker-2.3/t/sub.t                            
PadWalker-2.3/t/vn-inc-2.pl                      
PadWalker-2.3/t/dm.t                             
PadWalker-2.3/t/vn-inc-1.pl                      
PadWalker-2.3/t/bar.pl                           
PadWalker-2.3/t/closure.t                        
PadWalker-2.3/t/foo.t                            
PadWalker-2.3/t/tt.t                            
CPAN: YAML::XS loaded ok (v0.69)
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
CPAN: Module::CoreList loaded ok (v5.20181129_28)
Configuring R/RO/ROBIN/PadWalker-2.3.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for PadWalker
Writing MYMETA.yml and MYMETA.json
  ROBIN/PadWalker-2.3.tar.gz
  C:\Perl64\bin\perl.exe Makefile.PL INSTALLDIRS=site -- OK
Running make for R/RO/ROBIN/PadWalker-2.3.tar.gz
cp PadWalker.pm blib\lib\PadWalker.pm
Running Mkbootstrap for PadWalker ()
"C:\Perl64\bin\perl.exe" -MExtUtils::Command -e chmod -- 644 "PadWalker.bs"
"C:\Perl64\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- PadWalker.bs blib\arch\auto\PadWalker\PadWalker.bs 644
"C:\Perl64\bin\perl.exe" "C:\Perl64\site\lib\ExtUtils\xsubpp"  -typemap C:\Perl64\lib\ExtUtils\typemap  PadWalker.xs > PadWalker.xsc
"C:\Perl64\bin\perl.exe" -MExtUtils::Command -e mv -- PadWalker.xsc PadWalker.c
C:\MinGW\bin\gcc.exe -c         -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2    -DVERSION=\"2.3\"     -DXS_VERSION=\"2.3\"  "-IC:\Perl64\lib\CORE"   PadWalker.c
In file included from PadWalker.xs:3:0:
C:\Perl64\lib\CORE/inline.h: In function 'S_is_utf8_invariant_string_loc':
C:\Perl64\lib\CORE/perl.h:1759:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define PTR2nat(p) (PTRV)(p) /* pointer to integer of PTRSIZE */
C:\Perl64\lib\CORE/inline.h:397:48: note: in expansion of macro 'PTR2nat'
 #  define PERL_IS_SUBWORD_ADDR(x) (1 & (       PTR2nat(x)                     \
                                                ^~~~~~~
C:\Perl64\lib\CORE/inline.h:411:45: note: in expansion of macro 'PERL_IS_SUBWORD_ADDR'
                           + PERL_WORDSIZE * PERL_IS_SUBWORD_ADDR(x)
                                             ^
C:\Perl64\lib\CORE/perl.h:1759:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define PTR2nat(p) (PTRV)(p) /* pointer to integer of PTRSIZE */
                    ^
C:\Perl64\lib\CORE/inline.h:398:46: note: in expansion of macro 'PTR2nat'
                                       |   (  PTR2nat(x) >> 1)                 \
                                              ^~~~~~~
C:\Perl64\lib\CORE/inline.h:411:45: note: in expansion of macro 'PERL_IS_SUBWORD_ADDR'
                           + PERL_WORDSIZE * PERL_IS_SUBWORD_ADDR(x)
                                             ^
C:\Perl64\lib\CORE/perl.h:1759:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define PTR2nat(p) (PTRV)(p) /* pointer to integer of PTRSIZE */
                    ^
C:\Perl64\lib\CORE/inline.h:399:46: note: in expansion of macro 'PTR2nat'
                                       | ( ( (PTR2nat(x)                       \
                                              ^~~~~~~
C:\Perl64\lib\CORE/inline.h:411:45: note: in expansion of macro 'PERL_IS_SUBWORD_ADDR'
                           + PERL_WORDSIZE * PERL_IS_SUBWORD_ADDR(x)
                                             ^
C:\Perl64\lib\CORE/perl.h:1759:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define PTR2nat(p) (PTRV)(p) /* pointer to integer of PTRSIZE */
C:\Perl64\lib\CORE/inline.h:414:30: note: in expansion of macro 'PTR2nat'
                           - (PTR2nat(x) & PERL_WORD_BOUNDARY_MASK))
                              ^
C:\Perl64\lib\CORE/perl.h:1759:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define PTR2nat(p) (PTRV)(p) /* pointer to integer of PTRSIZE */
                    ^
C:\Perl64\lib\CORE/inline.h:419:16: note: in expansion of macro 'PTR2nat'
         while (PTR2nat(x) & PERL_WORD_BOUNDARY_MASK) {
                ^
In file included from C:\Perl64\lib\CORE/perl.h:5251:0,
                 from PadWalker.xs:3:
PadWalker.xs: In function 'XS_PadWalker__upcontext':
PadWalker.xs:641:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     XPUSHs(sv_2mortal(newSViv((IV)upcontext(aTHX_ uplevel, 0, 0, 0, 0))));
                               ^
C:\Perl64\lib\CORE/pp.h:462:55: note: in definition of macro 'XPUSHs'
 #define XPUSHs(s) STMT_START { EXTEND(sp,1); *++sp = (s); } STMT_END
                                                       ^
PadWalker.xs:641:12: note: in expansion of macro 'sv_2mortal'
     XPUSHs(sv_2mortal(newSViv((IV)upcontext(aTHX_ uplevel, 0, 0, 0, 0))));
            ^
PadWalker.xs:641:23: note: in expansion of macro 'newSViv'
     XPUSHs(sv_2mortal(newSViv((IV)upcontext(aTHX_ uplevel, 0, 0, 0, 0))));
"C:\Perl64\bin\perl.exe" -MExtUtils::Mksymlists \
     -e "Mksymlists('NAME'=>\"PadWalker\", 'DLBASE' => 'PadWalker', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' => {  }, 'DL_VARS' => []);"
C:\MinGW\bin\g++.exe PadWalker.def -o blib\arch\auto\PadWalker\PadWalker.dll -mdll -s -static-libgcc -static-libstdc++ -L"C:\Perl64\lib\CORE" -L"C:\MinGW\x86_64-w64-mingw32\lib" PadWalker.o
  "C:\Perl64\lib\CORE\libperl528.a" -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -Wl,--enable-auto-image-base
PadWalker.o:PadWalker.c:(.text+0x131): undefined reference to `_imp__Perl_hv_common_key_len'
PadWalker.o:PadWalker.c:(.text+0x1ec): undefined reference to `_imp__Perl_sv_reftype'
PadWalker.o:PadWalker.c:(.text+0x22d): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x242): undefined reference to `_imp__Perl_mg_get'
PadWalker.o:PadWalker.c:(.text+0x271): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0x282): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x29f): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x5bc): undefined reference to `_imp__Perl_sv_2iv_flags'
PadWalker.o:PadWalker.c:(.text+0x5e9): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0x62e): undefined reference to `_imp__Perl_newSViv'
PadWalker.o:PadWalker.c:(.text+0x63b): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0x66b): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0x6bd): undefined reference to `_imp__Perl_safesysmalloc'
PadWalker.o:PadWalker.c:(.text+0x70f): undefined reference to `_imp__Perl_die_nocontext'
PadWalker.o:PadWalker.c:(.text+0x728): undefined reference to `_imp__Perl_get_sv'
PadWalker.o:PadWalker.c:(.text+0x733): undefined reference to `_imp__Perl_safesysfree'
PadWalker.o:PadWalker.c:(.text+0x755): undefined reference to `_imp__Perl_get_av'
PadWalker.o:PadWalker.c:(.text+0x775): undefined reference to `_imp__Perl_get_hv'
PadWalker.o:PadWalker.c:(.text+0x837): undefined reference to `_imp__Perl_hv_common_key_len'
PadWalker.o:PadWalker.c:(.text+0x891): undefined reference to `_imp__Perl_hv_common_key_len'
PadWalker.o:PadWalker.c:(.text+0x8ed): undefined reference to `_imp__Perl_newRV'
PadWalker.o:PadWalker.c:(.text+0x932): undefined reference to `_imp__Perl_hv_common_key_len'
PadWalker.o:PadWalker.c:(.text+0x9ef): undefined reference to `_imp__Perl_die_nocontext'
PadWalker.o:PadWalker.c:(.text+0xa36): undefined reference to `_imp__Perl_newSV_type'
PadWalker.o:PadWalker.c:(.text+0xa8c): undefined reference to `_imp__Perl_sv_2cv'
PadWalker.o:PadWalker.c:(.text+0xb07): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0xb1d): undefined reference to `_imp__Perl_newRV_noinc'
PadWalker.o:PadWalker.c:(.text+0xb2a): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0xb49): undefined reference to `_imp__Perl_mg_get'
PadWalker.o:PadWalker.c:(.text+0xb5f): undefined reference to `_imp__Perl_sv_free2'
PadWalker.o:PadWalker.c:(.text+0xb81): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0xb96): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0xba3): undefined reference to `_imp__Perl_die_nocontext'
PadWalker.o:PadWalker.c:(.text+0xc40): undefined reference to `_imp__Perl_die_nocontext'
PadWalker.o:PadWalker.c:(.text+0xc4d): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0xd82): undefined reference to `_imp__Perl_die'
PadWalker.o:PadWalker.c:(.text+0xe6d): undefined reference to `_imp__Perl_sv_2iv_flags'
PadWalker.o:PadWalker.c:(.text+0xe79): undefined reference to `_imp__Perl_newSV_type'
PadWalker.o:PadWalker.c:(.text+0xeec): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0xefe): undefined reference to `_imp__Perl_newRV_noinc'
PadWalker.o:PadWalker.c:(.text+0xf0b): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0xf3d): undefined reference to `_imp__Perl_sv_free2'
PadWalker.o:PadWalker.c:(.text+0xf57): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0xfbd): undefined reference to `_imp__Perl_sv_2iv_flags'
PadWalker.o:PadWalker.c:(.text+0xfc9): undefined reference to `_imp__Perl_newSV_type'
PadWalker.o:PadWalker.c:(.text+0x103c): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0x104e): undefined reference to `_imp__Perl_newRV_noinc'
PadWalker.o:PadWalker.c:(.text+0x105b): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0x108d): undefined reference to `_imp__Perl_sv_free2'
PadWalker.o:PadWalker.c:(.text+0x10a4): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0x1169): undefined reference to `_imp__Perl_newRV'
PadWalker.o:PadWalker.c:(.text+0x119e): undefined reference to `_imp__Perl_hv_common_key_len'
PadWalker.o:PadWalker.c:(.text+0x11c8): undefined reference to `_imp__Perl_newSViv'
PadWalker.o:PadWalker.c:(.text+0x11db): undefined reference to `_imp__Perl_newRV'
PadWalker.o:PadWalker.c:(.text+0x1220): undefined reference to `_imp__Perl_hv_common'
PadWalker.o:PadWalker.c:(.text+0x1267): undefined reference to `_imp__Perl_sv_free2'
PadWalker.o:PadWalker.c:(.text+0x12c5): undefined reference to `_imp__Perl_newSV_type'
PadWalker.o:PadWalker.c:(.text+0x1303): undefined reference to `_imp__Perl_sv_2cv'
PadWalker.o:PadWalker.c:(.text+0x135c): undefined reference to `_imp__Perl_newRV_noinc'
PadWalker.o:PadWalker.c:(.text+0x1369): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0x13d4): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0x13dc): undefined reference to `_imp__Perl_newRV_noinc'
PadWalker.o:PadWalker.c:(.text+0x13f5): undefined reference to `_imp__Perl_sv_2mortal'
PadWalker.o:PadWalker.c:(.text+0x143d): undefined reference to `_imp__Perl_mg_get'
PadWalker.o:PadWalker.c:(.text+0x1459): undefined reference to `_imp__Perl_block_gimme'
PadWalker.o:PadWalker.c:(.text+0x148d): undefined reference to `_imp__Perl_stack_grow'
PadWalker.o:PadWalker.c:(.text+0x14b1): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x14c6): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0x15fd): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x1612): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x16cd): undefined reference to `_imp__Perl_sv_setpv'
PadWalker.o:PadWalker.c:(.text+0x16e3): undefined reference to `_imp__Perl_mg_set'
PadWalker.o:PadWalker.c:(.text+0x1712): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x1729): undefined reference to `_imp__Perl_sv_newmortal'
PadWalker.o:PadWalker.c:(.text+0x1751): undefined reference to `_imp__Perl_sv_2iv_flags'
PadWalker.o:PadWalker.c:(.text+0x176b): undefined reference to `_imp__Perl_croak_xs_usage'
PadWalker.o:PadWalker.c:(.text+0x1778): undefined reference to `_imp__Perl_croak_nocontext'
PadWalker.o:PadWalker.c:(.text+0x17af): undefined reference to `_imp__Perl_xs_handshake'
PadWalker.o:PadWalker.c:(.text+0x17b7): undefined reference to `_imp__Perl_newXS_deffile'
PadWalker.o:PadWalker.c:(.text+0x185e): undefined reference to `_imp__Perl_xs_boot_epilog'
collect2.exe: error: ld returned 1 exit status
dmake.exe:  Error code 129, while making 'blib\arch\auto\PadWalker\PadWalker.dll'
  ROBIN/PadWalker-2.3.tar.gz
  C:\Perl64\cpan\build\dmake-0\dmake.exe -- NOT OK

**Comment by Grinnz** [comment]
Please report this to the issue tracker for PadWalker: https://rt.cpan.org/Public/Dist/Display.html?Name=PadWalker
