### ISSUE TITLE
allow Human JSON (Hjson) format in META.json files

### ISSUE THREAD

**Issue by tbrowder** [metacpan/metacpan-web#2211]
# Problem

Requiring incoming modules to have their META.json files in strict JSON format is an unnecessary developer burden.

# Discussion

The JSON format was designed for machine-to-machine exchange and, consequently, disallows such human niceties as comment, bare strings without spaces, trailing commas, etc.

There are several variants of a looser JSON existing such as 'Relaxed JSON' and 'Human JSON' that permit these niceties as well as others.

There is a Perl 6 module, (JSON::Hjson)[https://github.com/akyim/JSON-Hjson), which implements the proposed [Hjson standard](https://hsjon.org/trc.html).

There are several Perl modules implementing Relaxed JSON.

# Recommendation

Use one (or more) relaxed or loosened JSON parsers for testing a module's META.json files for acceptance into CPAN.  Ideally, the files could be accepted in one or more formats as is, but accepting and then transforming them into standard JSON would be an acceptable fall-back solution.

**Comment by Grinnz** [comment]
This would be a toolchain concern, not MetaCPAN. Though MetaCPAN is among the consumers that would have to implement this change, also including PAUSE and all CPAN installers.

**Comment by Grinnz** [comment]
To the proposal, I disagree with the premise. META.json is only to be generated by authoring tools, not humans.

**Comment by tbrowder** [comment]
I'm a Perl 6 module author and the META6.json file is not automatically generated (at least at the moment) unless the author manually uses a tool to produce a template to then manually fill in.

We do have a test class an author can use to ensure his META6.json file is legitimate JSON and includes entries required by Perl 6 installation tools.

But I'll close this issue for now.

Thanks for your consideration.
