### ISSUE TITLE
markdown not rendering?

### ISSUE THREAD

**Issue by djzort** [metacpan/metacpan-web#2217]
From #2191 
This README.md file isn't HTML'd? Perhaps im missing something

See https://metacpan.org/release/JLCOOPER/DBD-Mock-1.50 -> README.md

**Comment by PatrickCronin** [comment]
I checked on this a few hours ago, and confirmed the behavior you reported. However, I just checked again, and it seems to be working on production. Perhaps something was being cached?

**Comment by djzort** [comment]
Shift-refresh seems to have it working. its possible it was my local machine, or perhaps a cache in front of metacpan. 
Closing.
