### ISSUE TITLE
make test fails   during  installation

### ISSUE THREAD

**Issue by pratheesh-new** [metacpan/metacpan-web#2219]
Hi i am trying to install Archive::Rar through capn . But the make test getting failed 
Running make test

PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/00pod.t ............ skipped: Test::Pod 1.00 required for testing POD
t/10basic.t .......... 1/3 # The following test fails if the 'rar' command isn't found.
t/10basic.t .......... ok
t/20list.t ........... 1/53
#   Failed test 'list structure is an array ref'
#   at t/20list.t line 54.
Can't use an undefined value as an ARRAY reference at t/20list.t line 55.
# Looks like your test exited with 255 just after 5.
t/20list.t ........... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 49/53 subtests
t/30extract.t ........ ok
t/40add.t ............ 1/15 Use of uninitialized value $1 in concatenation (.) or string at /appz/home/.cpan/build/Archive-Rar-2.02-s1JB1O/blib/lib/Archive/Rar.pm line 223.

Cannot open /tmp/I_A7jcpsU9//tmp/I_A7jcpsU9/add_test.rar
No such file or directoryUse of uninitialized value $archivename in -f at t/40add.t line 44.

#   Failed test 'List structure is defined and array ref and length 1'
#   at t/40add.t line 61.

#   Failed test at t/40add.t line 67.

#   Failed test at t/40add.t line 67.
# Looks like you failed 3 tests of 15.
t/40add.t ............ Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/15 subtests
        (1 TODO test unexpectedly succeeded)
t/50passt_basic.t .... ok
t/55passt_list.t ..... ok
t/60passt_extract.t .. ok

Test Summary Report
-------------------
t/20list.t         (Wstat: 65280 Tests: 5 Failed: 1)
  Failed test:  5
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 53 tests but ran 5.
t/40add.t          (Wstat: 768 Tests: 15 Failed: 3)
  Failed tests:  13-15
  TODO passed:   7
  Non-zero exit status: 3
Files=8, Tests=98,  5 wallclock secs ( 0.15 usr  0.00 sys +  2.53 cusr  0.36 csys =  3.04 CPU)
Result: FAIL
Failed 2/8 test programs. 4/98 subtests failed.
make: *** [test_dynamic] Error 255
  SMUELLER/Archive-Rar-2.02.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports SMUELLER/Archive-Rar-2.02.tar.gz
Running make install
  make test had returned bad status, won't install without force
Failed during this command:
 SMUELLER/Archive-Rar-2.02.tar.gz             : make_test NO

I dont have an idea about .

**Comment by Grinnz** [comment]
This is the bugtracker for the MetaCPAN site. The bugtracker for the Archive::Rar distribution is listed in its sidebar: https://rt.cpan.org/Public/Dist/Display.html?Name=Archive-Rar. This existing bug report might be related: https://rt.cpan.org/Public/Bug/Display.html?id=114246

**Comment by oalders** [comment]
Thanks @Grinnz!

**Comment by pratheesh-new** [comment]
Thanks @Grinnz  ..
