### ISSUE TITLE
Overwriting HandleError 

### ISSUE THREAD

**Issue by ovadbar** [metacpan/metacpan-web#2220]
I want to use a Class similar to DBIx::Error to handle my Errors but the code overwrites my changes.

I would on change
    `local $sth->{HandleError} = sub { $_[0] = Carp::shortmess($_[0]); 0 };`
to
    `local $sth->{HandleError} ||= sub { $_[0] = Carp::shortmess($_[0]); 0 };`

**Comment by Grinnz** [comment]
This is the issue queue for the MetaCPAN web site. It's unclear what CPAN module this is meant for, but the "Issues" link in the left sidebar on its page will direct you to the appropriate place to report issues.

**Comment by ovadbar** [comment]
Mojo::mysql::Database
