### ISSUE TITLE
Type::Tiny 1.007_007 release info looks weird

### ISSUE THREAD

**Issue by tobyink** [metacpan/metacpan-web#2243]
https://metacpan.org/release/TOBYINK/Type-Tiny-1.007_007

![Screenshot from 2019-12-03 20-05-12](https://user-images.githubusercontent.com/251383/70085546-5b90ff00-1608-11ea-9278-1f4077363f68.png)

Note it has "lib/Type/Tiny/Manual.pod" etc instead of the usual "Type::Tiny::Manual" etc.

**Comment by Grinnz** [comment]
This was probably just an indexing hiccup, it appears correct now

**Comment by oalders** [comment]
Seems to have healed itself?  Thanks @tobyink and @Grinnz!
