### ISSUE TITLE
t/controller/pod.t - Can't call method "warn" on an undefined value at ./app.psgi

### ISSUE THREAD

**Issue by atoomic** [metacpan/metacpan-web#2256]
error from t/controller/pod.t noticed from https://github.com/metacpan/metacpan-web/runs/339026741

```
Can't call method "warn" on an undefined value at ./app.psgi line 45 during global destruction.
212
t/controller/pod.t ....................... 
```

copy: @oalders

**Comment by oalders** [comment]
What's the best way to deal with this during destruction -- just check if $logger is defined or a ref?  The line is: `     $SIG{__WARN__} = sub { $logger->warn(@_) };`

ping @haarg

**Comment by guest20** [comment]
Maybe remove the `$SIG{__WARN__}` in `WarnHandler`'s  `DESTROY` so anything after that just uses regular old `warn`?

**Comment by mohawk2** [comment]
Surely just `$SIG{__WARN__} = sub { $logger ? $logger->warn(@_) : warn @_ };`?
