### ISSUE TITLE
Request: easy access (permalink-style?) from version-independent source file to latest-version source file

### ISSUE THREAD

**Issue by cxw42** [metacpan/metacpan-web#2260]
Related to #1675, but not the same issue; please let me know if I accidentally missed an already-open issue for this.

Scenario: Suppose I am submitting an issue comment related to 

https://metacpan.org/release/DBIx-Class-Fixtures/source/lib/DBIx/Class/Fixtures.pm#L913 .  

I would like to include the version-specific link in my comment, since the line numbers may change in future releases.  Therefore, I would like the link 

https://metacpan.org/source/SKAUFMAN/DBIx-Class-Fixtures-1.001039/lib/DBIx/Class/Fixtures.pm#L913 

I cannot find anything on https://metacpan.org/release/DBIx-Class-Fixtures/source/lib/DBIx/Class/Fixtures.pm#L913 that will give me that version-specific link.  Would it be possible to add such a thing to the "Tools" pane?

Thanks for considering this request!

**Comment by oalders** [comment]
This would be a helpful addition.

**Comment by cxw42** [comment]
@oalders Thanks!  Is this something that can be done entirely on the front end, or does it require back-end changes?  I have worked with the front-end code a bit, but haven't touched the back end.

**Comment by oalders** [comment]
@cxw42 this would be entirely front end work.  You could grep on how the other permalinks are created to get started.  Any help is greatly appreciated. :)

**Comment by dboehmer** [comment]
I often happened to have this exact issue. Now I've just decided to do the right thing and open an issue for it. Thanks for already doing it and (hopefully) for adding this!

**Comment by cxw42** [comment]
@dboehmer If you beat me to the PR, I won't complain ;) .  I'll post here when I take this up; please let me know if you do likewise.

**Comment by dboehmer** [comment]
@cxw42 I've never worked on MetaCPAN code before and won’t try this issue.

Anyway I just had the same need again and checked the status of this issue. I'd very much appreciate your PR! Maybe you find that little bit of extra time thanks to corona :wink:

**Comment by cxw42** [comment]
OK - had a few minutes today to start working on it.  Turns out the `Raw code` link is almost all the way there, so I think it can all be done in `root/source.html`.  It may take longer to add the tests than the code! :D
