### ISSUE TITLE
Distribution not found: eps2png

### ISSUE THREAD

**Issue by sciurius** [metacpan/metacpan-web#2261]
When I perform a metacpan search for eps2png, no results are returned.
When I look at CPAN user JV, eps2png is not among the list of distributions.

eps2png *is*, however, on the JV list of cpantesters.

Did I miss something?

**Comment by oalders** [comment]
Looks like it's there now.  https://metacpan.org/search?size=20&q=eps2png  Let me know if you'd like to re-open this.

**Comment by sciurius** [comment]
I managed to get eps2png in the list by drastically changing the kit contents. `eps2png` is a standalone perl program. I have added a module `App::eps2png` and now it is accepted by MetaCPAN.
However, this is a trick I do not like...
What is the correct way to have a standalone perl program (i.e., no modules) accepted? It used to work with the old CPAN.

**Comment by oalders** [comment]
Unfortunately that's the trick with MetaCPAN.  Only modules will show up in search results.  Other files are not so easily discoverable.  It's a pain point, but one we haven't been able to address yet.
