### ISSUE TITLE
prove -I ../test-nginx/lib -r t/ fails

### ISSUE THREAD

**Issue by lifeblood** [metacpan/metacpan-web#2263]
PATH=/usr/local/openresty/nginx/sbin:$PATH prove -I ../test-nginx/lib -r t/
t/cidr.t .. Can't locate Test/Nginx/Socket.pm in @INC (you may need to install the Test::Nginx::Socket module) (@INC contains: /home/travis/build/lifeblood/lua-resty-ipcidr/../test-nginx/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at t/cidr.t line 1.
BEGIN failed--compilation aborted at t/cidr.t line 1.

**Comment by oalders** [comment]
This issue tracker is for the metacpan.org web site.  Questions about module installations are better handled elsewhere.   I would suggest trying either asking a question on stackoverflow.com or in #perl on freenode IRC.  Those are both good options to get expert help.  :)
