### ISSUE TITLE
HANDOFF banner should be more verbose

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-web#2268]
When HANDOFF has permission for a distribution/module, this banner text is added:

> Take me over?
> The maintainer of this distribution is looking for someone to take over! If you're interested then please contact them via email.

Could that mailto: link also include the address of the last maintainer (if different from the first-come permission holder) -- or even include all the comaint holders in cc? I've had a few distributions taken over without my knowledge where I released it last but only have comaint rather than first-come, and I'd have been happy to continue maintaining the distribution (and incorporating the new arrival's patches) if only I had known.

I would also include explicit language in the body of the email noting what user did the last release, and the date of that release -- as often the first-come holder has lost track of what has happened with the distribution since his last release and other people took over, and this saves him the effort of having to look that up. Also it would be good to linkify the module name rather than just including it in plain text.

How about:

    - Hey $first_come_name,
    -
    - I'm interested in taking over the $module_name module. If you can grant me the privilege I will release the next version.

    + Hey $first_come_name (and co-maintainers $name, $name, $name),
    +
    + I would like to take over the <a href="https://metacpan.org/pod/$module_name">$module_name</a> module, last
    released on $date by $releaser_name. If you can grant me the privilege I will release the next version.

This would at least let other comaintainers have a chance to say "wait a minute!".

**Comment by oalders** [comment]
Pinging @ThisUsedToBeAnEmail for thoughts, since they kindly did the original work on this.

**Comment by ThisUsedToBeAnEmail** [comment]
I have no opinion on this, the text that is currently displaying was supposed to be just a 'draft' from me to demonstrate the point. So feel free to change: https://github.com/metacpan/metacpan-web/blob/master/root/inc/notification.html#L6

**Comment by karenetheridge** [comment]
#2293 is a more accurate telling of the situation than this.
