### ISSUE TITLE
Tree::AVL is not indexed

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#2273]
Hi!

See:

* https://rt.cpan.org/Public/Dist/Display.html?Name=Tree-AVL
* https://metacpan.org/author/MBEEBE
* https://www.cpan.org/modules/by-authors/id/M/MB/MBEEBE/
* https://cpants.cpanauthors.org/release/MBEEBE/Tree-AVL-1.073
* https://metacpan.org/search?q=tree%3A%3Aavl&size=20

It stopped getting indexed and found in searches, but it is there.

**Comment by Grinnz** [comment]
The module is not currently indexed in PAUSE: https://cpanmeta.grinnz.com/packages?module=Tree%3A%3AAVL&match_mode=prefix

The uploader or a pause admin can request a reindex at pause.perl.org, or someone with permissions can upload a new version.

**Comment by shlomif** [comment]
On Thu, 12 Mar 2020 11:18:55 -0700
Dan Book <notifications@github.com> wrote:

> The module is not currently indexed in PAUSE:
> https://cpanmeta.grinnz.com/packages?module=Tree%3A%3AAVL&match_mode=prefix
> 
> The uploader or a pause admin can request a reindex at pause.perl.org, or
> someone with permissions can upload a new version.
> 

Thanks for the info, Dan!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

Monologue: one person talking to himself.
Dialogue: two persons talking to themselves.
    — Shaike Ophir: http://www.youtube.com/watch?v=2bpVrKm9QCc

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by oalders** [comment]
@shlomif please update here once the re-index is complete so that we can trigger a manual re-index on your end. :)

**Comment by shlomif** [comment]
@oalders @Grinnz : thanks! I sent a reindexing request to the PAUSE admins by email to https://www.nntp.perl.org/group/perl.modules/ - from shlomif@gmail.com . It doesn't appear to be archived there yet, but I hope it will be soon.

**Comment by shlomif** [comment]
Update: my post has arrived at the online archive: https://www.nntp.perl.org/group/perl.modules/2020/03/msg100945.html .

**Comment by oalders** [comment]
Looks like it's still not in 02packages.

**Comment by neilb** [comment]
I've re-indexed it, and can see that it's reappeared in 02packages:

    Tree::AVL   1.077   M/MB/MBEEBE/Tree-AVL-1.077.tar.gz

**Comment by oalders** [comment]
<img width="1256" alt="Screen Shot 2020-03-31 at 10 13 37 AM" src="https://user-images.githubusercontent.com/96205/78036515-63537c80-7338-11ea-82a7-b04f89976e56.png">

Thanks everyone!

**Comment by shlomif** [comment]
Thanks @neilb , @oalders , @Grinnz & all.
