### ISSUE TITLE
Unable to remove distributions

### ISSUE THREAD

**Issue by zdm** [metacpan/metacpan-web#2280]
Hello.
I need to remove this distributions, they are old, buggy and not supported.

https://metacpan.org/release/Pcore-MySQL
https://metacpan.org/release/Pcore-Firebird

I am unable to remove them, because they are not listed under "Delete Files" section in my PAUSE account. This is some error, because I am the single owner of this distros.

How I can remove them or where I can get support?

**Comment by Grinnz** [comment]
This is a PAUSE issue. The uploader of those releases is able to delete them from their directory. If that is not the case send mail to modules@perl.org and PAUSE admins may be able to help.

**Comment by Grinnz** [comment]
You may also consider [marking them deprecated](https://neilb.org/2015/01/17/deprecated-metadata.html) without removing them from CPAN.

**Comment by zdm** [comment]
Thank you for info.
