### ISSUE TITLE
https://metacpan.org/search?q=perl&size=20 shows the latest version of "perl" as 5.30.0 instead of 5.30.2

### ISSUE THREAD

**Issue by shlomif** [metacpan/metacpan-web#2291]
https://metacpan.org/search?q=perl&size=20 shows the latest version of "perl" as 5.30.0 instead of 5.30.2 ; Moreover https://metacpan.org/pod/distribution/perl/pod/perl.pod points to 5.30.1. There is perl 5.30.2:

* https://www.reddit.com/r/perl/comments/filw9x/perl_5302_released/

* https://www.nntp.perl.org/group/perl.perl5.porters/2020/03/msg257227.html

Can you look into fixing it? Thanks!

**Comment by oalders** [comment]
Thanks @shlomif. I've re-indexed it and the release page now goes to the correct version.  The exposed URL in the search results are still not correct, though.

<img width="1139" alt="Screen Shot 2020-04-16 at 1 35 54 PM" src="https://user-images.githubusercontent.com/96205/79488259-75dfde00-7fe7-11ea-89b2-46a6390dc2b2.png">

**Comment by oalders** [comment]
Also, the first result for a search on `perl` is not very encouraging.

**Comment by shlomif** [comment]
> Thanks @shlomif. I've re-indexed it and the release page now goes to the correct version. 

Thanks!

> The exposed URL in the search results are still not correct, though.
> 

Any idea how to correct it?

**Comment by oalders** [comment]
I haven't yet looked into it.  I think we should fix https://github.com/metacpan/metacpan-api/issues/955 first and then see if this is still an issue.

**Comment by oalders** [comment]
It turns out that the older Perl needed to be re-indexed with the `cpan` status rather than `latest`.  It appears to be fixed now.
