### ISSUE TITLE
HANDOFF gives email to last releaser, not necessarily first-come

### ISSUE THREAD

**Issue by mohawk2** [metacpan/metacpan-web#2293]
I saw this on `Event` earlier. The then first-come, JPRIT, had added HANDOFF as a co-maint. The email link was to the last releaser (me), who couldn't do anything about it, wasting the emailer's time.

Comments / caveats:
- This isn't visible now, since then I've become first-come and removed `HANDOFF`.
- The HANDOFF-adding happened without me knowing, which is probably a missing PAUSE feature, not a MetaCPAN matter. It seems like there should be a pushed notification.

 #2268 says the banner isn't verbose enough, but by my reading it was Ok. I think (similar to that issue) the addresses mailed to should be `To` the first-come, `Cc` at least the last releaser, and probably all co-maints.

**Comment by karenetheridge** [comment]
I'll repeat what I said on irc -- if/when this is fixed, please do not mail only the first-come holder, but all comaint holders as well -- it is often the case that the original author of a module (still holding comaint) adds HANDOFF to *all* their modules, even though some of them are already maintained by someone else.

**Comment by djzort** [comment]
> I'll repeat what I said on irc -- if/when this is fixed, please do not mail only the first-come holder, but all comaint holders as well -- it is often the case that the original author of a module (still holding firstcome) adds HANDOFF to _all_ their modules, even though some of them are already maintained by someone else.

Perhaps this state of being handed off but still HANDOFF is something that should be addressed as its own bug?

**Comment by mohawk2** [comment]
Let's not try to solve all the world's problems at once. A material improvement would be to add to the list of addresses to be mailed, per @karenetheridge, and surely that would be a small and easy code-change.
