### ISSUE TITLE
WIN32::OLE is not working 

### ISSUE THREAD

**Issue by keshavr21** [metacpan/metacpan-web#2294]
getting this error while using win64 machine working fine in win 32
Error Inappropriate I/O control operationWin32::OLE(0.1712) error 0x800a801d

**Comment by Grinnz** [comment]
This is the issue tracker for the MetaCPAN website which is a search engine for the CPAN repository. The issue tracker for the Win32::OLE module is here: https://rt.cpan.org/Public/Dist/Display.html?Name=Win32-OLE
