### ISSUE TITLE
Dead links for .pm files

### ISSUE THREAD

**Issue by dk** [metacpan/metacpan-web#2298]
Hello,

I've got a couple of dead link in my distro, but assuming I did somehting wrong I couldn't find why.
Would you kindly help me find out why these

https://metacpan.org/pod/Prima::EditDialog
https://metacpan.org/pod/Prima::PrintDialog

return 404 while f ex

https://metacpan.org/pod/Prima::StdDlg

returns fine?

Thank you!
/dk

**Comment by karenetheridge** [comment]
> https://metacpan.org/pod/Prima::EditDialog
> https://metacpan.org/pod/Prima::PrintDialog

Where is the source for these files in the distribution? I cannot find them.

**Comment by haarg** [comment]
https://metacpan.org/source/KARASIK/Prima-1.58/Prima/EditDialog.pm
https://metacpan.org/source/KARASIK/Prima-1.58/Prima/PrintDialog.pm

**Comment by haarg** [comment]
These are both weird modules.

Prima/EditDialog.pm contains the packages Prima::FindDialog and Prima::ReplaceDialog, and the pod doesn't follow conventions for the NAME section.

Prima/PrintDialog.pm contains the package Prima::PrintSetupDialog.  The pod NAME section matches the file name, not the package contained.  This page is linked on the release page under the name Prima::PrintSetupDialog.

**Comment by dk** [comment]
Oh that is easy to fix .. thank you!
