### ISSUE TITLE
display core modules / since when [feature request]

### ISSUE THREAD

**Issue by telatin** [metacpan/metacpan-web#2299]
I think it would be useful to display a badge for "core modules" and since when they are so. 
I use 'corelist' a lot for this, but also MetaCPAN <3

If possible, a page listing the core modules also in MetaCPAN would be appreciated.

Thanks for the great job you do

**Comment by oalders** [comment]
Thanks for this @telatin.  I'm going to close this as it's a duplicate of #2264.  It's a very helpful suggestion.
