### ISSUE TITLE
utf-8 russian language

### ISSUE THREAD

**Issue by ea1985** [metacpan/metacpan-web#2308]
cat log4perl.pl
`#!/usr/bin/perl -w
use warnings;
use strict;
use Log::Log4perl qw(:easy);

use utf8;

sub logging {
    my ($filelog) = @_;
    umask 0022;

    my $config  = '
        log4perl.category         = WARN, Logfile
        log4perl.appender.Logfile = Log::Dispatch::FileRotate
        log4perl.appender.Logfile.filename    = '.$filelog.'
        log4perl.appender.Logfile.mode        = append
        log4perl.appender.Logfile.max         = 10
        log4perl.appender.Logfile.TZ          = PST
        log4perl.appender.Logfile.layout      = \.
            Log::Log4perl::Layout::PatternLayout
        log4perl.appender.Logfile.layout.ConversionPattern =%p:%F:%C:%L - %d %m %n
    ';

    Log::Log4perl->init(\$config);
    my $logger = Log::Log4perl::get_logger();
...
    return $logger;
}
my $logging=logging("log/test.log");
my $msg="тест";
$logging->error($msg);
`
`Wide character in print at /usr/local/share/perl/5.14.2/Log/Dispatch/File.pm line 149.`

cat log4perl.pl
`sub logging {
    my ($filelog) = @_;
    umask 0022;

    my $config  = '
        log4perl.category         = WARN, Logfile
        log4perl.appender.Logfile = Log::Dispatch::FileRotate
        log4perl.appender.Logfile.filename    = '.$filelog.'
        log4perl.appender.Logfile.mode        = append
        log4perl.appender.Logfile.max         = 10
        log4perl.appender.Logfile.TZ          = PST
        log4perl.appender.Logfile.layout      = \.
            Log::Log4perl::Layout::PatternLayout
        log4perl.appender.Logfile.layout.ConversionPattern =%p:%F:%C:%L - %d %m %n
    ';

    Log::Log4perl->init(\$config);
    my $logger = Log::Log4perl::get_logger();
...
    return $logger;
}
my $logging=logging("log/test.log");
my $msg="тест";
**_utf8::encode($msg) if utf8::is_utf8($msg);_**
$logging->error($msg);
` 
it working good

**Comment by haarg** [comment]
This is the issue tracker for the metacpan website, not the various modules it hosts documentation for. Possibly you are looking for https://github.com/mschout/perl-log-dispatch-filerotate/issues or https://github.com/houseabsolute/Log-Dispatch/issues.

You probably want to look at the binmode option, which is listed on https://metacpan.org/pod/Log::Dispatch::File
