### ISSUE TITLE
webperf - "Leverage browser caching of static assets" 

### ISSUE THREAD

**Issue by mohawk2** [metacpan/metacpan-web#2310]
https://webpagetest.org/performance_optimization.php?test=200615_WM_8d77c5a1320cf7af7badb20f6f423515&run=1#cache_static_content shows "FAILED - (No max-age or expires)":
- /static/images/metacpan-logo.png
- /static/icons/favicon.ico
- /static/icons/metacpan-icon.png
- /static/fonts//fa-regular-400.woff2
- /static/images/sponsors/liquidweb_color.png
- /static/images/sponsors/yellowbot.png
- /static/images/sponsors/bytemark_logo.png
- /static/images/sponsors/fastly_logo.png
- /static/fonts//fa-solid-900.woff2
- /static/fonts//fa-brands-400.woff2

**Comment by mohawk2** [comment]
The mighty @haarg advises that the static files are served by nginx, and that is configured via Puppet. This might be the relevant file, else it will live nearby: https://github.com/metacpan/metacpan-puppet/blob/master/modules/metacpan/manifests/web/static.pp

**Comment by haarg** [comment]
These are fixed now. The report still complains about the gravatars, but unless we want to entirely change what we are doing for those, that can't be fixed.

**Comment by mohawk2** [comment]
Agreed! This (https://webpagetest.org/performance_optimization.php?test=200620_F4_21bfde3cbc2b3457cc31e6bf4bbe540c&run=1#cache_static_content) now shows only gravatars, Google analytics, and the "activity" route which is fine. Also, the "first contentful paint" has gone from 2.4s to 1.4s, which I found actually noticeable.

Fantastic work @haarg!
