### ISSUE TITLE
Markdown not rendering correctly

### ISSUE THREAD

**Issue by djzort** [metacpan/metacpan-web#2312]
Please compare 

https://github.com/marioroy/mce-perl/blob/master/README.md

vs

https://metacpan.org/source/MARIOROY/MCE-1.872/README.md

The 3x ` seem to have problems.

**Comment by oalders** [comment]
So, issues with code fencing.

**Comment by djzort** [comment]
Looks like. Of course it may not be metacpan's bug as such, but rather a library

**Comment by haarg** [comment]
It's not strictly speaking a bug. MetaCPAN is using [MultiMarkdown](https://fletcherpenney.net/multimarkdown/) to render the markdown, which adds some extensions over [the original Markdown format](https://daringfireball.net/projects/markdown/). GitHub uses [its own set of extensions](https://github.github.com/gfm/) over the original Markdown.

It would be a good idea to switch to something [CommonMark](https://commonmark.org/) compatible.

**Comment by openstrike** [comment]
I also see that bulleted (unordered) lists in my markdown are rendered without list markers or inter-item vertical space which makes a list of long items just look like indented prose. See particularly the CODE section in this document.

Source: [CONTRIBUTING.md](https://fastapi.metacpan.org/source/HOUSTON/WebService-AbuseIPDB-0.03/CONTRIBUTING.md)
Rendered [at metacpan](https://metacpan.org/source/HOUSTON/WebService-AbuseIPDB-0.03/CONTRIBUTING.md)
Rendered [at gitlab](https://gitlab.com/openstrike/abuseipdb-client/-/blob/v0.03/CONTRIBUTING.md)

(let me know if you consider this a separate issue and I'll raise one)

**Comment by haarg** [comment]
That is an entirely different issue, because the style rules for markdown don't match what you want.

**Comment by oalders** [comment]
> It would be a good idea to switch to something CommonMark compatible.

Are there suggestions on a module we could switch to or does it not yet exist?

**Comment by djzort** [comment]
FWIW CommonMark is a module on cpan

https://metacpan.org/pod/distribution/CommonMark/lib/CommonMark.pod
