### ISSUE TITLE
Can not reconnect to Twitter in Identities

### ISSUE THREAD

**Issue by LadyAleena** [metacpan/metacpan-web#2322]
I was having trouble connecting my PAUSE account to my meta::cpan account, so I followed the directions in the [FAQ](https://wronghands1.files.wordpress.com/2019/11/hallmark-christmas-movie-plot-generator.jpg) to fix it. So, after I got my PAUSE account connected, I tried to reconnect my Twitter account. I went to Identities, clicked the green connect button, authorized the app on Twitter, and got the following page when Twitter redirected me back to meta::cpan.

![Twitter_back_to_meta_cpan](https://user-images.githubusercontent.com/123256/85348295-288d5a80-b4c9-11ea-8f06-fa9dd6f2d5a4.png)

**Comment by LadyAleena** [comment]
I tried again today, and I still can not connect my Metacpan account to my Twitter account.

**Comment by oalders** [comment]
Thanks for this. We should check the logs for today and see what's going on.

**Comment by LadyAleena** [comment]
I hope you find the problem. I think all of my favorite modules were attached to my Twitter account as is my preferred avatar. (It is the same avatar I use here on GitHub.)

**Comment by oalders** [comment]
bm-mc-01:
```
/home/metacpan/metacpan-api/var/log# grep twitter *
starman_error.log:[2020/09/24 22:27:49] [ERROR] [/login/twitter?oauth_token=[REDACTED]&oauth_verifier=[REDACTED]] Can't call method "value" on an undefined value at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Login/Twitter.pm line 35.
```
bm-mc-04:
```
$ grep twitter *
starman_error.log:[2020/09/24 22:27:49] [ERROR] [/login/twitter?oauth_token=[REDACTED]&oauth_verifier=[REDACTED]] Can't call method "value" on an undefined value at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Login/Twitter.pm line 35.
starman_error.log:[2020/09/24 22:27:50] [ERROR] [/login/twitter?oauth_token=[REDACTED]&oauth_verifier=[REDACTED]] Can't call method "value" on an undefined value at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Login/Twitter.pm line 35.

**Comment by oalders** [comment]
Can you try deleting your cookies and trying again?

**Comment by LadyAleena** [comment]
I deleted cookies and tried again but still nothing.

**Comment by bombsimon** [comment]
I just tried linking Twitter after merging https://github.com/metacpan/metacpan-api/pull/1071 and it worked so hopefully this will work for you as well now @LadyAleena

**Comment by oalders** [comment]
It worked for me as well. Thanks so much, @bombsimon! 🎉 

I'm still getting redirected to JSON on auth, but that's a different problem. Nice to see this working again!
