### ISSUE TITLE
Github tooltips show "error: error"

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2336]
Today when viewing POD for a module with a github repository, mousing over the relevant items in the left menu shows a popup with just "error: error" rather than details of the repo/issues. This is a new thing - I'm pretty sure it was fine last week but don't have a firm timestamp for that.

eg. looking at [HTML::Valid](https://metacpan.org/pod/distribution/HTML-Valid/lib/HTML/Valid.pod) if we mouse over either "Repository", "git clone" or "Issues" in the left menu we see the pop-up:

![pop-up](https://user-images.githubusercontent.com/4331674/86108900-a64df900-babb-11ea-95ec-c574361d872b.png)

That's just an example. It is the same with other modules and other authors.

**Comment by haarg** [comment]
Fixed by c4547d8d60bb30d4df48c2fa2d3dd8515eea3239

**Comment by oalders** [comment]
Thanks for reporting @openstrike!
