### ISSUE TITLE
Config-File-1.52.zip has bad hash

### ISSUE THREAD

**Issue by metabc** [metacpan/metacpan-web#2340]
It seems the recent Config-File-1.52.zip in http://www.cpan.org/authors/id/T/TH/THESEAL/Config-File-1.52.zip.

When i run the command "cpanm Config::File", I get error below

--> Working on Config::File
Fetching http://www.cpan.org/authors/id/T/TH/THESEAL/Config-File-1.52.zip ... OK
! Bad archive: [76b7fc46133c027befd3a68db6c4860526ec258b] Config-File-1.52.zip
! Failed to unpack Config-File-1.52.zip: no directory
! Failed to fetch distribution Config-File-1.52

If tI download the 1.51, it works. 
-- sudo curl -o config-file.tar.gz https://www.cpan.org/authors/id/T/TH/THESEAL/Config-File-1.51.tar.gz

-- sudo cpanm config-file.tar.gz

Please check the checksum on Config-File-1.52.zip

**Comment by haarg** [comment]
This is the issue tracker for the MetaCPAN website, not for the individual modules viewable on the site.

This is a bug in older versions of cpanm. `Config-File-1.52.zip` includes a zipfile comment, which is confusing cpanm's ability to parse the output of `unzip -t`. Updating cpanm should allow you to install the module.
