### ISSUE TITLE
Error after connected

### ISSUE THREAD

**Issue by lucas1** [metacpan/metacpan-web#2352]
I'm logged, but I don't can add in favorites. See image.
![Screenshot at 2020-07-16 00-40-31](https://user-images.githubusercontent.com/784699/87624123-5ac35e00-c6fd-11ea-9741-56eb64b524fd.png)

Thanks.

**Comment by haarg** [comment]
Fixed by 74e96a9589bf006c33276c77bf9803966dec7042
