### ISSUE TITLE
We can ++ with captcha, but never return

### ISSUE THREAD

**Issue by thibaultduponchelle** [metacpan/metacpan-web#2360]
When we want to ++ a distribution:
![cpansysdeps](https://user-images.githubusercontent.com/580360/87914168-8da88180-ca70-11ea-9726-d3a74bc762cb.png)

A popup is asking to solve a captcha:
![youhaveto](https://user-images.githubusercontent.com/580360/87914166-8d0feb00-ca70-11ea-9d4e-edb3267f1220.png)

It redirects to your profile to solve this captcha:
![captcha](https://user-images.githubusercontent.com/580360/87914165-8c775480-ca70-11ea-93b3-04a37e2a3d98.png)

If you complete it you get a success with a link to come back:
![success](https://user-images.githubusercontent.com/580360/87914164-8c775480-ca70-11ea-9a6b-11595822b61e.png)

Here is the problem, the link ("Continue browsing") is not redirecting to the initial distribution we are coming from but instead sends you to the same captcha page, asking you to complete it again and again:
![captchaagain](https://user-images.githubusercontent.com/580360/87914162-8bdebe00-ca70-11ea-8aec-1b71270e2e19.png)

It should either redirect to CPAN::Plugin::Sysdeps from where I was coming from initially or eventually -if it's too complicated- to metacpan homepage (I will happily accept to close this ticket with this solution :smile: ).

Technically, it worked and the great CPAN::Plugin::Sysdeps is well in my favorites (button is blue and I can now "remove from favorites"):
![wellplusplused](https://user-images.githubusercontent.com/580360/87915507-90a47180-ca72-11ea-878d-09602b8ca4a6.png)

Regards.

Thibault

**Comment by thibaultduponchelle** [comment]
I propose to close this issue since I think the feature of "++ without being signed in" seems disabled. WDYT ?

**Comment by oalders** [comment]
Sure, let's close it for now. We can always revisit if we need to. Thanks @thibaultduponchelle!
