### ISSUE TITLE
Feature Request: User contributed documentation and examples

### ISSUE THREAD

**Issue by afresh1** [metacpan/metacpan-web#2363]
It would be nice if metacpan users could submit additional documentation and examples for other user's dists.  I can see allowing pod, pm, or pl files.  I think they should show up clearly in a section of the release view below the "Other Files".  It should be visible who contributed the extra documentation and the user who added it should be able to update it.

This would likely necessitate the ability to "flag" these files as being inappropriate and would be nice if users could "++" them separately from the main dist.

The owners of the dist should be able to have some moderation ability, such as completely disabling the feature, disallowing specific other users from adding files, and completely blocking a specific file from showing up.

**Comment by oalders** [comment]
It sounds like you describing, at least somewhat, the way AnnoCPAN used to work?

**Comment by afresh1** [comment]
I don't recall ever actually using AnnoCPAN, but have a vague recollection that it let you add notes to existing documentation.  I was imagining whole new files of documentation or examples.

**Comment by LadyAleena** [comment]
I would suggest a separate section of meta::cpan for these, maybe call it Cookbooks or something similar? One could go to the Cookbook section and put in their recipes from modules.

**Comment by djzort** [comment]
An option might be to install foswiki and have it create a page for each module automatically, similar to how RT is used as a fallback default for bug tracking.

**Comment by LadyAleena** [comment]
@djzort Do you have a problem with MediaWiki? Until today I had never heard of foswiki.

In any case, a wiki would be great! Docs that are not so well written could be redone by anyone. A few tweaks would need to be made to pod2wiki, such as all pod `head1` would need to be moved to the second heading position and so on. Description sections would need to be moved to the top too.

However, we have time to discuss pod2wiki or whatever would be used to start the articles on the wiki.

**Comment by djzort** [comment]
foswiki is perl. without diving in to feature comparisons etc, that's the main reason i suggested it.

**Comment by LadyAleena** [comment]
As long as it has the same wiki markup as MediaWiki, and has the same namespaces as MediaWiki, I don't think it would be a problem. The one exception would be if foswiki has fallen into the socialization trap that Fandom/Wikia did. No socializing on anything but User talk: pages.

**Comment by jberger** [comment]
My concern with adding something like annocpan or even cpanreviews/rating is that the user-submitted content will either need to be bound to a particular version at which point they can be quickly lost to history or else tied to the namespace which means you have to worry about becoming outdated. There's also the problem of authors of modules disagreeing with user-generated content (like mojo used to get negative reviews that we couldn't easily dispute). Then there's GDPR. Honestly I don't think we want to go down this road.

I'd suggest that for modules that have github repos, you might encourage authors to open github-based wikis. Do we have a way to link to those via metadata in metacpan? We might, I can't remember offhand.

**Comment by LadyAleena** [comment]
I just thought of one problem with the wiki article title format, the colons. So, if there were an article for Fun::Things, the wiki namespace would be `Fun`, with the article title being `:Things`. That would need to be addressed.

**Comment by oalders** [comment]
If something like this gets created, it think should exist as a standalone service which MetaCPAN could link to. II don't see a compelling reason why it would need to be tightly coupled with the MetaCPAN front end.

**Comment by LadyAleena** [comment]
@oalders wiki.metacpan.org wouldn't be _that_ tightly coupled just like perldoc.perl.org, blogs.perl.org, and jobs.perl.org are not tightly coupled with perl.org.

**Comment by oalders** [comment]
@LadyAleena to be clear, what I'm saying is that this could live under something that is not `*.metacpan.org` and we could link to it, just like we do with http://cpancover.com/latest/index.html etc. I'm happy to see this discussion take place, but I think that this problem needs to be solved somewhere else. :)

**Comment by LadyAleena** [comment]
@oalders The problem I see with putting it somewhere else is the people behind it could get bored and one day this would fall just like AnnoCPAN did. Keeping it on metacpan.org at wiki.metacpan.org would give it more longevity. And today was the first time I'd heard of cpancover.

**Comment by oalders** [comment]
@LadyAleena that's a valid concern, but we don't have the available hours to take this on. Even if someone were to do the work, we will be stuck with the maintenance at some later point when that person moves on. Also, this will probably require some moderation, which is also outside of our wheelhouse.

I don't see why a motivated person or persons couldn't get this up and running somewhere else. Create a GitHub org to manage the rights and you should hopefully be able to avoid the problem of running out of humans to staff this. 

> I just took a look at cpancover, and that could be covered on metacpan also either on the main site or a possible wiki.
I strongly disagree. We believe in decoupling where possible. Even the API and the web site are their own projects.

cpancover.com is a giant beast. @pjcj does a wonderful job with it. I don't think it needs to be moved anywhere else.

**Comment by oalders** [comment]
> cpancover.com is a giant beast

To be clear, this is not a comment about the codebase for this site -- I haven't looked at. It's recognition that the site does a lot of heavy lifting and a lot of love and effort have gone into creating and maintaining it.

Things that can exist on their own should do so. If there's an issue with discoverability, there are other ways to address that, but linking to other resources is at the heart of what the web is good at. We should leverage this where it makes sense.

I'm going to close this ticket now. Hopefully the conversation can continue on somewhere else.
