### ISSUE TITLE
/recent report showing incorrect dates

### ISSUE THREAD

**Issue by tmetro** [metacpan/metacpan-web#2366]
It's currently Sat Aug  1 07:17:30 utc 2020 and https://metacpan.org/recent is showing these date headings:

Saturday, 6 August 2020
Friday, 5 July 2020
Thursday, 4 July 2020
Wednesday, 3 July 2020

The age of the individual distributions (shown as "39 minutes ago", "3 hours ago", etc.) look plausibly correct.

**Comment by haarg** [comment]
Fixed by b9ea3476fd3a50f7b36ad61c3fa708ab49b82fea
