### ISSUE TITLE
Recent uploads page seems to be very slow to update recently

### ISSUE THREAD

**Issue by tobyink** [metacpan/metacpan-web#2372]
https://metacpan.org/recent

![Screenshot from 2020-08-09 11-26-45](https://user-images.githubusercontent.com/251383/89730060-412ee100-da33-11ea-8520-9cbf84ff7845.png)

There's definitely been uploads more recent than 11 hours ago.

**Comment by tobyink** [comment]
Currently not showing any uploads for 16 hours.

**Comment by oalders** [comment]
This should be fixed now. Thanks for reporting!
