### ISSUE TITLE
Mojo::DOM::Role::Analyzer is no longer in metacpan repository

### ISSUE THREAD

**Issue by sdondley** [metacpan/metacpan-web#2373]
Up until a couple or hours ago, my module was up and running on metacpan. It is no longer visible, however: https://metacpan.org/pod/Mojo::DOM::Role::Analyzer
https://metacpan.org/release/Mojo-DOM-Role-Analyzer

It is listed on this page: https://cpan.metacpan.org/modules/02packages.details.txt

**Comment by sdondley** [comment]
This link works: https://metacpan.org/release/STEVIED/Mojo-DOM-Role-Analyzer-0.011

However, version 0.012 is not up and the module is not listed in search results (it was showing in search just fine previously): https://metacpan.org/search?q=mojo+dom+role+analyzer

**Comment by oalders** [comment]
@sdondley this should be back now. Thanks for reporting it!
