### ISSUE TITLE
Weird date format on favorite/recent

### ISSUE THREAD

**Issue by tobyink** [metacpan/metacpan-web#2388]
https://metacpan.org/favorite/recent has dates like "3 October, 2020" for *today* (7 October!)

It's caused by this line:
https://github.com/metacpan/metacpan-web/blob/master/root/favorite/recent.html#L13

It uses the code `%u` which is ISO 8601 weekday as number (so Monday=1, Tuesday=2, etc.) but should be using `%d` or `%e`.

**Comment by oalders** [comment]
I see the issue in production, but this does work for me locally when run on macOS.

<img width="1224" alt="Screen Shot 2020-10-08 at 16 08 11" src="https://user-images.githubusercontent.com/96205/95508114-7f3b7900-0980-11eb-886d-9579b8ca411b.png">

**Comment by oalders** [comment]
Latest Docker build is fine locally as well.

**Comment by xenu** [comment]
@oalders you were looking at the wrong page. https://metacpan.org/recent is fine, the problem exists on https://metacpan.org/favorite/recent

**Comment by tobyink** [comment]
Yeah, it's still broken.

**Comment by oalders** [comment]
Fixed via #2462 2462
