### ISSUE TITLE
Release link for File::RsyncP no longer works

### ISSUE THREAD

**Issue by craigbarratt** [metacpan/metacpan-web#2397]
This URL fails: [metacpan.org/release/File-RsyncP](https://metacpan.org/release/File-RsyncP).  It has worked for many years.  I recently released version 0.76, so perhaps that broke it.

These URLs do work:
* [metacpan.org/pod/File::RsyncP](https://metacpan.org/pod/File::RsyncP)
* [metacpan.org/release/CBARRATT/File-RsyncP-0.76](https://metacpan.org/release/CBARRATT/File-RsyncP-0.76)

The package does appear in [cpan.metacpan.org/modules/02packages.details.txt](https://cpan.metacpan.org/modules/02packages.details.txt):
```
File::RsyncP                       0.76  C/CB/CBARRATT/File-RsyncP-0.76.tar.gz
File::RsyncP::Digest               0.76  C/CB/CBARRATT/File-RsyncP-0.76.tar.gz
File::RsyncP::FileIO               0.76  C/CB/CBARRATT/File-RsyncP-0.76.tar.gz
File::RsyncP::FileList             0.76  C/CB/CBARRATT/File-RsyncP-0.76.tar.gz
```

**Comment by craigbarratt** [comment]
The release link is still broken.  Is there anything I can do (or someone can do) to fix it?

**Comment by mickeyn** [comment]
fixed
