### ISSUE TITLE
The documentation refers to snmprapd.conf

### ISSUE THREAD

**Issue by dimir** [metacpan/metacpan-web#2407]
https://metacpan.org/pod/NetSNMP::TrapReceiver

Although, rap daemon sounds fun. :-)

**Comment by Grinnz** [comment]
This is the issue tracker for the MetaCPAN web site. Use the "Issues" link in the sidebar of that module to report issues with a particular module.

**Comment by dimir** [comment]
Sorry, is this an auto-reply or I did something wrong?

**Comment by Grinnz** [comment]
You are a reporting an issue for a CPAN module. This is the issue tracker for the website which displays CPAN modules, it has nothing to do with the documentation CPAN modules include themselves.

**Comment by Grinnz** [comment]
The Issues link for this module as I mentioned goes to https://rt.cpan.org/Public/Dist/Display.html?Name=NetSNMP-TrapReceiver.

**Comment by dimir** [comment]
Oh, got it. Sorry.
