### ISSUE TITLE
How to get correct Repository link shown on metacpan.org

### ISSUE THREAD

**Issue by steve-m-hay** [metacpan/metacpan-web#2408]
In Makefile.PL scripts in my modules I have sections like this within the META_MERGE argument to WriteMakefile():

        resources => {
            repository => {
                type => 'git',
                url  => 'https://github.com/steve-m-hay/Text-Balanced.git'
            }
        },

That results in no Github/Repository/Clone links being shown on metacpan.org.

What is the correct way to do this? I see a variety of styles out there, but can't find my way through the various layers of documentation (ExtUtils::MakeMaker, CPAN::Meta::Spec, metacpan.org, ...) to work out what I want.

Some distros do it like this:

        resources => {
            repository => 'https://github.com/jib/archive-extract',
        }

which gives a "Clone Repository" (https://) link.

Some do it like this:

        resources => {
            repository => {
              url => 'git://github.com/demerphq/Algorithm-Heapify-XS.git',
            }
        }

or this:

        resources => {
            repository => {
                type => 'git',
                url  => 'https://github.com/shawnlaffan/Alien-Build-Plugin-Cleanse-BuildDir/',
            }
        }

which both give a "Clone git repository" (https://) link.

Some do it like this:

        resources   => {
            repository  => {
                type    => 'git',
                url     => 'git://github.com/pmqs/IO-Compress.git',
                web     => 'https://github.com/pmqs/IO-Compress',
            }
        }

which gives a "Repository" (https://) link and a parenthetical "git clone" (git://) link, but the latter is useless in my Chrome web browser on Windows 10.

Where is all this documented? Specifically, is there a way to simply get a "Repository" link going to a URL such as https://github.com/steve-m-hay/Text-Balanced ? I think that's all I want. I don't want the "git clone" link since it doesn't seem useful in a web browser (unless I'm missing something?). I just want the https:// Github URL link, but preferably called "Repository" rather than "Clone repository" or "Clone git repository" since the link doesn't actually clone the repository!

**Comment by haarg** [comment]
https://metacpan.org/pod/CPAN::Meta::Spec#repository shows how the repository information should be specified. That is for the meta version 2. By default EUMM's `META_MERGE` is specifying [meta v1](https://metacpan.org/pod/distribution/CPAN-Meta/lib/CPAN/Meta/History/Meta_1_4.pod). So to specify the repository using the v2 format, you have to specify version 2 in META_MERGE. Here is an example (taken from [Inline-Files](https://metacpan.org/source/AMBS/Inline-Files-0.71/Makefile.PL#L12-21)):
```perl
   META_MERGE        => {
      "meta-spec" => { version => 2 },
      resources => {
         repository => {
            type => 'git',
            url => 'git@gitlab.com:ambs/perl5-inline-files.git',
            web => 'https://gitlab.com/ambs/perl5-inline-files.git',
         },
      },
   },
```

**Comment by steve-m-hay** [comment]
> https://metacpan.org/pod/CPAN::Meta::Spec#repository shows how the repository information should be specified. That is for the meta version 2. By default EUMM's `META_MERGE` is specifying [meta v1](https://metacpan.org/pod/distribution/CPAN-Meta/lib/CPAN/Meta/History/Meta_1_4.pod). So to specify the repository using the v2 format, you have to specify version 2 in META_MERGE. Here is an example (taken from [Inline-Files](https://metacpan.org/source/AMBS/Inline-Files-0.71/Makefile.PL#L12-21)):
> 
> ```perl
>    META_MERGE        => {
>       "meta-spec" => { version => 2 },
>       resources => {
>          repository => {
>             type => 'git',
>             url => 'git@gitlab.com:ambs/perl5-inline-files.git',
>             web => 'https://gitlab.com/ambs/perl5-inline-files.git',
>          },
>       },
>    },
> ```

Thanks. I do have the meta-spec version 2 bit already. The example distribution that you give does have the single Repository (https://) link as I want, but curiously looks like it should have more than that (i.e. it should the "git clone" link as well) because it specifies "url" and "web" keys!?

Anyway, I'm now thinking that what I need is exactly what I currently have, except that I ought to change "url" to "web", i.e.:

    resources => {
        repository => {
            type => 'git',
            web  => 'https://github.com/steve-m-hay/Text-Balanced.git'
        }
    }

Does that sound correct? (I guess there's no way to try it, other than doing a new upload and seeing what comes out?)

**Comment by Grinnz** [comment]
Is there a specific release you are referring to where the 'url' key isn't picked up? Looking at the latest Text-Balanced release, it does not specify any repository information, nor does it have a META.json which is needed in order to represent meta-spec 2.

**Comment by Grinnz** [comment]
And yes, if you want the web repository link you want to use "web" rather than "url".

**Comment by steve-m-hay** [comment]
> Is there a specific release you are referring to where the 'url' key isn't picked up? Looking at the latest Text-Balanced release, it does not specify any repository information, nor does it have a META.json which is needed in order to represent meta-spec 2.

Lol! Yes, you're quite correct. I have the new information in the current version of Makefile.PL in Github, but haven't done a release of it yet...!

**Comment by steve-m-hay** [comment]
> And yes, if you want the web repository link you want to use "web" rather than "url".

Thanks for confirming. I will try this out and close the issue if (as I'm sure it will) it works.

**Comment by steve-m-hay** [comment]
This is indeed working now, so I am closing this issue. Thanks again for the help.
