### ISSUE TITLE
FindBin is missing from metacpan.org

### ISSUE THREAD

**Issue by slegga** [metacpan/metacpan-web#2409]
Hi, the module: FindBin is missing from metacpan.org.

How to recreate:
Try to search for FindBin om metacpan.org.

**Comment by Grinnz** [comment]
This is because it was unindexed for the purpose of a dual life release, but was never released. https://github.com/Perl/perl5/issues/14479

**Comment by Grinnz** [comment]
Until it has a separate CPAN release you can find the documentation for the version released with Perl at https://perldoc.perl.org/FindBin.

**Comment by oalders** [comment]
It's back! Thanks @toddr!
