### ISSUE TITLE
Distribution "App::ucpan" is lost

### ISSUE THREAD

**Issue by kpeejp** [metacpan/metacpan-web#2412]
Dear sir,
One of my distributions, "App::ucpan", has been lost for a long time.
Make sure it's listed: As it stands, no one will see it, no one will use it, and I won't get any feedback.
Initially it was listed, and it was updated even after the version was upgraded, but when I uploaded a new version, it suddenly stopped appearing in the list.
It's successfully registered on CPAN. (You can check it on cpanm --info App::ucpan)

**Comment by haarg** [comment]
I've reindexed the module and fixed the status of it. Thanks for the report.
