### ISSUE TITLE
Unable to update perl library using "carton" / "cpan" 

### ISSUE THREAD

**Issue by DipanjanSG** [metacpan/metacpan-web#2415]
Have a manifest file which contains the required perl modules like this :
requires 'Module::Util', '== 1.07';
requires 'MongoDB', '== 2.2.2';
requires 'Moose', '== 2.0601';
requires 'MooseX::AttributeHelpers', '== 0.23';

But I am getting the below error when I run the file with blow command :

/usr/local/bin/carton install --cpanfile=ecl/code/active/config/cpan.manifest

EROR IS THIS ->

Installing modules using /data01/production/ecl/code/active/config/cpan.manifest
Successfully installed MongoDB-v2.2.2 (upgraded from v1.8.0)
! Installing the dependencies failed: Installed version (v1.8.0) of MongoDB is not in range '== v2.2.2'
! Bailing out the installation for /data01/production/ecl/code/active/config/.
1 distribution installed
Installing modules failed

**Comment by DipanjanSG** [comment]
@oalders Pls help here

**Comment by oalders** [comment]
Please ask this question on StackOverflow.com You should get good help there.

**Comment by mohawk2** [comment]
@DipanjanSG This is the issue-tracker for just the metacpan.org website. We can't help with general CPAN, or module-installation issues. Good luck!
