### ISSUE TITLE
A little more font size big

### ISSUE THREAD

**Issue by yuki-kimoto** [metacpan/metacpan-web#2419]
This is my proposal.

Can metacpan font size become a little more big?

In my sense, how about 16px as default? Currently 13px, a little more 14px, 15px or 16px

Write where I feel the font is small.

- side bar
- header

**Comment by oalders** [comment]
Hi @yuki-kimoto! Do you find it too small for mobile or in general? Could you provide a screen shot to demonstrate what you find problematic?

**Comment by yuki-kimoto** [comment]
general. I see it on PC.

![metacpan](https://user-images.githubusercontent.com/81858/103841496-11b1fc80-50d7-11eb-857e-d95c520c954a.png)

**Comment by Akaxiounda** [comment]
No

**Comment by Fransjemo** [comment]
I agree with @yuki-kimoto about the font size of 13px that is a little to small. Here you can see how it looks like on a PC, while using Google Chrome with default the page proporties.
![report](https://user-images.githubusercontent.com/48428470/104983946-15664d00-5a0e-11eb-831b-0392b2fe2643.png)

**Comment by oalders** [comment]
We would accept a pull request which bumps up the font size so that we can test it out and see what the feedback is.

**Comment by yuki-kimoto** [comment]
Thank you.

I will write the code to to adjust the font size in a few weeks.

**Comment by yuki-kimoto** [comment]
Hi, I'm trying a little fix design on Windows Desktop.

I'm trying fine-tuning, is it possible to increase the default body font size?

13px to 15px.

<pre>
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 13px;
  line-height: 1.42857143;
  color: #333333;
  background-color: #ffffff;
}
</pre>

<pre>
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 15px;
  line-height: 1.42857143;
  color: #333333;
  background-color: #ffffff;
}
</pre>

**Comment by oalders** [comment]
@yuki-kimoto sure. If you provide a patch, we can deploy it and get some feedback.

**Comment by 1nickt** [comment]
FWIW I am happy with the font sizes as-is. You can always zoom in your browser. I am glad that the whole thing fits in one screen with no scrolling.

**Comment by yuki-kimoto** [comment]
@oalders @1nickt 

Before the patch, I feel that members of the metacpan developer need to discuss the 2021 default readable font size.

I feel a little small, on the other hand,  there are one say it isn't.

**Comment by oalders** [comment]
@yuki-kimoto it's trivial to revert a patch and re-deploy, so why don't you just do what you like best and we can see what people say about it? If it's controversial, we will revert. No big deal. :)

**Comment by yuki-kimoto** [comment]
@oalders OK, I will write patch in a few days.

**Comment by yuki-kimoto** [comment]
I try to edit body font-size.

I found in static directory. I can't find the file.

Would you tell me the file?

**Comment by oalders** [comment]
@yuki-kimoto I'm actually not too familiar with the static asset generation, but I believe you'd be looking at `root/static/less/style.less`. See `@font-size-base: 13px;` in that file. When you restart the app, it should regenerate the static assets for you and you should be able to see the changes. Please, let us know if that doesn't work for you.

**Comment by yuki-kimoto** [comment]
@oalders 

I try it.

**Comment by yuki-kimoto** [comment]
#2447

**Comment by mohawk2** [comment]
Merged the above. @yuki-kimoto If you feel the new font-size is better, (try in about an hour), please comment here and/or close the issue. If problems arise, as @oalders said it's easy to revert or adjust.

**Comment by yuki-kimoto** [comment]
Thank you!

**Comment by yuki-kimoto** [comment]
I feel the new font-size is better.

If possible, is it possible to talk about a few design improvement?

**Comment by haarg** [comment]
This increase in size has caused a few issues with the layout. The text in the sidebars doesn't quite fit anymore.

**Comment by yuki-kimoto** [comment]
I feel that the width of the sidebar is a little small.

If possible, I can fix it.

**Comment by 1nickt** [comment]
IMHO the size needs to be reverted.

-nick

**Comment by openstrike** [comment]
I have had to zoom out when viewing pages on metacpan.org today as the font was too large.

Isn't specifying font sizes in pixels frowned upon anyway? The variety in pixel densities these days means that it's always going to look bad on somebody's display if you specify pixel sizes.

**Comment by oalders** [comment]
So far the responses on Twitter have been positive: https://twitter.com/metacpan/status/1373667588207742980

**Comment by andyjack** [comment]
I like the size increase.  I noticed that the last line of a code block is not rendering `_` underscores, e.g. for [DBI](https://metacpan.org/pod/DBI#last_insert_id) - so the layout could use a tweak.

![chomped](https://user-images.githubusercontent.com/8292769/112015950-a89d2b00-8b02-11eb-8acc-55169066a683.png)

**Comment by oalders** [comment]
> I feel that the width of the sidebar is a little small.
> 
> If possible, I can fix it.

@yuki-kimoto that would be helpful.

**Comment by yuki-kimoto** [comment]
@oalders 

I will try in a few days.

**Comment by wolfsage** [comment]
I find the larger font distracting and it makes it harder for me to comprehend what I'm reading so I also need to zoom out to use it, fwiw

**Comment by yuki-kimoto** [comment]
#2449

I create pull request.

side bar  width become 174px to 195px.

What do you think?

**Comment by Grinnz** [comment]
I dislike the new font size mostly because it doesn't look nice to me, but it seems fine on mobile.

**Comment by 1nickt** [comment]
<img width="206" alt="image" src="https://user-images.githubusercontent.com/12807261/112760656-d03e3880-8fc5-11eb-9744-1954679236d2.png">

This background element is also broken now fwiw

**Comment by yuki-kimoto** [comment]
@Grinnz 

If there are many people who dislike it, getting them back is a good choice.

I want us to talk about the default font size of the Web, which is easy to read and general in 2021.

In my sense, <b>universal design</b> is a size that is easy for the elderly and children to read.

**Comment by yuki-kimoto** [comment]
@1nickt 

Thank you. I will fix it.

**Comment by haarg** [comment]
The 'Questions?' banner is fixed by #2450

**Comment by yuki-kimoto** [comment]
@haarg 

Sorry, Not yet.

I plan to fix in a few days.

**Comment by haarg** [comment]
@yuki-kimoto The banner and other sidebar width issues have already been fixed.

**Comment by yuki-kimoto** [comment]
@haarg Thank you!

**Comment by mohawk2** [comment]
Are there remaining issues or can this be regarded as fixed?

**Comment by yuki-kimoto** [comment]
not remain about the font size. Please close this issue.

About other design improvement, I will create new issue.
