### ISSUE TITLE
Examples files are no longer listed on release pages

### ISSUE THREAD

**Issue by Grinnz** [metacpan/metacpan-web#2427]
Examples files were previously listed on release pages along with Modules, Documentation, etc. They no longer seem to be shown.

https://metacpan.org/release/Mojolicious

**Comment by zmughal** [comment]
This is also what I'm seeing via the API:

```shell
$ curl -s 'https://fastapi.metacpan.org/v1/release/interesting_files/SRI/Mojolicious-9.18' | jq '.files|.[]|.category' | sort -u
"changelog"
"contributing"
"dist"
"license"
"other"
```

so no `example` category.

<https://metacpan.org/source/SRI/Mojolicious-9.18/examples> should be categorised as `example` per <https://github.com/metacpan/metacpan-api/commit/9ca3563e9cb040ef56cc8c35de581e0d3cefaf12>.

**Comment by zmughal** [comment]
@haarg, should `$path_files{example}` also contain `qw( example examples Example Examples )` in <https://github.com/metacpan/metacpan-api/blob/9ca3563e9cb040ef56cc8c35de581e0d3cefaf12/lib/MetaCPAN/Query/File.pm#L146-L151>?

Connected to change in <https://github.com/metacpan/metacpan-api/pull/992>.

Other dists where this would be useful:
- <https://metacpan.org/source/ETJ/PDL-2.048/Example>
