### ISSUE TITLE
Explain "advanced searches"

### ISSUE THREAD

**Issue by szabgab** [metacpan/metacpan-web#2440]
I think it would be helpful to make it easy for people to find out what "advanced searches" are available on MetaCPAN.

There is already a FAQ entry with this information  https://metacpan.org/about/faq#anon-comprehensivelistofspecialsearchexpressions:

My idea would be to
1. Add a link next to the search box (both on the front page and on the internal pages) that will link to that FAQ entry.
1. Maybe rename that FAQ entry to be called "Advanced Searches"

The link could be "Advanced searches" or it could be just an (i)  fa-info-circle from fontawesome

**Comment by thibaultduponchelle** [comment]
(?) or (i) with a hover popup would be fine :+1:

In addition I think this faq section could be promoted to first faq item :smiley:

**Comment by oalders** [comment]
It would be nice to bring it up in a modal like we do for keyboard shortcuts when you press "shift + ?".

**Comment by szabgab** [comment]
You see, I was not aware the `?` button either. (even though I have the same on my slide-system)
I just posted a poll in the "Perl Programmers" Facebook group asking if people are familiar with it. Partially I would like to know and partially as that make more people aware of the keyboard shortcuts. If you are part of the group you can see the poll here: https://www.facebook.com/groups/perlprogrammers/permalink/4036194559746635/

**Comment by szabgab** [comment]
Now that I saw that modal, I'd say we could add the list of special searches to that window AND I think we need to visual hint so people will press ? to explore it. (e.g. ? after the search box that is a button that show the same modal)

**Comment by oalders** [comment]
Yeah, it's kind of an easter egg right now. It would be great to add a visual hint that it's there. It has been around for many years. :)

**Comment by szabgab** [comment]
Implemented and it was deployed.
