### ISSUE TITLE
A search for VRML::Color gives a dead link

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#2451]
A search for VRML::Color

https://metacpan.org/search?q=VRML::Color

![vrml-color](https://user-images.githubusercontent.com/102005/113524785-f24e4100-95eb-11eb-89f3-42156a648288.png)

gives the following, which is a dead link:

https://metacpan.org/pod/VRML::Color

![not-found](https://user-images.githubusercontent.com/102005/113524787-f67a5e80-95eb-11eb-84ca-0b95921d9fd8.png)

**Comment by Grinnz** [comment]
It's not great that it's a dead link, but I believe the underlying cause is because Color.pm has its name set as "Color.pm" rather than "VRML::Color" in the pod: https://metacpan.org/source/HPALM/VRML-1.10/Color.pm#L232

**Comment by benkasminbullock** [comment]
Clicking from here:

https://metacpan.org/source/HPALM/VRML-1.10

under the "Name" column also gives the same dead link.

https://metacpan.org/source/HPALM/VRML-1.10/Color.pm#L232

Clicking from the "Documentation" colomn gives a valid link:

https://metacpan.org/pod/release/HPALM/VRML-1.10/Color.pm

**Comment by mickeyn** [comment]
The release wasn't marked as latest for some reason (I suspect META, but didn't check).
Anyway, it's fixed now.
