### ISSUE TITLE
CRITICAL - No way to report bugs in Modules

### ISSUE THREAD

**Issue by gitcnd** [metacpan/metacpan-web#2486]
Going here: https://metacpan.org/release/JSON-XS - no links to report bugs.

Going to the "issues" link above => https://rt.cpan.org/Public/Dist/Display.html?Name=JSON-XS - no links to report new bugs.

Above are EXAMPLES ONLY.  This applies to *everything* that shows problems but gives us no way to report new ones.

I realize perl is beyond saving at this point, but, actively making it difficult/impossible to maintain by not letting anyone report anything is vastly accelerating its demise...

If metacpan was a car, it would have NO AIRBAGS, NO SEATBELTS, and NO SAFETY.

**Comment by Grinnz** [comment]
The instructions for reporting bugs to RT queues are shown at https://rt.cpan.org/. I agree that it is hard to find this from the metacpan link now but I don't think there's anything metacpan can do to fix this RT interface issue.

For the specific case of JSON-XS, the author (MLEHMANN) does not accept bug reports in a public tracker. See his module documentation for how to report bugs to him privately.

**Comment by Grinnz** [comment]
I've sent a request to the RT maintainers to see if the interface can be improved there.

**Comment by gitcnd** [comment]
So it turns out the "Report a new bug" button is rendered invisible unless you're logged in... totally stupid.  They should ALWAYS SHOW THE BUTTON (and send you to login when you click it if you're not already)
