### ISSUE TITLE
Include bus factor somewhere in the UI

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#2493]
Bus factor is now available via the API: https://fastapi.metacpan.org/v1/distribution/Moose

Should we use a font-awesome bus? https://fontawesome.com/icons/bus

**Comment by renderorange** [comment]
(please read this as a sincere question)
What purpose does having this metric solve?

**Comment by oalders** [comment]
There's a blog post or two on the way which will go into detail why this metric exists.
