### ISSUE TITLE
Pg::Explain was uploaded to PAUSE, but is not visible on CPAN/MetaCPAN?

### ISSUE THREAD

**Issue by depesz** [metacpan/metacpan-web#2499]
Hi,
I might have done something wrong, or didn't do something needed, but I think I recall installing Pg::Explain from cpan, and now it's no longer there. What is wrong?

**Comment by Grinnz** [comment]
The indexed version of Pg::Explain has been deleted from CPAN: https://metacpan.org/release/DEPESZ/Pg-Explain-1.07

Either force reindexing of the previous version in the PAUSE interface so that 1.06 will get indexed, or upload a new version (unfortunately you cannot reupload the same version).

**Comment by depesz** [comment]
Is there a way to figure out why it was deleted?

**Comment by Grinnz** [comment]
Not sure other than searching your email for PAUSE mails or asking the PAUSE admins at modules@perl.org.
