### ISSUE TITLE
Image::CairoSVG disappeared

### ISSUE THREAD

**Issue by benkasminbullock** [metacpan/metacpan-web#2507]
I uploaded a module about 1.5 hours ago and it is still not visible:

https://metacpan.org/recent

![recent](https://user-images.githubusercontent.com/102005/118431562-9bbb4300-b711-11eb-9ebd-d797d9028998.png)

Then it seems to have disappeared completely:

https://metacpan.org/search?q=Image%3A%3ACairoSVG

![disappeared](https://user-images.githubusercontent.com/102005/118431574-9fe76080-b711-11eb-94f4-0f3e0c4f2ebd.png)

This is on CPAN (except for the most recent one):

![all-releases](https://user-images.githubusercontent.com/102005/118431593-aa095f00-b711-11eb-9ab0-5bd6f475c98f.png)

**Comment by mickeyn** [comment]
reindexed. it's there now. 0.21 is the latest in the index/search.
