### ISSUE TITLE
DBD::DB2 1.88 not reflecting in CPAN

### ISSUE THREAD

**Issue by AWADHAMBIKA** [metacpan/metacpan-web#2509]
Hi Team,
I uploaded the latest version of my module DBD::DB2 i.e. 1.88 today almost 6 hours back and I received the successful indexing email from PAUSE but at the time of raising this issue, the module version 1.88 is still not visible on cpan.org.
Can someone please help me if something is wrong?

**Comment by haarg** [comment]
Fixed.
