### ISSUE TITLE
Missing support of MooX::Enumeration

### ISSUE THREAD

**Issue by jsf116** [metacpan/metacpan-web#2521]
This is just a clone of https://rt.cpan.org/Ticket/Display.html?id=136678&results=3ee348b549e2cc18e2106901a6996e86

Trying to apply **MooX::Enumeration** as a constraint I detected that this attempt is not rejected but also has no effect.
The following snippet demonstrates a difference in the behavior in this regard between validation based on **MooX::Enumeration** and another one based on **Type::Tiny**:

```
use Moo;
use MooX::Enumeration;
use MooX::Struct
  Foo => [
    fooAttribute => [ enum => [ qw(A B) ], traits => [ 'Enumeration' ], is => 'ro', required => 1 ],
  ];
use Type::Tiny;
use MooX::Struct
  Bar => [
    barAttribute => [
      isa      => Type::Tiny->new(
        name       => 'Direction',
        constraint => sub { /^[AB]$/ },
        message    => sub { 'erroneous letter for barAttribute' },
      ),
      is       => 'ro',
      required => 1,
    ],
  ];
use Test2::V0;

ok(dies { Foo['X'] }, 'erroneous letter for fooAttribute');
ok(dies { Bar['X'] }, 'erroneous letter for barAttribute');

done_testing();
```

As you can see, the 1st attempt (using **MooX::Enumeration**) does not lead to expected exception caused by a wrong letter **X**, whereas the 2nd attempt (using type check based on **Type::Tiny**) raises the exception properly.
I would suggest to either reject the usage of **MooX::Enumeration** raising an exception or to support its usage in accordance with the description of this class.

**Comment by haarg** [comment]
This is the issue tracker for the metacpan website, not for MooX::Enumeration.

**Comment by oalders** [comment]
@jsf116 have a look at https://rt.cpan.org/Public/Dist/Display.html?Name=MooX-Enumeration
