### ISSUE TITLE
rss feed is broken

### ISSUE THREAD

**Issue by msmeissn** [metacpan/metacpan-web#2532]
hi,

https://metacpan.org/recent.rss is broken currently

**Comment by haarg** [comment]
How is it broken?

**Comment by msmeissn** [comment]
html of /recent has a superflous space:
which makes the link not work at least (between .rss and ?)

      <a href="/recent.rss ?f=l"><i class="fa fa-rss fa-2x black"></i></a>

**Comment by haarg** [comment]
Fixed in c2ae0cfcf8ca99da3bc488a510d03ea2b74f8244. Will be deployed soon.
