### ISSUE TITLE
Bus factor: Mouse-over experience is not uniform and overlapping with piece of code.

### ISSUE THREAD

**Issue by rai-gaurav** [metacpan/metacpan-web#2540]
The 'Bus factor' and its tool-tip which is recently added is not uniform throughout the page.
E.g.
By default it will open on right hand side and consist of 4 lines.
![1](https://user-images.githubusercontent.com/23376158/122651355-e2a7b880-d155-11eb-8e62-502d60a27683.JPG)

If we scroll a little bit and go down the alignment changed a little bit
![2](https://user-images.githubusercontent.com/23376158/122651375-fc490000-d155-11eb-9f9e-eb7f2047bb1d.JPG)

Also, if we scroll more and go to 'Synopsis' section or any section which contain piece of code, its overlapping with it(maybe because of z-index ?)
![3](https://user-images.githubusercontent.com/23376158/122651401-2f8b8f00-d156-11eb-83a6-cd753e72547e.JPG)

Similar behavior is observed in both Firefox and Chrome.

**Comment by oalders** [comment]
What happens if you remove `data-placement="right"`?

**Comment by rai-gaurav** [comment]
Tried it by removing data-placement, but no changes are observed.
The tool-tip behavior is similar as before.

**Comment by haarg** [comment]
Should be fixed by #2542
