### ISSUE TITLE
“Jump to version” URL paths missing /view

### ISSUE THREAD

**Issue by johannessen** [metacpan/metacpan-web#2545]
The “Jump to version” links currently seem to be broken. It appears that POD pages were recently moved to a new URL that includes `/view` in the path, but the links weren’t updated and no redirect put in place. Release pages are unaffected.

## Steps to Reproduce

1. Go to <https://metacpan.org/pod/MetaCPAN::Client>.
2. Open the “Jump to version” menu on the bottom of the left sidebar.
3. Select version 2.028000.

## Expected Result

<https://metacpan.org/release/MICKEY/MetaCPAN-Client-2.028000/view/lib/MetaCPAN/Client.pm>

## Actual Result

<https://metacpan.org/release/MICKEY/MetaCPAN-Client-2.028000/lib/MetaCPAN/Client.pm>
which is a 404

## Possible Fix

If I understand correctly, adding an appropriate rule to [OldUrls.pm](https://github.com/metacpan/metacpan-web/blob/master/lib/MetaCPAN/Middleware/OldUrls.pm) should produce an HTTP redirect solving the issue. Such a redirect would also address bookmarks and other incoming links.

The relevant template producing the broken `href` seems to be:

https://github.com/metacpan/metacpan-web/blob/3fc5181ece15d8cc16088f3556a14dd04fcaa2bd/root/inc/version_select.tx#L5

I don’t know where exactly the value of `$module.path` comes from or where else it might be used, but I’m sure you do.

**Comment by haarg** [comment]
A redirect in OldUrls won't be needed, because those URLs never worked.

Fixed in dcb3920ddb9b2cfd86d9818f5f4c255e805bdd17
