### ISSUE TITLE
perl IPC-Cmd: signals not being reported

### ISSUE THREAD

**Issue by scarneysc** [metacpan/metacpan-web#2547]
- OS: CentOS 7.9
- Version of module: 0.80-4

The IPC::Cmd module traps for signals and reports them.  When I sent the KILL signal to the external program it is calling,
a signal was taken.  However, the module is not reporting what the signal is.  The output is

  `<date stamp> <hostname> '/path/to/external_program --opt1 --opt2 --opt3 --outputdir=/dev/shm/<some_dir>' died with signal %d, %s coredump`

in the IPC::Run module.  The method taking the signal has this code snippet:

    sub _pp_child_error {
    ...
    } elsif ( $ce & 127 ) {
          ### some signal
          $str = loc( "'%1' died with signal %d, %s coredump\n",
                 $pp_cmd, ($ce & 127), ($ce & 128) ? 'with' : 'without');

      } else {
      ...    ### Otherwise, the command run but gave error status.
      }
      ...
    }

I tracked down the 'loc' method and it comes from the Locale::Maketext::Simple module which translates
the text.  Something seems to be lost in translation in the loc call.  I suspect it needs to go
through an sprintf call first.  Then pass that result to loc.

I modified the _pp_child_error() method in the Cmd.pm module on my system like so:

      my $str1;
      my $str;
      } elsif ( $ce & 127 ) {
          ### some signal

          $str1 = sprintf( "\'%s\' died with signal %d, %s coredump\n",
                $pp_cmd, ($ce & 127), ( ($ce & 128) ? 'with' : 'without' ) );

          $str = loc( $str1 );
      } else {
      ...

With that fix, now I am seeing:

  `<date stamp> <hostname> '/path/to/external_program --opt1 --opt2 --opt3 --outputdir=/dev/shm/<some_dir>' died with signal 7, without coredump`

Another note.  The latest version of this modules is 1.04.  I looked at the code and it is the same problem.

**Comment by haarg** [comment]
This is the issue tracker for the metacpan website.

The issue tracker for IPC::Cmd is at https://rt.cpan.org/Dist/Display.html?Name=IPC-Cmd

**Comment by scarneysc** [comment]
To confirm, I should open an issue at the cited link?

**Comment by oalders** [comment]
@scarneysc that's correct! Thanks for reporting bugs. :)
