### ISSUE TITLE
How set bugtracker to github?

### ISSUE THREAD

**Issue by Azq2** [metacpan/metacpan-web#2548]
I set bugtarcker field:
```
			bugtracker => 'https://github.com/Azq2/perl-html5-dom/issues'
```
https://github.com/Azq2/perl-html5-dom/blob/master/Makefile.PL#L70

But it not works. 

`Issues (2)` link on https://metacpan.org/release/ZHUMARIN/HTML5-DOM-1.20 is https://rt.cpan.org/Public/Dist/Display.html?Name=HTML5-DOM, not github

Why?

**Comment by haarg** [comment]
https://metacpan.org/pod/CPAN::Meta::Spec#bugtracker

The bug tracker should not be just a URL, but a hash with a 'web' key.

```
bugtracker => {
    web => 'https://github.com/Azq2/perl-html5-dom/issues',
},
```
