### ISSUE TITLE
Parsing files without extension error

### ISSUE THREAD

**Issue by baudilio** [metacpan/metacpan-web#2553]
When a file has no extension _e.g.,_ `mainproc` in the example below, the following error occurs:

```
... etc ...
Generating code for file mainproc...
Use of uninitialized value $1 in lc at /home/baudilio/perl5/bin/doxygen-filter-perl line 63.
Generating file documentation...
... etc ...
```
and no documentation is produced for that source code.

**Comment by oalders** [comment]
We can try to direct you to the right place for your report, but without more context I don't see how that's possible.

**Comment by baudilio** [comment]
Olaf:

My apologies. I though I was automatically redirected to the  project site and repository on giltlab, and hence my succinctness.  I'm sorry. 

This issue is intended for `https://metacpan.org/pod/Doxygen::Filter::Perl`

Would it be possible to forward it directly?

Thank you!
Baudilio

**Comment by Grinnz** [comment]
No; metacpan has no affiliation with any modules on CPAN.

**Comment by oalders** [comment]
Hi Baudilio,

No worries! If you use the link provided above, that would be the best place to report the bug. 🐛
