### ISSUE TITLE
browse link redirects incorrectly on submodules

### ISSUE THREAD

**Issue by inphobia** [metacpan/metacpan-web#2568]
quick example:
https://metacpan.org/pod/Alien::Build::Plugin::Build::Autoconf

-> click browse (either regular or (raw))
![image](https://user-images.githubusercontent.com/39005454/125179262-5be27a80-e1ed-11eb-853f-2f6d0bfe5b8a.png)

this will redirect to:
- with browse: https://metacpan.org/dist/Alien-Build/source/lib
- with browse raw: https://fastapi.metacpan.org/source/PLICEASE/Alien-Build-2.41/lib

i would have expected it to redirect to the containing directory, in this case either:
- https://metacpan.org/release/PLICEASE/Alien-Build-2.41/source/lib/Alien/Build/Plugin/Build
- https://fastapi.metacpan.org/source/PLICEASE/Alien-Build-2.41/lib/Alien/Build/Plugin/Build/

instead it seems under base /lib (or /bin for executables)

**Comment by oalders** [comment]
@inphobia is this still an issue for you?

**Comment by haarg** [comment]
This should have been fixed by #2570

**Comment by oalders** [comment]
Looks to me to be working now.

**Comment by inphobia** [comment]
late reply but yup, seems to be working as expected for me now.
