### ISSUE TITLE
Spurious die with "TODO" message during parse.

### ISSUE THREAD

**Issue by uniejo** [metacpan/metacpan-web#2571]
0.25 seems to have a case that exits parsing with a "TODO" message.
Likely related to regexp matching in catch.

$ perl -I local/lib/perl5 -E 'use Syntax::Keyword::Try; say "Before"; try {} catch($err) { }; say "After";'
Before
After
$ perl -I local/lib/perl5 -E 'use Syntax::Keyword::Try; say "Before"; try {} catch($err =~ m/whoa/) { }; say "After"'
TODO
$

Installation also fails in 04catch-types.t :
...
Configuring Syntax-Keyword-Try-0.25
Running Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Syntax-Keyword-Try' version '0.25'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have XS::Parse::Keyword 0.06 ... Yes (0.08)
Checking if you have ExtUtils::CBuilder 0 ... Yes (0.280231)
Checking if you have Test::More 0.88 ... Yes (1.302162)
Building and testing Syntax-Keyword-Try-0.25
Building Syntax-Keyword-Try
x86_64-linux-gnu-gcc -I/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -DVERSION="0.25" -DXS_VERSION="0.25" -fPIC -Ihax -I. -c
-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -o lib/Syntax/Keyword/Try.o lib/Syntax/Keyword/Try.c
ExtUtils::Mkbootstrap::Mkbootstrap('blib/arch/auto/Syntax/Keyword/Try/Try.bs')
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Syntax/Keyword/Try/Try.so lib/Syntax/Keyword/Try.o
t/00use.t .............. ok
t/01trycatch.t ......... ok
t/02tryfinally.t ....... ok
t/03trycatchfinally.t .. ok
TODO
t/04catch-types.t ......
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
t/10snail.t ............ ok
t/11loop.t ............. ok
t/12return.t ........... ok
t/13die-in-finally.t ... ok
t/14try-localises.t .... ok
t/15context.t .......... ok
t/16final-expr.t ....... ok
t/30compat.t ........... ok
t/70deparse.t .......... ok
t/80await+SKT.t ........ skipped: Future::AsyncAwait >= 0.50 is not available
t/80defer+SKT.t ........ skipped: Syntax::Keyword::Defer >= 0.02 is not available
t/90rt123547.t ......... ok
t/90rt125971.t ......... ok
t/99pod.t .............. skipped: Test::Pod 1.00 required for testing POD

Test Summary Report
-------------------
t/04catch-types.t    (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=19, Tests=59,  7 wallclock secs ( 0.01 usr  0.17 sys +  0.87 cusr  3.72 csys =  4.77 CPU)
Result: FAIL
Failed 1/19 test programs. 0/59 subtests failed.
-> FAIL Installing Syntax::Keyword::Try failed. See /home/uniejo/.cpanm/work/1626086978.9604/build.log for details. Retry with --force to force install it.
1 distribution installed

Tested on linux for windows, Ubuntu 20.04 LTS
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

**Comment by haarg** [comment]
This is the issue tracker for the metacpan website, not the individual modules it displays documentation for.

The issue tracker for Syntax-Keyword-Try is at https://rt.cpan.org/Dist/Display.html?Name=Syntax-Keyword-Try

**Comment by uniejo** [comment]
Thanks. And sorry.

**Comment by oalders** [comment]
Thanks for reporting bugs @uniejo!
