### ISSUE TITLE
Problem with sign in via github account

### ISSUE THREAD

**Issue by poizon** [metacpan/metacpan-web#2595]
After click on sign in through github OAuth, I've got an error:
There has been an error with your request: bad_verification_code
And no sign in

I revoked Authorized OAuth Apps in my github profile and grant metacpan again, but still unsuccessful.

**Comment by paulo-graca** [comment]
I'm having the same issue...

**Comment by AlexP007** [comment]
the same

**Comment by oalders** [comment]
https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors#bad-verification-code

If you attempt more than once are you eventually able to authenticate?

**Comment by poizon** [comment]
> https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors#bad-verification-code
> 
> If you attempt more than once are you eventually able to authenticate?

No, I attempted a lot...

**Comment by GeekRuthie** [comment]
Same problem...

**Comment by poizon** [comment]
I think this problem describes here:

https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors#bad-verification-code

And to solve this -  start the OAuth authorization process again and get a new code for you app:
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

and update config:
https://github.com/metacpan/metacpan-web/blob/75276c60b7cbe7ef4c8c582bdb3a519090f6bc33/metacpan_web.conf#L10

**Comment by niceperl** [comment]
Twitter login is not working also

**Comment by oalders** [comment]
Sorry, everyone. We are understaffed over here. If anyone wants to pitch in and help get some of this stuff working again, we'd be happy to work with you.

**Comment by poizon** [comment]
> Sorry, everyone. We are understaffed over here. If anyone wants to pitch in and help get some of this stuff working again, we'd be happy to work with you.

 Hi, I wrote about solving here: https://github.com/metacpan/metacpan-web/issues/2595#issuecomment-943087700
Need access to all of the affected services and refresh their tokens

**Comment by oalders** [comment]
Just to clarify, It's a bit confusing, but `consumer_secret = ClearAirTurbulence` is the secret which the API uses to act as an OAuth provider itself. It's unrelated to any of the 3rd party apps. The 3rd party secrets get configured in `metacpan-api`.

I'm just rotating the client secret for the MetaCPAN GitHub app. It will take a while for puppet to pick up and apply the changes. I think it should happen hourly. If this doesn't fix things, we'll try something else.

**Comment by oalders** [comment]
Can confirm that Twitter OAuth triggers the generic Catalyst error page.

**Comment by oalders** [comment]
```
GET https://api.twitter.com/oauth/access_token failed: 401 Unauthorized at /home/metacpan/metacpan-api/lib/MetaCPAN/Server/Controller/Login/Twitter.pm line 32
```

**Comment by oalders** [comment]
Twitter consumer_key and consumer_secret have now been rotated as well. Will take a while to go into production as well.

**Comment by mbeijen** [comment]
Unfortunately, rotating of the secrets did not help, or at least if I try to log in I get the same problem as 10 hours ago.

**Comment by poti1** [comment]
Anything we can do to help?
I read in the comments about OAuth. Do we need someone who is familiar with the github API and OAuth specifics?

**Comment by oalders** [comment]
> Do we need someone who is familiar with the github API and OAuth specifics?

That certainly wouldn't hurt, but the issue may be somewhere deep in the application logic or possibly in load balancing/Fastly config.

The first thing would be if someone could fire up the developer environment and find a way to reliably replicate this problem. The auth has been funky pretty much right from the beginning, at least with PAUSE. The GitHub issues seem to be more recent.

The dev env is at https://github.com/metacpan/metacpan-docker  The production env doesn't (yet) use Docker, but this is probably the easiest way to get a close approximation of what is currently running.

Yes, we absolutely could use some help here. 😃

**Comment by oalders** [comment]
Also, if you run into a problem starting via `docker-compose`, this could to get up and running:

```diff
git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index 6ddb536..7efe394 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -74,11 +74,11 @@ services:
       - type: bind
         source: ./configs/metacpan-web/metacpan_web_local.conf
         target: /metacpan-web/metacpan_web_local.conf
-        read_only: true
+        #read_only: true
       - type: bind
         source: ./src/metacpan-web
         target: /metacpan-web
-        read_only: true
+        #read_only: true
     ports:
       - "5001:5001"
     networks:
```

**Comment by AlexP007** [comment]
want to mention that authentication via google works. It was my personal solution =)

**Comment by poti1** [comment]
Metacpan is done?

**Comment by poti1** [comment]
I mean down?

**Comment by voegelas** [comment]
The request `GET "https://api.github.com/user?access_token=$token"` returns the error code 400 Bad Request. If the token is passed in the Authorization header as described in GitHub's document [Authorizing OAuth Apps](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps) the request succeeds and `$extra->{id}` will be defined.

```patch
--- a/lib/MetaCPAN/Server/Controller/Login/GitHub.pm
+++ b/lib/MetaCPAN/Server/Controller/Login/GitHub.pm
@@ -33,7 +33,9 @@ sub index : Path {
             unless ($token);
         $token =~ s/&.*$//;
         my $extra_res = $ua->request(
-            GET "https://api.github.com/user?access_token=$token" );
+            GET 'https://api.github.com/user',
+            authorization => "token $token"
+        );
         my $extra = eval { decode_json( $extra_res->content ) } || {};
         $self->update_user( $c, github => $extra->{id}, $extra );
     }
```

I'm not sure whether that is everything that needs to be fixed with regard to GitHub. My dev env redirects me to http://localhost:5000/user, which is an empty JSON document.

**Comment by oalders** [comment]
@voegelas I think the empty JSON document is a different issue, possibly an issue around when cookies are being set. If you'd like to submit the above patch, we can deploy it and test it out.

**Comment by oalders** [comment]
This looks to have fixed it for me. I had a machine where I couldn't authenticate, but now it works again.

**Comment by poti1** [comment]
This appears to also be working for me. Thanks for the rapid response and
swift solution. Basically we were just missing the Authorization field.

**Comment by poizon** [comment]
Cool! Now it works
