### ISSUE TITLE
authprotocol | SHA256 support in Net::SNMP

### ISSUE THREAD

**Issue by SameerGho** [metacpan/metacpan-web#2599]
https://metacpan.org/pod/Net::SNMP#2.-Blocking-SNMPv3-set-request-of-sysContact
=====================
Two different hash algorithms are defined by SNMPv3 which can be used by the Security Model for authentication. These algorithms are HMAC-MD5-96 "MD5" (RFC 1321) and HMAC-SHA-96 "SHA-1" (NIST FIPS PUB 180-1). The default algorithm used by the module is HMAC-MD5-96. This behavior can be changed by using the -authprotocol argument. This argument expects either the string 'md5' or 'sha' to be passed to modify the hash algorithm.
=====================
Can get SHA256 support in Net::SNMP perl module

**Comment by haarg** [comment]
This is the issue tracker for the metacpan website, which is just a search and documentation viewer for CPAN modules. It is not responsible for the modules themselves.

The issue tracker for Net::SNMP can be found at https://rt.cpan.org/Dist/Display.html?Name=Net-SNMP
