### ISSUE TITLE
Auth::Kokolores Perl Module

### ISSUE THREAD

**Issue by Abatjour3407** [metacpan/metacpan-web#2600]
Hi, just got a new CentOS server and I am trying to duplicate all the settings from my old server across to this one. It has a Perl Module called Auth::Kokolores and I'm trying to install it via the WHM. I cannot find it listed under the available Perl modules. Googling it led me to https://github.com/benningm/kokolores.git but this page link is broken. Please assist. Thanks.

**Comment by Grinnz** [comment]
It's been deleted from CPAN but you can download it manually or with cpanm from backpan. The latest release appears to be https://metacpan.org/release/BENNING/Auth-Kokolores-1.01.
