### ISSUE TITLE
Cannot find activity mail

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-web#2629]
[Search](https://metacpan.org/search?size=20&q=activitymail).

activitymail uses the PAUSE subdirectory feature and was a script rather than a module, but it used to appear on search.cpan.org. You can see it [here](https://www.cpan.org/modules/by-authors/id/D/DW/DWHEELER/activitymail/). Maybe the script feature isn't supported?

**Comment by theory** [comment]
Found it [on MetaCPAN[(https://metacpan.org/release/DWHEELER/activitymail-1.26/view/bin/activitymail), but sadly https://metacpan.org/pod/activitymail does not work, either.

**Comment by Grinnz** [comment]
The script feature is not supported. Additionally, only releases which contain an indexable *module* will show up in search.

**Comment by Grinnz** [comment]
See https://github.com/andk/pause/blob/master/doc/operating-model.md#35-factors-considering-in-the-indexing-phase for the PAUSE component of whether a release gets indexed, which is a factor in whether it will get indexed for metacpan search.

**Comment by theory** [comment]
Okay, as long as the project is aware of it. I don't expect ever to release a another script this way, just was fixing obsolete links on my blog.
