### ISSUE TITLE
uploads not being properly indexed?

### ISSUE THREAD

**Issue by djerius** [metacpan/metacpan-web#2643]
Hi folks,

Random bits of a distribution I uploaded yesterday (https://metacpan.org/release/DJERIUS/Data-Record-Serialize-0.33-TRIAL)

are returning a 

> The resource you requested could not be found.

error page.  Here's a couple of links which currently do that:

https://metacpan.org/release/DJERIUS/Data-Record-Serialize-0.33-TRIAL/view/lib/Data/Record/Serialize.pm

https://metacpan.org/release/DJERIUS/Data-Record-Serialize-0.33-TRIAL/source

But this one works:

https://metacpan.org/release/DJERIUS/Data-Record-Serialize-0.33-TRIAL/view/lib/Data/Record/Serialize/Encode/ddump.pm

Thanks for your efforts!
Diab

**Comment by atoomic** [comment]
similar issue with Test-MockFile-0.025.tar.gz
this file is not available whereas it s on pause

broken:
https://cpan.metacpan.org/authors/id/T/TO/TODDR/Test-MockFile-0.025.tar.gz

working:
http://httpupdate.cpanel.net/CPAN/authors/id/T/TO/TODDR/Test-MockFile-0.025.tar.gz

**Comment by zmughal** [comment]
I can confirm that tarballs on `https://cpan.metacpan.org` currently give a 404 for uploads after SPVM-0.9129.

**Comment by zmughal** [comment]
The mirror is now updated per <http://mirrors.cpan.org/> so this looks fixed.
