### ISSUE TITLE
Simple search pratically returns nothing useful

### ISSUE THREAD

**Issue by florian-pe** [metacpan/metacpan-web#2644]
I searched for the keyword "SDL2" and got only 4 results, with only 1 in the SDL2 namespace while there are in fact dozens.

Here is my search url:
https://metacpan.org/search?q=SDL2

and here's what should be listed in the search result but doesn't
https://metacpan.org/dist/SDL2-FFI

**Comment by Grinnz** [comment]
The results are modules, not distributions; the first result is a module in the distribution you mention, at least for me.

**Comment by oalders** [comment]
Thanks @florian-pe. This is the kind of thing that could be tracked at #1231
