### ISSUE TITLE
Metacpan.org - Error 503 No healthy backends

### ISSUE THREAD

**Issue by MartinMcGrath** [metacpan/metacpan-web#2651]
The site seems to be experiencing issues responding to anything besides requests for static content.

**Comment by MartinMcGrath** [comment]
> Appears to have resolved now thankfully. I wonder what had been wrong?

I suspect an issue between caching and backend workers.

**Comment by oalders** [comment]
Thanks everyone! Looks to be resolved for the time being.

**Comment by MartinMcGrath** [comment]
Thanks @oalders

**Comment by oalders** [comment]
Kudos to @haarg for getting things back up and running. 😄
