### ISSUE TITLE
ability to redirect uses away from filing bug reports through cpan

### ISSUE THREAD

**Issue by jayenashar** [metacpan/metacpan-web#2654]
https://rt.cpan.org/Transaction/Display.html?id=2197790

> The maintainers prefer that issues for F::Q get reported at https://github.com/finance-quote/finance-quote instead of cpan.org. 

is there any way for them to set this up?

cc @bpschuck

**Comment by oalders** [comment]
I think you'll want to change this line: https://github.com/finance-quote/finance-quote/blob/master/dist.ini#L89

**Comment by jayenashar** [comment]
Thanks so much.

https://github.com/finance-quote/finance-quote/pull/201
