### ISSUE TITLE
RoadMap - how things are going till 8.x?!?

### ISSUE THREAD

**Issue by jenswitzel** [metacpan/metacpan-web#2656]
Dear Enrico, dear Team

we're actually running ES CPAN module 7.715 against our local ES 7.16 Server and all is fine :-D Thx again for your brilliant job!

My question is about the readmap: what are your plans for version 8. Will there be updates in the 7th-universe or are you waiting for ES8?!

Kind regards
 Jens

**Comment by oalders** [comment]
Hi Jens,

This bug tracker is for MetaCPAN. I think you'll get better feedback if you open this issue at https://github.com/elastic/elasticsearch-perl

All the best,

Olaf
