### ISSUE TITLE
$source eq $browse?

### ISSUE THREAD

**Issue by hvds** [metacpan/metacpan-web#2659]
For the first time today I hit an example at https://metacpan.org/pod/Math::MPFR where the links for "source" and for "browse" are the same (https://metacpan.org/dist/Math-MPFR/source/MPFR.pm) and so are the corresponding raw links (https://metacpan.org/dist/Math-MPFR/source/MPFR.pm?raw=1). Not sure if there's a bug here, or if there's something about this distro that makes that for some reason the correct thing to do.

I usually hit browse-raw when I want to navigate to something like a test file (usually to follow up on a blead-breaks-CPAN ticket), so it's a lot more useful to me when it links to a directory display.

**Comment by oalders** [comment]
Thanks for reporting @hvds!

**Comment by hvds** [comment]
Thanks, that one works for me now. But the next one I tried failed differently: https://metacpan.org/pod/Convert::Number::Roman points me to https://metacpan.org/dist/Convert-Number-Roman/sourcelib/Convert/Number/ which does not exist, and appears to be missing a '/'.

Let me know if you'd prefer me to open a separate issue for this.

**Comment by hvds** [comment]
@haarg The 'browse' link at https://metacpan.org/pod/Convert::Number::Roman now appears to be fixed, but the 'browse (raw)' link is still missing a '/'.
