### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by freonpsandoz** [metacpan/metacpan-web#2662]
The link to ["EXAMPLES" in Win32::OLE](https://metacpan.org/pod/Win32::OLE#EXAMPLES) on the page https://metacpan.org/pod/Win32::OLE::Variant is not found.

**Comment by Grinnz** [comment]
The link works for me, it goes to https://metacpan.org/pod/Win32::OLE#EXAMPLES. Also, broken links in POD are an issue with the distribution, not MetaCPAN.

**Comment by mickeyn** [comment]
As Dan mentioned, this is not a MetaCPAN issue.
