### ISSUE TITLE
broken generated links pointing to man.he.net

### ISSUE THREAD

**Issue by peterdd** [metacpan/metacpan-web#2664]
It looks like POD-links like Modulename(3) generates bad links.

For instance, on https://metacpan.org/pod/Data::Serializer the links for Data::Dumper(3) are generated as 

http://man.he.net/man3/Data::Dumper which is broken.

Instead the link should go to https://metacpan.org/pod/Data::Dumper ?

**Comment by haarg** [comment]
Quoting [perlpodspec](https://perldoc.perl.org/perlpodspec):
> At time of writing, L<name> values are of two types: either the name of a Pod page like L<Foo::Bar> (which might be a real Perl module or program in an @INC / PATH directory, or a .pod file in those places); or the name of a Unix man page, like L<crontab(5)>. In theory, L<chmod> is ambiguous between a Pod page called "chmod", or the Unix man page "chmod" (in whatever man-section). However, the presence of a string in parens, as in "crontab(5)", is sufficient to signal that what is being discussed is not a Pod page, and so is presumably a Unix man page. The distinction is of no importance to many Pod processors, but some processors that render to hypertext formats may need to distinguish them in order to know how to render a given L<foo> code.

A link that includes a `(3)` is interpreted as a Unix man page, so linking to a page like man.he.net is appropriate. Data::Serializer's pod is written incorrectly.
