### ISSUE TITLE
Searche software about RegRipper for forense - 

### ISSUE THREAD

**Issue by sec-fei** [metacpan/metacpan-web#2666]
Hello,

I try searching software that was install/uninstall for forensic analysis.

I used this command:
./rip.pl.linux -r /mnt/imagem_forense/Windows/System32/config/SYSTEM -p uninstall 

But appear this result without:
Uninstall
Use of uninitialized value $bytes_read in numeric ne (!=) at /usr/share/perl5/Parse/Win32Registry/WinNT/Key.pm line 279.

I was waiting for the result of the software that was found.

**Comment by haarg** [comment]
This is the issue for the MetaCPAN web site. The issue tracker for Parse-Win32Registry is at https://rt.cpan.org/Dist/Display.html?Name=Parse-Win32Registry
