### ISSUE TITLE
id of Anchor is wrong

### ISSUE THREAD

**Issue by yuki-kimoto** [metacpan/metacpan-web#2668]
The id of anchor is wrong when there are multiple head names that start with the same string.

```
=head1 Method Names

Method Names.

=head1 Method

Method.

=head2 Method Definition

Method Definition.

L<"Method">

```

L<"Method"> want to jump to "=head1 Method", but it jumps to "=head1 Method Names".

<a href="https://metacpan.org/pod2html">Pod Renderer</a> renders the following HTML.

```
<h1 id="Method-Names"><a href="#Method-Names" class="anchor"><span class="fa fa-bookmark black"></span></a><a id="Method"></a>Method Names</h1>

<p>Method Names.</p>

<h1 id="Method1"><a href="#Method1" class="anchor"><span class="fa fa-bookmark black"></span></a>Method</h1>

<p>Method.</p>

<h2 id="Method-Definition"><a href="#Method-Definition" class="anchor"><span class="fa fa-bookmark black"></span></a><a id="Method2"></a>Method Definition</h2>

<p>Method Definition.</p>

<p><a href="#Method">"Method"</a></p></div>

```

Is this bug or spec?

**Comment by yuki-kimoto** [comment]
> This can be discussed in https://metacpan.org/dist/MetaCPAN-Pod-XHTML if necessary, as this behavior is controlled by those roles.

I want to discuss this because I feel this behavior is a little strange.

**Comment by oalders** [comment]
Am closing as discussion has moved to MetaCPAN-Pod-XHTML.
