### ISSUE TITLE
Missed files at repository: Makefile.PL, INSTALL

### ISSUE THREAD

**Issue by KES777** [metacpan/metacpan-web#2671]
I can find those files on metacpan, but they does not exists at repository

**Comment by haarg** [comment]
This is the issue tracker for the MetaCPAN website. Did you mean to post this elsewhere?

Many distributions generate files like Makefile.PL and INSTALL at release time, and don't include them in their git repo. This is often done using Dist::Zilla, with the generation of those files and other parts of the release process controlled by a `dist.ini` file.

**Comment by KES777** [comment]
Ouch. Sorry. I did not noticed that that link does not refer to Dancer.

![image](https://user-images.githubusercontent.com/799021/165166430-9f79e8ce-7ffd-41c4-9e3e-7cee712aea11.png)

PS. I have checkout Dancer repo and did not find better way as `wget Makefile.PL` manually =)
