### ISSUE TITLE
d-link DGS-1510-28 stack does not discover as a stack

### ISSUE THREAD

**Issue by atretyakov** [metacpan/metacpan-web#2679]
An attempt to discover the stack of 6 switches D-Link DGS-1510-28 was unsuccessful. What to do? Discovery log attached
[netdisco.log](https://github.com/metacpan/metacpan-web/files/8669603/netdisco.log)
.

**Comment by haarg** [comment]
This is the issue tracker for the MetaCPAN web site. You may be looking for the issue tracker for the App::Netdisco module: https://github.com/netdisco/netdisco/issues
