### ISSUE TITLE
SPVM repository is removed on metaCPAN

### ISSUE THREAD

**Issue by yuki-kimoto** [metacpan/metacpan-web#2688]
I have a trouble.

Today, I find SPVM module is removed on metaCAPN.

https://metacpan.org/pod/SPVM

The works I do today is uploading SPVM::Unicode and SPVM::Regex.

https://metacpan.org/pod/SPVM::Regex

https://metacpan.org/pod/SPVM::Unicode

It seems that the above modules are uploaded, SPVM is removed on metaCPAN.

Is it possible to search for the reason?

I try to upload the new version of SPVM.

**Comment by yuki-kimoto** [comment]
Duplication of SPVM::Regex and SPVM::Unicode in SPVM distribution?

**Comment by Grinnz** [comment]
I don't see any obvious issues. The separate distributions contain modules with higher versions so were correctly indexed for those modules, which should not affect any of the other modules in the SPVM distribution, and indeed the modules are still correctly indexed to that distribution in PAUSE: https://cpanmeta.grinnz.com/packages?module=SPVM&match_mode=prefix

**Comment by Grinnz** [comment]
SPVM seems searchable and viewable for me now, but isn't showing as latest. Caching error?

**Comment by yuki-kimoto** [comment]
Thank you very much. Maybe caching error. I can see SPVM page now.
