### ISSUE TITLE
perlapi is messed up

### ISSUE THREAD

**Issue by monken** [metacpan/metacpan-web#27]
http://beta.metacpan.org/module/perlapi

The full pod is generated as part of the `make all` process. Not sure if/how we should support that.

**Comment by salva** [comment]
Being `perlapi` part of the `perl` distribution, it well deserves an special treatment.

**Comment by haarg** [comment]
Special casing this would involve a rather significant amount of work.  metacpan currently takes everything from the files uploaded to CPAN.  We don't have anywhere in our navigation or URL schemes for generated files like this.  We would also need a new storage location to store the files.  And of course, a process for generating the files when new releases are made.

Are there other generated files in the perl dist that would benefit from special handling?  I'm not sure the work involved would be justified for just this one file.

**Comment by choroba** [comment]
For perlapi, we could link to http://perldoc.perl.org/perlapi.html at least. What's shown currently is a garbage.
