### ISSUE TITLE
Recent page has a module's abstract "Do not pass capture variables as arguments" instead of the actual abstract

### ISSUE THREAD

**Issue by robrwo** [metacpan/metacpan-web#2704]
The recent page shows [Perl::Critic::Policy::ValuesAndExpressions::ProhibitFiletest_rwxRWX](https://metacpan.org/pod/Perl::Critic::Policy::ValuesAndExpressions::ProhibitFiletest_rwxRWX) with an abstract:
> Do not pass capture variables as arguments

But the actual abstract is "Prohibit file access test". A grep for "Do not pass capture variables as arguments" shows nothing.  This seems like a bug somewhere.

Screenshot attached:
![Screenshot 2022-06-30 at 14-45-09 Recent - metacpan org](https://user-images.githubusercontent.com/294409/176693757-2e84af9f-2eaf-4a34-aaaf-d5de8471fc99.png)

**Comment by ilmari** [comment]
That is the `abstract` in [META.json](https://metacpan.org/release/WYANT/Perl-Critic-Policy-ValuesAndExpressions-ProhibitFiletest_rwxRWX-0.001/source/META.json), which appears to come from [`My::Module::Meta`](https://metacpan.org/release/WYANT/Perl-Critic-Policy-ValuesAndExpressions-ProhibitFiletest_rwxRWX-0.001/source/inc/My/Module/Meta.pm#L21).

**Comment by robrwo** [comment]
So this is a problem with that distribution, not MetaCPAN.
