### ISSUE TITLE
Would like secret_command field made available in config file for App-wsgetmail

### ISSUE THREAD

**Issue by H20-17** [metacpan/metacpan-web#2719]
**Describe the feature**
Want a secret_command field in json config file for App-wsgetmail

**Which problem does it solve?**

The config files will not have to be set so they are not readable by all users (not a big deal), but more importantly,
secrets change periodically, and we won't have to modify the config file every time that happens. (We may have to
modify something else but we shouldn't have to modify a config file when a secret changes)
Also if the secret is shared between accounts (it is in my case), we have to change multiple files when the secret changes.

**Expected behavior**
Want to see a "secret_command" field that we can use instead of the "secret" field. For reference see getmail6 and how they have implemented their "password_command" field.

**Volunteering**
I don't have time for this at the moment.

**Comment by Grinnz** [comment]
This is the issue tracker for the metacpan web site. Use the "Issues" link on the left sidebar of the module to find the issue tracker for a particular distribution. For App-wsgetmail that is https://rt.cpan.org/Public/Dist/Display.html?Name=App-wsgetmail
