### ISSUE TITLE
Trying to build on MacOS 12.5.1

### ISSUE THREAD

**Issue by davehodg** [metacpan/metacpan-web#2735]
The system reports that sqlplus cannot be run because:

![image](https://user-images.githubusercontent.com/922517/188904632-e5c5080f-b99e-4002-b55c-074617e57b0c.png)

Also, the Mac documentation needs to be brought up to date.

**Comment by oalders** [comment]
@davehodg this is the MetaCPAN bug tracker. Which dist are you looking for?

**Comment by davehodg** [comment]
I clicked on a link from DBD::Oracle. Never mind, I'll fix it.

**Comment by oalders** [comment]
When you created this ticket, you should have been presented with a bug issue template which reads:

> This issue tracker is for bugs in the https://metacpan.org web site. If you are are reporting a bug about anything else, this is most likely not the correct venue. Please use the left side menu for the module you are interested in and click the `Issues` link in order to find the bug tracker for your module.

I'm just wondering if you saw this when creating the report? I'm trying to find a way to prevent CPAN bug reports getting opened here. Just wondering if you saw that template or if something in there could be worded more clearly.

**Comment by davehodg** [comment]
I probably just glossed over it. My fault. I'm up to my eyeballs in Oracle right now so not necessarily paying attention.
