### ISSUE TITLE
Sidebar is empty on "all releases page"

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#2749]
Here's an example: https://metacpan.org/author/OALDERS/releases?size=500

<img width="1565" alt="Screen Shot 2022-09-29 at 15 14 55" src="https://user-images.githubusercontent.com/96205/193122190-0f4e6a24-cb52-47db-b096-abdf80c770d6.png">

**Comment by dhogan8** [comment]
@oalders Thanks! Do you know if the sidebar was always empty for this page? I'm trying to understand if the PR deleted something that was previously there or if it is desired to have something on that sidebar for this specific page.

**Comment by oalders** [comment]
That's a good question @dhogan8. I checked out an earlier commit and it looks like this:

<img width="1569" alt="Screen Shot 2022-09-29 at 16 14 43" src="https://user-images.githubusercontent.com/96205/193132996-c1b1f1ca-a303-4130-b742-e89c985c5bf0.png">

Now I realize why I was confused. I think in this case, it's ok not to have a sidebar, especially for authors who have a list of releases with really long names or abstracts.

**Comment by dhogan8** [comment]
Okay yeah that was on my undocumented list of things to update: Figure out a template that works for pages that don't have or need a sidebar. Like the following:
<img width="1272" alt="Screen Shot 2022-09-29 at 4 19 35 PM" src="https://user-images.githubusercontent.com/52248962/193133692-cfc73517-df0e-43d8-b85e-dbb77c67c9c0.png">

**Comment by dstar8** [comment]
@oalders How do the following look to you?
<img width="1511" alt="Screen Shot 2022-09-29 at 7 02 45 PM" src="https://user-images.githubusercontent.com/29670143/193157095-69f09fe2-4f3e-43e7-8df7-2f6ac151ef7b.png">
<img width="1511" alt="Screen Shot 2022-09-29 at 7 02 16 PM" src="https://user-images.githubusercontent.com/29670143/193157099-57a6b58e-22d7-4026-b3fb-0b8b48203294.png">

**Comment by dhogan8** [comment]
@oalders How do the following look to you?
<img width="1511" alt="Screen Shot 2022-09-29 at 7 02 45 PM" src="https://user-images.githubusercontent.com/29670143/193157095-69f09fe2-4f3e-43e7-8df7-2f6ac151ef7b.png">
<img width="1511" alt="Screen Shot 2022-09-29 at 7 02 16 PM" src="https://user-images.githubusercontent.com/29670143/193157099-57a6b58e-22d7-4026-b3fb-0b8b48203294.png">
<img width="1511" alt="Screen Shot 2022-09-29 at 7 05 42 PM" src="https://user-images.githubusercontent.com/29670143/193157393-1cf410d5-7463-4422-a47a-4740c5328696.png">

**Comment by oalders** [comment]
Wonderful!

**Comment by dhogan8** [comment]
@oalders I think this was resolved in https://github.com/metacpan/metacpan-web/pull/2759.
