### ISSUE TITLE
Header positions move during page load

### ISSUE THREAD

**Issue by haarg** [metacpan/metacpan-web#2752]
Various elements of the header move from their initial position after the login check is done, and the user account button in the upper right corner is displayed. This is visually distracting.

Possibly the some elements should be adjusted so that when it is shown, the position doesn't change. Alternatively, it might make more sense to always have the button visible, just not usable or with any content until after the login check.

**Comment by dhogan8** [comment]
@haarg I was able to fix this while working on https://github.com/metacpan/metacpan-web/pull/2759. The icon for being logged in wasn't exactly aligned with the other icons which was causing the weird offset.

**Comment by dhogan8** [comment]
@haarg Is this what you mean when you suggest the following?
> Alternatively, it might make more sense to always have the button visible, just not usable or with any content until after the login check.

https://user-images.githubusercontent.com/52248962/193422691-87cc258a-9910-4660-81c8-b41bc1ea46b5.mov

**Comment by dhogan8** [comment]
@oalders @haarg I think this has been resolved in https://github.com/metacpan/metacpan-web/pull/2759
