### ISSUE TITLE
Matrix icon is still in sidebar

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#2756]
All other icons appear to be gone, but the matrix has been overlooked.

<img width="336" alt="Screen Shot 2022-09-30 at 13 25 36" src="https://user-images.githubusercontent.com/96205/193324345-c762db55-fe4e-4e7c-ab41-671890c2db1c.png">

**Comment by dhogan8** [comment]
Clicking this icon takes a user to http://matrix.cpantesters.org/?author=[author_name]. Should the icon be removed and converted to a link instead between CPANTesters Reports and CPANTS? 

- CPANTesters Reports
- CPANTesters Matrix
- CPANTS

**Comment by oalders** [comment]
Ah, right. There was a reason for that. I always just click on the matrix icon and had forgotten the link went to a different place. We should get some feedback from someone who isn't me. 😄

**Comment by openstrike** [comment]
It could be a separate menu item as proposed but honestly, what's wrong with the icon as it stands?

**Comment by oalders** [comment]
> what's wrong with the icon as it stands?

I think it makes sense to keep it.
