### ISSUE TITLE
Can't connect my Pause ID

### ISSUE THREAD

**Issue by dhogan8** [metacpan/metacpan-web#2758]
**Describe the bug**
When I submit the form at https://metacpan.org/login/pause, 
<img width="1212" alt="Screen Shot 2022-10-01 at 9 21 56 AM" src="https://user-images.githubusercontent.com/52248962/193411582-6bd6faf6-54a5-4def-b0e2-5a680fd3491f.png">

it redirects me to http://localhost:5001/login?success=mail_sent rather than https://metacpan.org/login?success=mail_sent and no email gets sent to my email.
<img width="1136" alt="Screen Shot 2022-10-01 at 9 24 12 AM" src="https://user-images.githubusercontent.com/52248962/193411642-d281c325-5b93-421b-8046-af48602e96b3.png">

In the meantime, is there another way to connect my Pause ID?

**Comment by oalders** [comment]
I think this one may take a bit of time to sort out. We don't have a great way of manually connecting a PAUSE id right now. ☹️

**Comment by dhogan8** [comment]
I was finally able to connect it but it seems like I need to reconnect it a few times a day. 

Another odd issue I run into is I'll see this on a desktop (Chrome):
<img width="952" alt="Screen Shot 2022-10-05 at 9 32 32 AM" src="https://user-images.githubusercontent.com/52248962/194073061-f3b52563-cee8-43b1-ac00-85a840729365.png">

But then I'll see this on mobile (Safari), which indicates my Pause ID is indeed connected:

![MetaCPAN Account - metacpan org](https://user-images.githubusercontent.com/52248962/194073981-97788094-f9c1-47c5-b1a8-ad8445ff3f2e.jpeg)

**Comment by bmeneg** [comment]
I'm currently facing somewhat the same issue: some time ago I created my MetaCPAN user but I didn't have a PAUSE account at the time, few hours ago I got it and decided to link it in MetaCPAN's profile, I received the email that moved me back to MetaCPAN home page, but when I try to access my profile, I receive the very same message about connecting my account to a PAUSE account.

> We should check to make sure you don't have two different accounts. ;)

That's indeed a possibility. I was able to access, a single time, my MetaCPAN profile with connected PAUSE account, changed my image on gravatar, added my GitHub, ... profiles and whatnot, but when I logged out, what I described previously started to happen.

**Comment by bmeneg** [comment]
Ah, ok.. found something: entering in `MetaCPAN > "user image" > Identities` lead me to these options:

![image](https://github.com/metacpan/metacpan-web/assets/453611/be652510-c7be-4e53-9701-3a50fa5a625d)

But, if I click to connect PAUSE it redirects me to the page where I need to input my PAUSE ID (`Connect to MetaCPAN using PAUSE`), then I'm redirected to MetaCPAN home page, but this time I'm logged in as another MetaCPAN user, which has the PAUSE account connected:

![image](https://github.com/metacpan/metacpan-web/assets/453611/a0bb9215-c1b4-4e05-9dcb-7619d7598035)

But as is stated into MetaCPAN, PAUSE ID isn't used for logging in, so when I logout from this MetaCPAN user with PAUSE ID connected, I have no other way to log in if not following the process I mentioned (using GitHub or Google account leads me to the first account without PAUSE ID connected).

**Comment by oalders** [comment]
This has been an ongoing, frustrating bug that is the stuff of nightmares.

We do address it to some extent here: https://metacpan.org/about/faq#connectingoneidentitydisconnectsanother

Have you tried (and I hate asking) clearing out your cookies? I do believe there is something funky related to cookies and the interaction between the front and back end.

**Comment by bmeneg** [comment]
Ahh.. ok, cookies were messing things up for sure.
I disconnected my MetaCPAN user connected to PAUSE ID from PAUSE, logged in with my GitHub/Google account in a browser private sessions and connected tried to connect PAUSE, finally I got everything connected in a single account:

![image](https://github.com/metacpan/metacpan-web/assets/453611/19606987-6b16-462b-ae19-e83385d36ca2)

Many thanks @oalders !

**Comment by oalders** [comment]
I think this one can be closed.
