### ISSUE TITLE
Error 503 No healthy backends

### ISSUE THREAD

**Issue by MartinMcGrath** [metacpan/metacpan-web#2764]
**Describe the bug**
Varnish cache server - No healthy backends

**To Reproduce**
1. Go to 'metacpan.org'
2. Perform a search
3. See error

**Expected behavior**

Search results should be displayed

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 105.0.1

**Comment by haarg** [comment]
This should be resolved for now. Some of the services decided to take a vacation.
