### ISSUE TITLE
Logged in drop-down never appears

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2768]
**Describe the bug**
When logged in to MetaCPAN the dropdown menu from the avatar in the very top right never appears. Clicking on the avatar toggles the `aria-expanded` value on the button and the class on the enclosing `li` but the actual menu items never show.

**To Reproduce**
1. Login to MetaCPAN
2. Visit any page, eg https://metacpan.org/pod/Pepper
3. Click on your avatar in the top right
4. ... nothing visible happens

**Expected behavior**
The drop-down menu should appear on one click and disappear on the next click.

**Screenshots**
![metacpan-no-menu](https://user-images.githubusercontent.com/4331674/194050822-86f577f3-8692-48e6-90bd-a153861839be.png)

**Desktop (please complete the following information):**
 - OS: Linux 64bit
 - Browser Firefox 105.0.1 and Palemoon 31.3.0.1

**Comment by haarg** [comment]
Fixed by #2769
