### ISSUE TITLE
Module dependencies list blends in with dependency tools

### ISSUE THREAD

**Issue by bbrtj** [metacpan/metacpan-web#2777]
**Describe the bug**
Dependency list, previously easily distinguishable, is now followed immediately with dependency tools links (starting with "Reverse dependencies").

**To Reproduce**
Visible on every module's page, desktop and mobile.

**Expected behavior**
I marked with two colors: blue (dependencies) and red (tools). I would expect these to at least be separated by a vertical whitespace.

![image](https://user-images.githubusercontent.com/44323413/194530796-197fc11b-efa2-427b-818f-50537172303e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Mozilla Firefox
 - Version: 105.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14
 - Browser: Opera

**Comment by haarg** [comment]
That looks good to me as a quick solution.

**Comment by dhogan8** [comment]
Added in https://github.com/metacpan/metacpan-web/pull/2778
