### ISSUE TITLE
multiple levels of indentation not handled

### ISSUE THREAD

**Issue by karenetheridge** [metacpan/metacpan-web#2788]
Multiple levels of `=over 4` are not visible in the site redesign -- everything appears at the same level, so it's impossible to tell what content is meant to be nested.

example: https://metacpan.org/pod/Net::IDN::Encode -- there is a list of functions, and inside the function description is a list of options, but the options are shown at the same level as the functions themselves.

**Comment by haarg** [comment]
Old design:
![Screen Shot 2022-10-17 at 11 09 34](https://user-images.githubusercontent.com/50029/196137989-bb150ce3-82e1-4e10-a199-cc7d9acc8b3c.png)
New design:
![Screen Shot 2022-10-17 at 11 09 36](https://user-images.githubusercontent.com/50029/196138002-8350d251-3796-4d67-9476-6d42d9e1adc1.png)

**Comment by nrdvana** [comment]
I'll second this.  While the amount of indentation is an opinion, the readability of nested information and distinguishing the end of a list from the content that follows it is a real problem.

Current:

![image](https://user-images.githubusercontent.com/3742953/200394402-05632a07-d106-4a55-8756-e7fb027152b6.png)

With ```dd { margin-left: 1.5em; }``` :

![image](https://user-images.githubusercontent.com/3742953/200395205-8b1683ea-9169-4e8c-93fe-67c39a35d673.png)

I'm going to guess that ```dd``` got a left margin of 0 for some other reason, such as in a menu or something?  So maybe a fix could be:

    .page-pod .content dd { margin-left: 1.5em; }

Would you accept a patch for that?

**Comment by nrdvana** [comment]
Another example, for just a single level of indent where the visual indication of the end of the list got lost:

![image](https://user-images.githubusercontent.com/3742953/200400962-d7ae7eb3-33e4-47f2-b112-a0fc8b81b12f.png)

It's much easier to see that the content resumes after the list if the list is indented:

![image](https://user-images.githubusercontent.com/3742953/200401334-4d372ff4-5db9-4db3-a0ea-05d41f3cec43.png)

**Comment by oalders** [comment]
@dhogan8 ^^

**Comment by haarg** [comment]
Should be fixed by #2813.
