### ISSUE TITLE
No search form or button in header on palemoon

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2846]
**Describe the bug**
The search form is missing from the page headers when viewed in Palemoon. There is no search button either. Both are styled out with `display: none !important`

**To Reproduce**
1. Fire up palemoon and go to any page with the usual header, eg. https://metacpan.org/release/JDHEDDEN/threads-shared-1.59/source/Changes
2. Look at the header
3. Be surprised to find no search form

**Expected behavior**
Either the search form or the search button should be present. For now the only way to perform a module/dist/author search is to return to the home page.

**Screenshots**
![image](https://user-images.githubusercontent.com/4331674/207044820-bb30da37-72fc-4434-bac2-8d5b02bc555d.png)

I expect the search form to appear between the "API" link and the user icon.

**Desktop:**
 - OS: Linux (Slackware 15)
 - Browser Palemoon
 - Version 31.4.1 (64-bit)

**Additional context**
The form renders fine on the same page in Firefox.
The form renders fine in Palemoon if I untick the "display: none !important" in the CSS editor as in the screenshot.
This is a relatively new phenomenon.

**Comment by haarg** [comment]
I just tested on Palemoon 31.4.1 on Windows 11 on ARM64, and wasn't able to reproduce.

Are there any errors listed in the console tab?

**Comment by omega** [comment]
for some reason the `.visible-lg` doesn't trigger. Is your window wide enough in Palemoon? It needs to be at least 1200px wide according to the css:

The screenshot attached is 1075px, but I guess that might have been resized on the way.

<img width="206" alt="image" src="https://user-images.githubusercontent.com/23787/207072289-49f45512-817c-424a-aedf-12f261777e5b.png">

**Comment by openstrike** [comment]
That's it. My window is less than 1200px wide.

If I extend the window to be wider than that and then load the page, the search form shows up (and stays present as the window is subsequently dragged narrower).

**Comment by openstrike** [comment]
Since the initial occurrence and report, I am now unable to reproduce this myself as the search form consistently appears even on less-than-massively-wide windows.

If somebody did something, then thank you. If not, I'll just quietly curse the gremlins.

Either way, I think this issue can now be closed.
