### ISSUE TITLE
PDL::PrimaImage is not searchable

### ISSUE THREAD

**Issue by dk** [metacpan/metacpan-web#2863]
Hello

My PDL::PrimaImage is neither searchable nor is in 02packages.details.txt .

I made the module structure accorting to the recommendation from the PDL guys here https://github.com/PDLPorters/pdl/issues/417 so it seems that it should be there. However for some reason I see that the module URL [1] is in /release, not in /dist . I wonder where the problem could be here?

[1] https://metacpan.org/release/KARASIK/PDL-PrimaImage-1.03

**Comment by oalders** [comment]
What did the email which you got from PAUSE say?

**Comment by mohawk2** [comment]
This dist has, for the first time, a `.pm` file in its `GENERATED/` directory. This appeared to cause some confusion for https://metacpan.org/dist/PDL-Graphics-ColorSpace when that happened, though it now looks all sorted.

I mention this in the hope it's relevant, rather than suggesting it is either a sign of a problem, or a solution to one.

**Comment by dk** [comment]
The following report has been written by the PAUSE namespace indexer.
Please contact [modules@perl.org](mailto:modules@perl.org) if there are any open questions.

  User: KARASIK (Dmitry Karasik)
  Distribution file: PDL-PrimaImage-1.03.tar.gz
  Number of files: 9
  *.pm files: 1
  README: PDL-PrimaImage-1.03/README
  META-File: PDL-PrimaImage-1.03/META.json
  META-Parser: Parse::CPAN::Meta 1.4414
  META-driven index: no
  Timestamp of file: Sat Jan 28 20:02:33 2023 UTC
  Time of this run: Sat Jan 28 20:04:01 2023 UTC

Status of this distro: OK
=========================


The following packages (grouped by status) have been found in the distro:

Status: Successfully indexed
============================

     module : PDL::PrimaImage
     version: undef
     in file: PDL-PrimaImage-1.03/GENERATED/PDL/PrimaImage.pm
     status : indexed

__END__

**Comment by dk** [comment]
Oh well it was an indexing job after all... sorry for the trouble and thank you very much for quick response! Seems to shows up both in searches and the index just fine!
