### ISSUE TITLE
Error accessing very old CPAN test report from 2018

### ISSUE THREAD

**Issue by djerius** [metacpan/metacpan-web#2878]
**Describe the bug**

Accessing

http://www.cpantesters.org/cpan/report/0d14e9bc-61ba-11e8-a9bf-eea0818d84b4

Results in a "server error (development mode)" page with the following leading text:

```
Can't call method "resource" on an undefined value at /home/cpantesters/perl5/lib/perl5/CPAN/Testers/Web/Controller/Legacy.pm line 249.
```

**To Reproduce**

1. Go to 'http://www.cpantesters.org/cpan/report/0d14e9bc-61ba-11e8-a9bf-eea0818d84b4'

**Expected behavior**
I expected to see the CPAN report

**Additional Info**
A zip file of the HTML page and associated files is available here: 

[error.zip.txt](https://github.com/metacpan/metacpan-web/files/10963525/error.zip.txt)

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Firefox
 - Version: 110.0.1 (64-bit)

**Additional context**

**Comment by Grinnz** [comment]
CPANtesters is not managed by metacpan. Unfortunately its a bit difficult to figure out/reach who is responsible for a particular issue, but you can start here: http://cpantesters.org/page/about.html

**Comment by mickeyn** [comment]
Closing this ticket as it's not a MetaCPAN issue.

**Comment by djerius** [comment]
> CPANtesters is not managed by metacpan. Unfortunately its a bit difficult to figure out/reach who is responsible for a particular issue, but you can start here: http://cpantesters.org/page/about.html

OOOPS.  My apologies, I don't know how I managed to confuse the two.
