### ISSUE TITLE
++ seems wrong in search results

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2879]
**Describe the bug**
The ++ count next to modules in the search results appears to be wrong.

**To Reproduce**
1. Go to [https://metacpan.org/](https://metacpan.org/)
2. Type `ExtUtils::MakeMaker` into the box and hit return (do not select from the pop-up list)
3. See the first module listed in the results is indeed ExtUtils::MakeMaker and be surprised that it has no ++es
4. Click through to the module page at [https://metacpan.org/pod/ExtUtils::MakeMaker](https://metacpan.org/pod/ExtUtils::MakeMaker) and see that it actually has 52 ++es as of today.

**Expected behavior**
The count of ++ on the search result page should match that on the module-specific page.

**Screenshots**
Search results page:
![Screenshot_2023-03-15_09-57-13](https://user-images.githubusercontent.com/4331674/225274606-8ad6ce5b-72c6-4521-8bf3-9b6274ac2925.png)

Module specific page:
![Screenshot_2023-03-15_09-57-45](https://user-images.githubusercontent.com/4331674/225274643-974e62db-4858-4c1b-9528-25eabaced0b9.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Pale Moon 32.0.1 64-bit
 - Version 32.0.1 64-bit

**Additional context**
It isn't every module which is affected, so the bug is inconsistent in that regard. I've only noticed it on ExtUtils::MakeMaker today but haven't gone looking for lots of others.

**Comment by surajdubey08** [comment]
Hi @openstrike 
I couldn't reproduce the issue. I followed your exact steps and the issue is not reproduced for me. Please check the screenshots below:

Search result page:
![image](https://user-images.githubusercontent.com/55913511/226417659-7c7baf63-3896-4d9e-8758-3074f1e74ff5.png)

Module specific page:
![image](https://user-images.githubusercontent.com/55913511/226417855-50a8a134-b5ad-4465-af2e-1c199bf5b01c.png)

Please let me know if I'm missing anything.

**Comment by ingydotnet** [comment]
I see no ++ for https://metacpan.org/search?size=500&q=assign

I see 3 ++ for https://metacpan.org/dist/assign/view/lib/assign.pod

**Comment by openstrike** [comment]
Was this silently addressed?

As of today I see consistent ++ figures in the search results and on the module pages for both ExtUtils::MakeMaker and assign.

**Comment by openstrike** [comment]
In the absence of any updates I will close this as either having been a transient effect of some sort or having been fixed without reporting it here. Either way, the problem seems to have disappeared.
