### ISSUE TITLE
Cannot change `City` in profile

### ISSUE THREAD

**Issue by abeltje** [metacpan/metacpan-web#2895]
**Describe the bug**
After logging into meta-cpan and connecting with my PAUSE-ID I try to change the City I live in, but that doesn't get changed

**To Reproduce**
* log in/connect pause-id
* select the `Profile` menu item
* change `City` in the `Location` section of the profile

**Expected behavior**
The city has changed after reselecting the `Profile` menu item

**Desktop (please complete the following information):**
 - OS: MacOS ventura 13.3.1
 - Browser: Opera
 - Version: 97.0.4719.63 (arm64)

**Comment by oalders** [comment]
@abeltje can you try this again and then check the city value in your author profile? You can use https://explorer.metacpan.org/?url=/author/ABELTJE

**Comment by abeltje** [comment]
Looks ok now, Thanks heaps!

**Comment by oalders** [comment]
Thanks! Wonder if we need to purge the cache for the author page when that changes. 🤔
