### ISSUE TITLE
connecting to Meta CPAN via pause strange message

### ISSUE THREAD

**Issue by rkapl123** [metacpan/metacpan-web#2937]
When I try to connect to Meta CPAN via pause (to edit my profile), I get the message:
```
(en) Please come back later
(fr) SVP veuillez revenir plus tard
(de) Bitte versuchen sie es spaeter nocheinmal
(at) Konnten's bitt'schoen spaeter nochmal reinschauen
(no) Vennligst prov igjen senere
(dk) Venligst prov igen senere
(pl) Prosze sprobowac pozniej
(pt) Por favor volte mais tarde
(ru) Попробуйте еще раз позже
(ua) Спробуйте ще раз пізніше
(it) Per favore riprova più tardi
```
I do this after I've logged in to Meta CPAN with my Github account.
I've set up both emails (public and secret) in PAUSE and set forwarding to my secret email address. My PAUSE Account is RKAPL.

-regards,
Roland

**Comment by regcostajr** [comment]
This issue seems to be fixed, I can see the email updated after PAUSE changes, now I'm receiving "Backend is unhealthy" but I believe this is another issue, so I guess this can be closed.
