### ISSUE TITLE
Paging broken on author releases

### ISSUE THREAD

**Issue by nrdvana** [metacpan/metacpan-web#2941]
When browsing "All Releases by AUTHOR", the pager is showing a number of elements equal to the page, instead of the selected number of elements-per-page.

[Page 1, Size 50](https://metacpan.org/author/NERDVANA/releases?size=50) shows only one result, where [Page 15, Size 10](https://metacpan.org/author/NERDVANA/releases?p=15&size=10) shows 15 results.

**Comment by oalders** [comment]
Closing as fixed. Thanks for reporting @nrdvana.
