### ISSUE TITLE
Contributors page spins forever

### ISSUE THREAD

**Issue by openstrike** [metacpan/metacpan-web#2952]
**Describe the bug**

The contributors page at https://metacpan.org/about/contributors has no content in the main pane, just a spinner which goes round and round forever

**To Reproduce**

1. Go to https://metacpan.org/about/contributors
2. See no contributors listed and make yourself dizzy staring at the perpetual spinner.

**Expected behavior**

A list of contributors to this repo ordered by ... lines? commits? Anything is better than an almost blank page.

**Screenshots**

![Screenshot_2023-11-08_18-13-26](https://github.com/metacpan/metacpan-web/assets/4331674/c09b1334-0170-43da-b06a-91dcd1d61286)

**Desktop (please complete the following information):**
 - OS: Linux 64-bit
 - Browser Firefox
 - Version 119.0 (64-bit)

**Comment by openstrike** [comment]
This seems to have been fixed at some point in the last couple of months.

**Comment by haarg** [comment]
#3021 rewrote the contributors page, so it would have fixed this.
