### ISSUE TITLE
Improve recent page with indication of type of release (stable/testing/unstable/cpan)

### ISSUE THREAD

**Issue by michal-josef-spacek** [metacpan/metacpan-web#2954]
**Describe the feature**
Improve recent page https://metacpan.org/recent with information about release type.
I think that could be some icon before the river icon or by the color of the link (same as in the distribution page)

**Which problem does it solve?**
When I look at the recent page there is a mix of secret releases (status => cpan), public releases (status => latest), development releases (meta.release_status => unstable), and testing releases (meta.release_status => testing).
This is not fine for the user.

**Expected behavior**
When I look at the recent page, I can identify releases, that I need.

**Volunteering**
I could implement it.

**Comment by haarg** [comment]
We have an existing convention of using colors to indicate this (on the navigation breadcrumb). Using those colors would probably be the easiest way to implement this. And staying consistent with the other parts of the site would be good.

The colors aren't the best though, and aren't well explained. If we can find a better way to demonstrate the status, it is could be welcome. But it should be something that can be used both on the recent page and the breadcrumb.

**Comment by michal-josef-spacek** [comment]
I have some code for adding CSS styles to the recent page. Seems possible.

The main problem that I have is missing ```$release.maturity``` value in recent.tx page.
I don't see how to fetch this info for now.

**Comment by michal-josef-spacek** [comment]
API was changed to add maturity, I could create PR. Great.

**Comment by michal-josef-spacek** [comment]
@haarg Could you look to it, please? I think it's clear to merge.

**Comment by michal-josef-spacek** [comment]
@haarg  Great, thank you.
