### ISSUE TITLE
Old docs shown for modules in the perl dist

### ISSUE THREAD

**Issue by Smylers** [metacpan/metacpan-web#2960]
**Describe the bug**

When viewing modules provided in the `perl` distribution, a out-of-date version is shown by default, rather than the latest stable released version.

**To Reproduce**

1. From the [homepage](https://metacpan.org/), search for ‘feature’.
2. That will take you to <https://metacpan.org/search?q=feature>. Click on the first result, the link labelled just ‘feature’.
3. That goes to <https://metacpan.org/pod/feature>. See that the module's version number is 1.72 and the distribution it's being rendered from is `perl-5.36.0`.
5. Click the ▼ to the left of the distribution name to open the list of other versions, and see that there are several more recent stable distributions, including 5.38.0 in July and 5.38.2 last week.
6. Look at the Pause index, <https://cpan.metacpan.org/modules/02packages.details.txt>, and search for ‘feature␣␣’ (that's 2 spaces at the end). See that the latest version of `feature` is `1.82` in the dist `P/PE/PEVANS/perl-5.38.2.tar.gz`.

**Expected behavior**

Going to the default page for a module would display its latest stable version, as per either the Pause index or the module contained in the most-recent `perl` release.

This also affects other modules such as [Hash::Util](https://metacpan.org/pod/Hash::Util) (displaying version 0.28; the Pause index has version 0.30 in `perl-5.38.0`), and documentation-only pages such as [perldelta](https://metacpan.org/pod/perldelta) ‒ all seem to be stuck on the `perl-5.36` distribution.

**Desktop:**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 120

**Comment by haarg** [comment]
I force reindexed the latest release, so this should be fixed.
