### ISSUE TITLE
Pod Renderer is not working.

### ISSUE THREAD

**Issue by yuki-kimoto** [metacpan/metacpan-web#2980]
Pod Renderer is not working now.

![image](https://github.com/metacpan/metacpan-web/assets/81858/31313e4b-a6c6-4a78-9de3-41f445ff144c)

**Comment by haarg** [comment]
Fixed by fadb16ccc195bbd6903b36c5fba135273abe559f

**Comment by yuki-kimoto** [comment]
Thank you.
