### ISSUE TITLE
Pod Renderer cannot be accessed. "Error 503 Backend is unhealthy"

### ISSUE THREAD

**Issue by yuki-kimoto** [metacpan/metacpan-web#2994]
Pod Renderer cannot be accessed.

https://metacpan.org/pod2html

![image](https://github.com/metacpan/metacpan-web/assets/81858/ce92ffee-54c8-4bdd-8d0c-207940857e53)

**Comment by a-parser** [comment]
same for other modules and search

**Comment by oalders** [comment]
Thanks. We are working on this.

**Comment by oalders** [comment]
This should be fixed now. Let me know if it isn't.
