### ISSUE TITLE
Fsdb (in pause) doesn't show up as a release in metacpan

### ISSUE THREAD

**Issue by jheidemann** [metacpan/metacpan-web#3000]
**Describe the bug**

I released the Fsdb package in cpan via pause.  It shows up in metacpan, but not as a release.

I expected it to show up as a release, and am uncertain if I'm doing something incompletely, or if metacpan is missing something.

**To Reproduce**
1. check that files exist in pause.  I can do this by loging in to pause.cpan.org and looking at "show my files", which shows in authors/id/J/JO/JOHNH thinks like Fsdb-3.4.tar.gz [indexed].
2. observe that metacpan knows about Fsdb, since  https://metacpan.org/pod/Fsdb has stuff
3.  use the API to check for releases, https://fastapi.metacpan.org/v1/release/Fsdb
4.  get back result: 
 {
   "code" : 404,
   "message" : "Not found"
}
6.  expected result is a json structure that incldues many things, like "author": "JOHNH"
7. (for example, see the results of https://fastapi.metacpan.org/v1/release/DBI )

**Expected behavior**
1. A result from the API that includes the kind of information seen in the pod

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 39)
 - Browser brave
 - Version: 1.63.169
 - (but it seems very unlikely this is a problem on my side)

(I'm opening this ticket in response to a request from noc@metacpan.org)

**Comment by Grinnz** [comment]
It is indexed in PAUSE: https://cpanmeta.grinnz.com/packages?module=Fsdb&match_mode=prefix

One thing that stands out as incorrect is this:

```
=cut
our $VERSION = '3.4';
```

Pod declarations are paragraphs, so a Perl parser may consider that line part of the =cut paragraph and not Perl code.

**Comment by oalders** [comment]
I did a manual re-index and it looks to be fixed. Not sure if this was uploaded while we were having issues a while back. Thanks @jheidemann and @Grinnz!

**Comment by oalders** [comment]
> @oalders: thanks, yes the API call now seems to return what I expect. I had done a manual reindex on pause, but apparently that didn't propagate to metacpan.

Right. MetaCPAN will not necessarily know about a PAUSE re-index if the re-index doesn't change anything.
