### ISSUE TITLE
Missing ++ icon and profile icon on autobox::Core page

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-web#3005]
I'm KARJALA on metacpan. When I visit https://metacpan.org/pod/autobox::Core I don't see my profile icon on the top-right of the page, which I normally see (e.g. I see it on https://metacpan.org/pod/RxPerl).

A different profile icon (the default profile icon of a gray face) appears only when I hover over the profile icon's position with my mouse. But it's not clickable (absolutely nothing happens when I click on it).

I also don't see the ++ clickable icon on the autbox::Core page.

The RxPerl page appears and behaves correctly, however.

The exact same bugs happen when I'm not logged into metacpan and visit the autobox::Core page.

**Screenshots**

https://usercontent.irccloud-cdn.com/file/tA76gKTY/mc.mkv

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Librewolf (Firefox clone)
 - Version: 124.0.1-1

**Comment by akarelas** [comment]
More permanent location of the same video, here: https://files.karelcom.net/public/mc.mkv

**Comment by haarg** [comment]
This sounds like it could be a browser cache issue. If you force refresh the page, does anything change?

Could you check the browser console to see if there are any errors reported?

**Comment by akarelas** [comment]
Additional problem: the SYNOPSIS and all code boxes in the page appear with black text, instead of syntax highlighting (RxPerl on the other hand does have syntax highlighting where it should).

**Comment by akarelas** [comment]
I got this in the browser console:

<img width="545" alt="image" src="https://github.com/metacpan/metacpan-web/assets/423822/82be39ef-09a0-4de7-9ae0-5f37d021a16c">

**Comment by akarelas** [comment]
On the RxPerl page, I get absolutely nothing (errors/warnings/etc) on the console! Only on autobox::Core do I!

**Comment by akarelas** [comment]
I deleted all my cache, and still get the same problem.

**Comment by akarelas** [comment]
Problem seems to have been fixed. Don't know how or when. Maybe was a cache issue.
