### ISSUE TITLE
Add GitHub Action to update image tag used when updating metacpan-web

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-web#3007]
Action should:

1. checkout the metacpan-k8s repository alongside the metacpan-web repository
2. issue the `kustomize edit set image "metacpan/metacpan-web:latest" "metacpan/metacpan-web:${{ github.sha }}"` command
3. commit and push the resulting change back to the metacpan-k8s repository onto `main`

Reference for checking out two repositories in GitHub Actions:
https://github.com/actions/checkout?tab=readme-ov-file#Checkout-multiple-repos-side-by-side

**Comment by haarg** [comment]
We need new deployments to k8s to send a purge of the key `content_type=text/html` to Fastly before this can be automated.
