### ISSUE TITLE
No search results for Devel::Cover

### ISSUE THREAD

**Issue by aspiers** [metacpan/metacpan-web#3009]
## Describe the bug
Searching for `Devel::Cover` or `Devel-Cover` yields no search results.

## To Reproduce

1. Go to https://metacpan.org/
2. Search for `Devel::Cover` or `Devel-Cover`
3. Observe no search results yielded

## Expected behavior
It finds the module.

## Screenshots
![image](https://github.com/metacpan/metacpan-web/assets/100738/dfb243b2-274c-4fa9-a280-24f2552eac6f)

## Additional context
I clicked "Find out why" and verified that it is indeed present in `02packages.details.txt`:
![image](https://github.com/metacpan/metacpan-web/assets/100738/4416139d-85bd-48b0-9f20-963589dee423)

**Comment by mauke** [comment]
Search doesn't seem to be working at all. https://metacpan.org/search?size=20&q=perl also shows "no search results".

**Comment by oalders** [comment]
I believe this is now fixed.
