### ISSUE TITLE
Treex::PML missing

### ISSUE THREAD

**Issue by choroba** [metacpan/metacpan-web#3018]
**Describe the bug**
The distribution Treex::PML can't be found by MetaCPAN. The latest version 2.27 is missing (it exists in [https://cpan.metacpan.org/modules/02packages.details.txt/02packages.details.txt], though). The previous version [2.26](https://metacpan.org/release/CHOROBA/Treex-PML-2.26) exists, but is shown in grey and not accessible through search.

**To Reproduce**
1. Go to (https://metacpan.org)
2. Type `Treex::PML` and hit <kbd>Enter</kbd>
3. The distribution Treex::PML is not shown

Similarly, the page (https://metacpan.org/pod/Treex::PML) shows

 > Not Found
 > 
 > The resource you requested could not be found.

**Expected behavior**
The latest version of the distribution is displayed.

**Comment by atoomic** [comment]
This probably happened during PTS hack while index were rebuilding or servers upgraded 
Looks like `2.27` is listed correctly this morning

<img width="1190" alt="Screenshot 2024-04-26 at 10 37 07" src="https://github.com/metacpan/metacpan-web/assets/405282/b513079c-c4ef-4cc2-a7a5-d2c5e9ddad41">

I think we can close the issue. Feel free to reopen if you think it's still an issue
