### ISSUE TITLE
Long author names are cut off on search results page

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-web#3040]
Note that `CHRISARG` is mostly cut off in this example.

<img width="1788" alt="Screenshot 2024-04-30 at 10 19 16 PM" src="https://github.com/metacpan/metacpan-web/assets/96205/a07a8fff-47c1-47e2-9129-44819ddb331b">

**Comment by dhogan8** [comment]
https://github.com/metacpan/metacpan-web/pull/3041

**Comment by oalders** [comment]
Closed via #3041
