### ISSUE TITLE
Link from POD pointing to wrong file

### ISSUE THREAD

**Issue by Ovid** [metacpan/metacpan-web#3090]
The POD link to `L<OpenAPI::Client::OpenAI::Schema>` is linking to https://metacpan.org/pod/release/OVID/OpenAPI-Client-OpenAI-0.03/devel/build_docs.pl for some reason.

**To Reproduce** Steps to reproduce the behavior:

1. If you visit [OpenAPI::Client::OpenAI v0.3](https://metacpan.org/release/OVID/OpenAPI-Client-OpenAI-0.03/view/lib/OpenAPI/Client/OpenAI.pm), you can see the following text:

> The schema is documented in OpenAPI::Client::OpenAI::Schema

2. If you view the source, the POD is as follows:

```pod
The schema is documented in L<OpenAPI::Client::OpenAI::Schema>
```

3. If you view [the source of the README.md](https://fastapi.metacpan.org/source/OVID/OpenAPI-Client-OpenAI-0.03/README.md), it is also rendered correctly:

```markdown
The schema is documented in [OpenAPI::Client::OpenAI::Schema](https://metacpan.org/pod/OpenAPI%3A%3AClient%3A%3AOpenAI%3A%3ASchema).
```

However, the link on https://metacpan.org/release/OVID/OpenAPI-Client-OpenAI-0.03/view/lib/OpenAPI/Client/OpenAI.pm actually points to https://metacpan.org/pod/release/OVID/OpenAPI-Client-OpenAI-0.03/devel/build_docs.pl.

**Expected behavior** A clear and concise description of what you expected to
happen.

The "OpenAPI::Client::OpenAI::Schema" link should point to the schema doc, not to the script used to build the schema doc.

**Comment by Leont** [comment]
It seems to parse the schema documentation template on line 116 as actual documentation. The easiest solution may be to mark `devel/` as `no_index` in the META file

**Comment by haarg** [comment]
`build_docs.pl` has pod in it that is intended as documentation, but that will never be properly readable because any pod viewer will also show the pod from the templates.

I would recommend indenting all of the code in your templates, then stripping off the leading whitespace when using them.

**Comment by haarg** [comment]
nferraz/perl-openapi-client-openai#4

**Comment by Ovid** [comment]
@haarg Thank you. The issue is now resolved.
