### ISSUE TITLE
The "++" button isn't working

### ISSUE THREAD

**Issue by esabol** [metacpan/metacpan-web#3125]
I'm logged into my MetaCPAN using my PAUSE account. When I click on the "++" button on any module's page, after a 3-10(!) second delay (which I don't consider to be very good usability, fwiw), a pop-up appears that says I need to complete a CAPTCHA in order to use the "++" button. After I click OK and complete the CAPTCHA, I get a "Success" message. However, when I return to module's page and reload the web page, the "++" count has not increased and my account is not listed as a "plusser". I've tried this a bunch of times with multiple distributions with no success.

EDITED TO ADD: I'm using Safari on iPadOS 17.5.1, the latest release.

**Comment by esabol** [comment]
Also, underneath the CAPTCHA "Success" message, there's a link to "Continue browsing". I would expect this link to take me to back to the web page of the module where I clicked the "++" button. It doesn't. It takes me to another CAPTCHA instead. Not very useful.

**Comment by oalders** [comment]
There were issues with disk space yesterday. Is this working for you now?

**Comment by esabol** [comment]
It's working better (no CAPTCHA today), but it doesn't seem perfect. I just ++'ed a distribution, waited a couple seconds, and then reloaded the web page. It didn't show me as having ++'ed it (it still showed zero), but I did see my avatar listed at the bottom of the left sidebar as someone who ++'ed it. Reloading two more times seemed to fix the ++ indicator though, so maybe it was just a caching issue.

Should the issue with the "Continue browsing" link post-CAPTCHA be a separate issue?

**Comment by oalders** [comment]
> Should the issue with the "Continue browsing" link post-CAPTCHA be a separate issue?


I think so. See also https://github.com/metacpan/metacpan-web/issues/572

**Comment by esabol** [comment]
> I think so.

OK, I've opened a new issue for that: #3126. Closing this issue as the problem seems to be resolved.
