### ISSUE TITLE
perl Spreadsheet::WriteExcel is not compatible with office and wps

### ISSUE THREAD

**Issue by Pysion-lin** [metacpan/metacpan-web#3127]
**PLEASE NOTE**

When I use Spreadsheet::WriteExcel to operate xls, it appears that wps can normally display all the processed background colors and font colors, but office can not display normally, there are always some colors lost, may I ask why

![image](https://github.com/metacpan/metacpan-web/assets/51597546/619fbe99-898f-42d7-a020-75573b3a6b9a)

- OS: windows10

I hope that friends who encounter the same problem can share the solution, thank you very much

**Comment by Grinnz** [comment]
This is the bugtracker for the metacpan CPAN search website. The repository for Spreadsheet::WriteExcel is at https://github.com/jmcnamara/spreadsheet-writeexcel and the issue tracker is at https://rt.cpan.org/Public/Dist/Display.html?Name=Spreadsheet-WriteExcel

**Comment by Pysion-lin** [comment]
my code is as follwos
my $parser   = Spreadsheet::ParseExcel->new();
my ($book,@sheets,$sheet);

# $status= (-e $inputFile) ? "$inputFile" : "not exists!";

$book = $parser->parse($inputFile);
@sheets = @{ $book->{Worksheet} };
$sheet =shift @sheets ;


my ($workbook,$worksheet);

eval{
$workbook  = Spreadsheet::WriteExcel->new($outFile);
$worksheet = $workbook->add_worksheet('genotype');
};
ROW_LOOP: for ($row = 0; $row < $sheet->{MaxRow} + 1; $row++){
	for ($col = 0; $col < $sheet->{MaxCol} + 1;$col++){
		my $cell = $sheet->get_cell($row, $col);
		next unless $cell;
		my $a = 'beta substitution';
		my $b = 'alpha substitution';
		my $c = 'deletionResults';
		if ($cell->value() gt $a or $cell->value() gt $b or $cell->value() gt $c){
			$worksheet->freeze_panes(1, 5);
			if ($col != 0){
				$worksheet->set_column($col, $col,15); # set Columns C-E width
			}
		}
				 
		#On s'occupe du format des cellules
		my $format_w = $workbook->add_format();
		my $format_r = $cell->get_format();
		 
		#Font
		if(my $font = $format_r->{Font}) {
			$format_w->set_font($font->{Name});
			$format_w->set_size($font->{Height});
			$format_w->set_color($font->{Color});
			$format_w->set_bold($font->{Bold});
			$format_w->set_italic($font->{Italic});
			$format_w->set_underline($font->{UnderlineStyle});
			$format_w->set_font_strikeout($font->{Strikeout});
			$format_w->set_font_script($font->{Super});
		}
		 
		#Proctection
		$format_w->set_locked($format_r->{Lock});
		$format_w->set_hidden($format_r->{Hidden});
		 
		#Alignment
		$format_w->set_align($format_r->{AlignH});
		$format_w->set_valign($format_r->{AlignV});
		$format_w->set_rotation($format_r->{Rotate});
		$format_w->set_text_wrap($format_r->{Wrap});
		$format_w->set_text_justlast($format_r->{JustLast});
		$format_w->set_shrink($format_r->{Shrink});
		 
		#Pattern
		if(my $pattern = $format_r->{Fill}) {
			$format_w->set_pattern(@$pattern[0]);
			$format_w->set_fg_color(@$pattern[1]);
			$format_w->set_bg_color(@$pattern[2]);
		}
			 
		#Border style
		if(my $borderStyle = $format_r->{BdrStyle}) {
			$format_w->set_left(@$borderStyle[0]);
			$format_w->set_right(@$borderStyle[1]);
			$format_w->set_top(@$borderStyle[2]);
			$format_w->set_bottom(@$borderStyle[3]);
		}
		 
		#Border color
		if(my $borderColor = $format_r->{BdrColor}) {
			$format_w->set_left_color(@$borderColor[0]);
			$format_w->set_right_color(@$borderColor[1]);
			$format_w->set_top_color(@$borderColor[2]);
			$format_w->set_bottom_color(@$borderColor[3]);
		}	
			
		$worksheet->write($row, $col,$cell->value(),$format_w);
	}	

}

**Comment by Pysion-lin** [comment]
report info


    Perl version   : 5.036003
    OS name        : MSWin32
    Module versions: (not all are required)
                     Spreadsheet::WriteExcel    2.40
                     Parse::RecDescent          1.967015
                     File::Temp                 0.2311
                     OLE::Storage_Lite          0.22
                     IO::Stringy                2.113
                     Spreadsheet::ParseExcel    0.66
                     Scalar::Util               1.63
                     Unicode::Map               (not installed)

**Comment by Pysion-lin** [comment]
> 这是metacpan CPAN搜索网站的错误跟踪器。Spreadsheet：：WriteExcel 的存储库位于 https://github.com/jmcnamara/spreadsheet-writeexcel，问题跟踪器位于 https://rt.cpan.org/Public/Dist/Display.html?Name=Spreadsheet-WriteExcel


    Perl version   : 5.036003
    OS name        : MSWin32
    Module versions: (not all are required)
                     Spreadsheet::WriteExcel    2.40
                     Parse::RecDescent          1.967015
                     File::Temp                 0.2311
                     OLE::Storage_Lite          0.22
                     IO::Stringy                2.113
                     Spreadsheet::ParseExcel    0.66
                     Scalar::Util               1.63
                     Unicode::Map               (not installed)

**Comment by Pysion-lin** [comment]
> This is the bugtracker for the metacpan CPAN search website. The repository for Spreadsheet::WriteExcel is at https://github.com/jmcnamara/spreadsheet-writeexcel and the issue tracker is at https://rt.cpan.org/Public/Dist/Display.html?Name=Spreadsheet-WriteExcel


Perl version   : 5.036003
OS name        : MSWin32
Module versions: (not all are required)
                 Spreadsheet::WriteExcel    2.40
                 Parse::RecDescent          1.967015
                 File::Temp                 0.2311
                 OLE::Storage_Lite          0.22
                 IO::Stringy                2.113
                 Spreadsheet::ParseExcel    0.66
                 Scalar::Util               1.63
                 Unicode::Map               (not installed)

**Comment by mickeyn** [comment]
Wrong place to report - please contact the author through the distribution's repo - https://github.com/jmcnamara/spreadsheet-parseexcel
