### ISSUE TITLE
Can't connect to PAUSE account

### ISSUE THREAD

**Issue by tessarin** [metacpan/metacpan-web#3180]
### Description

Despite following all recommended procedures, I’m still unable to connect to my PAUSE account. After discussing this issue on IRC, I’m formalizing the details here.

What I’ve tried so far:

- Tested multiple browsers.
- Tested multiple devices.
- Cleared cookies and cache.
- Verified my email forwarding is correctly set up on PAUSE.
- Disconnected other identities (only GitHub is currently connected).

### Reproducing

The issue consistently occurs as follows:

1. Go to Profile Image > Identities.
2. Click on ‘PAUSE Connect.’
3. Enter my PAUSE username.
4. Encounter the error.

### Error

<img width="667" alt="Screenshot 2024-09-23 at 10 59 27" src="https://github.com/user-attachments/assets/0e338cac-0612-4a37-b346-3487fabf3cf8">

**Comment by oalders** [comment]
@tessarin is this now working for you?

**Comment by tessarin** [comment]
@oalders It did go past that step, but I haven’t closed the issue yet because I can’t fully confirm the resolution. The email confirmation never arrived, and I’m still investigating. It seems the problem is now unrelated to MetaCPAN and is likely with the CPAN email forwarder.

That said, I’m not entirely sure of the full process. If you believe that getting past this step means the original issue is resolved, we can definitely mark this closed. Thanks for your help!

**Comment by tessarin** [comment]
@oalders By the way, do you happen to know what I should do or who I can contact to sort out the @cpan.org email forwarding issue? I’ve tried multiple ways (email, IRC), but haven’t received any replies. Any guidance would be appreciated.

**Comment by oalders** [comment]
I think @rspier might know about the email situation.

**Comment by rspier** [comment]
If you're not receiving @cpan.org email, it's 99.9999% because your email provider is rejecting the email.  There's really nothing we can do about this besides recommending you don't use @cpan.org emails for anything you care about.

**Comment by tessarin** [comment]
@rspier Thanks for your response. Is there any alternative, then? As far as I know, MetaCPAN only sends the verification to that address.

My email provider isn’t uncommon—it’s Gmail. Does this mean that no one uses Gmail for @cpan.org addresses, or am I missing something?

**Comment by rspier** [comment]
I can't speak for MetaCPAN.

Gmail has some of the strictest inbound filtering standards in the industry.   Some days are better, some are worse.  Glancing at the logs, today is not a good day for relaying to Gmail.  I will investigate (as time permits) if there's anything we can do to improve the situation.

**Comment by tessarin** [comment]
I see. Thank you @rspier, once again. It should be worth mentioning that I run Gmail on a custom domain, so I have access to more configuration layers than a free @gmail account. I was wondering if adding cpan.org to my SPF would be of any help. Or, if you happen to know about any other strategy.

**Comment by rspier** [comment]
https://www.youtube.com/watch?v=6DGNZnfKYnU

**Comment by tessarin** [comment]
After switching the secret email to one not hosted by google, the email finally arrived. It too a few tries and there is a big delay, but this means this issue should be closed anyway.

I did encounter other problems along the way. We will discuss this and then open specific issues on the appropriate places.

Thank you!
