### ISSUE TITLE
GitHub popup in author's page contains invalid URLs

### ISSUE THREAD

**Issue by tessarin** [metacpan/metacpan-web#3189]
**Description**

The popup for GitHub profiles located at any author page (considering the author has a GitHub profile connected) shows links to three pages:

 - Followers
 - Following
 - Public Repos

All of these result in 404 pages.

**To Reproduce**

1. Go to your author page `metacpan.org/author/<user>`
2. Hover over the GitHub profile to open the popup
3. Click at any of the 3 links

**Expected behavior**

Visit the appropriate pages.

**Comment by tessarin** [comment]
The reason for this to happen is simple: GitHub changed the address of those pages.

The fix is also quite simple: changing to the new standard. These links are generated with: https://github.com/metacpan/metacpan-web/blob/7028400e2bd2188abd2ad1a3d51f3c897b045085/root/static/js/github.js#L150-L152

If permitted (and desired) I can create a PR to fix this.

**Comment by oalders** [comment]
@tessarin a pull request would be great!
