### ISSUE TITLE
Executable scripts that don't contain Pod are not displayed on release page

### ISSUE THREAD

**Issue by rwstauner** [metacpan/metacpan-web#336]
For example, I was trying to find where this "scraper" script installed on my machine came from...
it seemed likely to come from Web::Scraper, since that's the module it used, but it wasn't listed in the search page
or the release page.

I had to go to the "browse" link to find it.
I'm guessing it's not being included because there's no pod inside,
but a script that gets installed should be shown on that page somewhere.

**Comment by EvanCarroll** [comment]
Still exists, shouldn't have been culled.

* metacpan release: https://metacpan.org/pod/release/ECARROLL/xprop2i3-0.01/scripts/xprop2i3
* profile: https://metacpan.org/author/ECARROLL (which lacks release)
