### ISSUE TITLE
Badly formed dists without a top level directory cause breakage

### ISSUE THREAD

**Issue by haarg** [metacpan/metacpan-web#508]
https://metacpan.org/release/IDIVISION/nginx.pm/

This dist has a single file at the top level in the tarball, and is treated rather strange.  The module and browse links both lead to the HTML source of a directory listing.  The API/raw source also gives strange results: http://api.metacpan.org/source/IDIVISION/nginx.pm/

The dist is packaged entirely wrong so I'm not sure of the best way it should be presented.

**Comment by karenetheridge** [comment]
would it be possible to tag with a label saying something like "not fixed -- needs love"? otherwise it will never be seen in the vast sea of other closed tickets.

**Comment by ranguard** [comment]
@karenetheridge I've opened https://github.com/CPAN-API/cpan-api/issues/436 instead, and that has the 'Volunteer needed' label, so it can get lost in that sea instead :)
