### ISSUE TITLE
Unable to connect my PAUSE account to metaCPAN

### ISSUE THREAD

**Issue by jackmaney** [metacpan/metacpan-web#568]
Hello,

I'm trying to connect my PAUSE account (JACKMANEY) to my metaCPAN account.  The email never seems to never arrive (either in the inbox or the spam folder).

The email address registered to my PAUSE account (jack@jackmaney.com) is set to forward to two other accounts...could that be the cause of the issue?

Thank you for your time,

Jack

**Comment by Bas-Man** [comment]
I am not receiving any email when I attempt to register my newly minted PAUSE ID

**Comment by pamela1122** [comment]
jackmaney same problem with me i am trying to access with the account (PAMELA) pamela@kortingsok.nl butt unable to get the email.

**Comment by oalders** [comment]
@pamela1122 

> jackmaney.com[185.199.111.153]:25: Connection
    timed out
Return-Path: <notifications@metacpan.org>
Received: from compute2.internal (compute2.nyi.internal [10.202.2.46])
	by mailnew.nyi.internal (Postfix) with ESMTP id 26EFA580176;
	Tue,  5 Jul 2022 14:44:50 -0400 (EDT)
Received: from mailfrontend2 ([10.202.2.163])
  by compute2.internal (MEProxy); Tue, 05 Jul 2022 14:44:50 -0400
