### ISSUE TITLE
Use cache control on "latest" module/dist pages

### ISSUE THREAD

**Issue by dagolden** [metacpan/metacpan-web#569]
Pages that point to the "latest" module or distribution, e.g. "https://metacpan.org/module/HTTP::Tiny", should set a cache control header to require revalidation.  Otherwise, a user has to manually refresh to actually see the latest content when a distribution is updated on CPAN.

**Comment by haarg** [comment]
#1765 related

**Comment by haarg** [comment]
This has been fixed.
