### ISSUE TITLE
"Perl" missing on CPAN.

### ISSUE THREAD

**Issue by kentfredric** [metacpan/metacpan-web#734]
https://metacpan.org/search?q=perl
1. ILYAZ/perl_mlb - Mar 14, 1997 - Mar 14, 1997
2. CJFIELDS/BioPerl-1.6.901 - May 19, 2011
3. ADAMK/Perl-Dist-1.16 - Jul 08, 2009

The same thing happens with practically everything that is part of perl itself, ie: `perldebug`

https://metacpan.org/search?q=perldebug
1. ILYAZ/perl_mlb - Mar 14, 1997
2. DAMI/Tree-Navigator-0.05 - Oct 02, 2012
3. RBS/Test-Verbose-0.01 - Mar 09, 2004

**Comment by kentfredric** [comment]
This issue is back.

```irc
[02:08:17] <bulk88> if 5.24 was shipped, why is https://metacpan.org/release/perl missing
[02:09:22] <rjbs> dunno!
```

404: https://metacpan.org/release/perl

**Comment by oalders** [comment]
@kentfredric it's back now.  Thanks for reporting!
