### ISSUE TITLE
Favorites not displaying on author page -- Give author type an updated timestamp as soon as PAUSE account is connected

### ISSUE THREAD

**Issue by mperry2** [metacpan/metacpan-web#852]
I favorited a distribution about a week ago but it's not listed as a favorite on my author page (https://metacpan.org/author/MPERRY). When I view the distribution that I favorited (https://metacpan.org/module/Finance::QIF) I can see that the favorite button is blue, which I assume means that the site knows I've clicked it and recorded it as a favorite.

Expected result:
My author page should list my favorites.

Actual result:
No favorites are listed on my author page.

**Comment by vanstyn** [comment]
My Account is 'VANSTYN' and I still have no favorites. I just disconnected and re-linked with my PAUSE account, and tried updating and saving my profile, and then gave a few more modules ++ ... still nothing, favorites show up blank as always

**Comment by vlyon** [comment]
I'm having the same issue, can't link my GitHub (vlyon) account and my PAUSE (vlyon) account.

**Comment by Relequestual** [comment]
Also having this issue. Logged a new issue for not being able to link both accounts at the same time https://github.com/CPAN-API/metacpan-web/issues/1579

**Comment by bes-internal** [comment]
Sing in with github first time at all. No PAUSE account. Click on fav and enter a captcha at new page. Num increment but favorites page at account is empty.

**Comment by perlpunk** [comment]
The ++ thing never worked for me, but I just didn't bother to find out why. Now I wanted to find out and found this issue.
The instructions in
https://github.com/CPAN-API/metacpan-web/issues/852#issuecomment-34836987
worked for me. There should be at least an FAQ that addresses this.

**Comment by p-alik** [comment]
The ++ thing never worked for me and still doesn't work.
No matter what I do, favorites page is empty

**Comment by vanstyn** [comment]
same here

**Comment by s31tz** [comment]
I see my favorites under https://metacpan.org/account/favorite/list but not on my authors page [https://metacpan.org/author/FSEITZ]. I saved my profile before and after (re)connecting to PAUSE but nothing changed. Any ideas?

**Comment by p-alik** [comment]
As result of [#852](#issuecomment-218082326) both pages https://metacpan.org/account/favorite/list and author page (pause account palik) are empty in my case.

**Comment by s31tz** [comment]
After I uploaded a new distribution, my favorites are now visible on my authors page. It seems to me, that a causal connection exists.

**Comment by p-alik** [comment]
after reconnecting to pause I see favorites on [account favorite list](https://metacpan.org/account/favorite/list) but author page shows 

> No favorite distributions from XXX could be found

**Comment by p-alik** [comment]
magic world! ++ works now as well

**Comment by s31tz** [comment]
Congratulations ;-)
