### ISSUE TITLE
Test::Harness 3.29 POD is different from cpan.org

### ISSUE THREAD

**Issue by willsheppard** [metacpan/metacpan-web#974]
I don't seem to be able to access this POD:
http://search.cpan.org/~ovid/Test-Harness-3.29/lib/Test/Harness.pm

...via metacpan.
I just end up at this page:
https://metacpan.org/module/OVID/Test-Harness-3.29/lib/Test/Harness.pm

which isn't the same.
Specifically, it's missing the "ENVIRONMENT VARIABLES" sections.

Not sure how that's possible or what I'm missing.

**Comment by mohawk2** [comment]
Bit of a drive-by - but I just tried the original s.c.o link, and now it redirects to https://metacpan.org/pod/release/OVID/Test-Harness-3.29/lib/Test/Harness.pm which seems right. Can this be closed?

**Comment by oalders** [comment]
I think this can be closed.  Thanks @mohawk2 and everyone else. :)
